import { contextBridge, ipcRenderer } from 'electron'
import type {
  IpcContractArgs,
  IpcContractResult,
  IpcEventPayload,
  XingmangApi,
  XingmangEventContract,
  XingmangInvokeContract,
} from './ipc-contract'

// Sandboxed preload scripts cannot require local runtime modules. Keep the
// channel maps in this entry file while checking them against the shared types.
const ipcInvokeChannels = {
  getPlatformCapabilities: 'platform:get-capabilities',
  scanSystem: 'system:scan',
  refreshNetworkLocation: 'system:refresh-network-location',
  refreshOfficialChatGptUsage: 'system:refresh-official-chatgpt',
  getCodexReadiness: 'startup:codex-readiness',
  getConfig: 'config:get',
  revealApiKey: 'config:reveal-api-key',
  saveConfig: 'config:save',
  openProviderConfigDirectory: 'config:open-directory',
  configureExternalTool: 'config:configure-external-tool',
  scanExternalClients: 'external-clients:scan',
  installExternalClient: 'external-clients:install',
  launchExternalClient: 'external-clients:launch',
  switchToOfficialAccount: 'config:switch-to-official-account',
  switchAccountSource: 'config:switch-account-source',
  inspectRunningTools: 'tools:inspect-running',
  checkToolModels: 'tools:check-models',
  listModels: 'models:list',
  listConfiguredModels: 'models:list-configured',
  chooseWorkspace: 'workspace:choose',
  getRepositoryContext: 'repository:get-context',
  installNodeRuntime: 'runtime:install-node',
  restartWindows: 'runtime:restart-windows',
  installPythonRuntime: 'runtime:install-python',
  installGitRuntime: 'runtime:install-git',
  installCli: 'cli:install',
  cancelCliInstall: 'cli:cancel-install',
  uninstallCli: 'cli:uninstall',
  checkCliUpdate: 'cli:check-update',
  getCodexSetupStatus: 'setup:codex-status',
  installCodexDesktop: 'desktop:install-codex',
  cancelCodexDesktopInstall: 'desktop:cancel-install-codex',
  uninstallCodexDesktop: 'desktop:uninstall-codex',
  checkCodexDesktopUpdate: 'desktop:check-update-codex',
  launchCli: 'cli:launch',
  getCodexDesktopStatus: 'desktop:codex-status',
  inspectCodexDesktopLocale: 'desktop:codex-locale-status',
  inspectCodexWorkspacePermissions: 'desktop:codex-permissions-status',
  trustCodexWorkspace: 'desktop:trust-workspace',
  setCodexDesktopLocale: 'desktop:set-codex-locale',
  launchCodexDesktop: 'desktop:launch-codex',
  setWindowMode: 'window:set-mode',
  setWindowTheme: 'window:set-theme',
  getWindowCapabilities: 'window:get-capabilities',
  relaunchApp: 'window:relaunch',
  takeExternalDeepLink: 'navigation:take-deep-link',
  replyWindowClose: 'window:close-report',
  openExternal: 'external:open',
  bypassBrokenProxy: 'network:bypass-broken-proxy',
  openNetworkSettings: 'network:open-settings',
  getUpdateState: 'update:get-state',
  runStartupUpdate: 'update:startup',
  checkForUpdates: 'update:check',
  downloadUpdate: 'update:download',
  installUpdate: 'update:install',
  listSessions: 'sessions:list',
  getSessionDetail: 'sessions:detail',
  exportSession: 'sessions:export',
  archiveSession: 'sessions:archive',
  restoreSession: 'sessions:restore',
  listProviderSessions: 'provider-sessions:list',
  getProviderSessionDetail: 'provider-sessions:detail',
  exportProviderSession: 'provider-sessions:export',
  openProviderSessionDirectory: 'provider-sessions:open-directory',
  getSettings: 'settings:get',
  saveSettings: 'settings:save',
  runDiagnostics: 'diagnostics:run',
  exportDiagnostics: 'diagnostics:export',
  getRuntimeLogs: 'runtime-logs:list',
  getFeedbackReport: 'runtime-logs:preview-feedback',
  copyFeedbackReport: 'runtime-logs:copy-feedback',
  exportFeedbackReport: 'runtime-logs:export-feedback',
  revealExportedFile: 'exports:reveal-file',
  openRuntimeLogDirectory: 'runtime-logs:open-directory',
  clearRuntimeLogs: 'runtime-logs:clear',
  reportRendererError: 'runtime-logs:renderer-error',
  listBackups: 'backups:list',
  createBackup: 'backups:create',
  inspectBackup: 'backups:inspect',
  restoreBackup: 'backups:restore',
  deleteBackup: 'backups:delete',
  listMcpServers: 'mcp:list',
  addMcpServer: 'mcp:add',
  removeMcpServer: 'mcp:remove',
  loginMcpServer: 'mcp:login',
  logoutMcpServer: 'mcp:logout',
  listSkills: 'skills:list',
  importSkill: 'skills:import',
  toggleSkill: 'skills:toggle',
  uninstallSkill: 'skills:uninstall',
  listPlugins: 'plugins:list',
  addPlugin: 'plugins:add',
  removePlugin: 'plugins:remove',
  togglePlugin: 'plugins:toggle',
  addMarketplace: 'marketplaces:add',
  upgradeMarketplace: 'marketplaces:upgrade',
  removeMarketplace: 'marketplaces:remove',
  listProviderExtensions: 'extensions:list',
  listAllProviderExtensions: 'extensions:list-all',
  mutateProviderExtension: 'extensions:mutate',
  ensureProviderMarketplace: 'extensions:ensure-marketplace',
  checkProviderMcpHealth: 'extensions:check-mcp-health',
  getAccountStatus: 'account:get-status',
  getAccountNotice: 'account:get-notice',
  markAccountNoticeRead: 'account:mark-notice-read',
  syncLocalNoticeReads: 'account:sync-local-notice-reads',
  getAccelerationState: 'acceleration:get-state',
  listAccelerationLines: 'acceleration:list-lines',
  pingAccelerationLine: 'acceleration:ping-line',
  startAcceleration: 'acceleration:start',
  stopAcceleration: 'acceleration:stop',
  redeemAccelerationCode: 'acceleration:redeem-code',
  getAccelerationPreference: 'acceleration:get-preference',
  saveAccelerationPreference: 'acceleration:save-preference',
  getLegalDocument: 'account:get-legal-document',
  loginAccount: 'account:login',
  submitTwoFactorCode: 'account:submit-two-factor-code',
  logoutAccount: 'account:logout',
  getAccountSession: 'account:get-session',
  listSavedAccounts: 'account:list-saved',
  switchSavedAccount: 'account:switch-saved',
  removeSavedAccount: 'account:remove-saved',
  getAccountBalance: 'account:get-balance',
  getAccountTopupInfo: 'account:get-topup-info',
  quoteAccountTopupAmount: 'account:quote-topup',
  createAccountTopupPayment: 'account:create-topup-payment',
  closeAccountPaymentWindow: 'account:close-payment-window',
  getAccountTopupOrders: 'account:list-topup-orders',
  redeemAccountTopupCode: 'account:redeem-topup-code',
  transferAccountAffiliateQuota: 'account:transfer-affiliate-quota',
  getAccountSubscriptionPlans: 'account:list-subscription-plans',
  getAccountSubscriptionSelf: 'account:get-subscription-self',
  updateAccountSubscriptionPreference: 'account:update-subscription-preference',
  createAccountSubscriptionPayment: 'account:create-subscription-payment',
  purchaseAccountSubscriptionWithBalance: 'account:purchase-subscription-balance',
  syncManagedCliKeys: 'account:sync-managed-cli-keys',
  configureManagedCliKeys: 'account:configure-managed-clis',
  registerAccount: 'account:register',
  sendVerificationCode: 'account:send-verification-code',
  sendPasswordResetCode: 'account:send-reset-code',
  resetPassword: 'account:reset-password',
  getAccountProfile: 'account:get-profile',
  updateAccountDisplayName: 'account:update-display-name',
  getAccountUsage: 'account:get-usage',
  getAccountDashboard: 'account:get-dashboard',
  getAccountTasks: 'account:get-tasks',
  getAccountKeys: 'account:list-keys',
  getAccountUsableGroups: 'account:list-groups',
  revokeAccountKey: 'account:revoke-key',
  copyAccountKey: 'account:copy-key',
  revealAccountKey: 'account:reveal-key',
  listAccountKeyModels: 'account:list-key-models',
  saveConfigWithAccountKey: 'account:configure-cli-with-key',
  changeAccountPassword: 'account:change-password',
  getAccountLoginSessions: 'account:list-login-sessions',
  revokeAccountLoginSession: 'account:revoke-login-session',
  revokeOtherAccountLoginSessions: 'account:revoke-other-login-sessions',
  openCanvasWindow: 'canvas:open',
  getRememberedAccountLogin: 'account:get-remembered-login',
  setRememberedAccountLogin: 'account:set-remembered-login',
  createAccountKey: 'account:create-key',
  updateAccountKey: 'account:update-key',
  listAiChatGroups: 'chat:list-groups',
  prepareAiChatGroup: 'chat:prepare-group',
  startAiChat: 'chat:start',
  generateAiImage: 'chat:generate-image',
  cancelAiChat: 'chat:cancel',
  copyAiChatAsset: 'chat:copy-asset',
  saveAiChatAsset: 'chat:save-asset',
  showAiChatAssetMenu: 'chat:asset-menu',
  readAiChatHistory: 'chat-history:read',
  writeAiChatHistory: 'chat-history:write',
  checkProviderConnection: 'diagnostics:check-connection',
  checkExternalClientConnection: 'diagnostics:check-external-connection',
  getAccountKeyOptions: 'account:get-key-options',
} as const satisfies {
  [Method in keyof XingmangInvokeContract]: XingmangInvokeContract[Method]['channel']
}

const ipcEventChannels = {
  onExternalClientInstallProgress: 'external-clients:install-progress',
  onAccountSessionChanged: 'account:session-changed',
  onAccountUsageChanged: 'account:usage-changed',
  onAccountVaultRecovered: 'account:vault-recovered',
  onNavigate: 'navigation:open-page',
  onWindowCloseRequest: 'window:close-request',
  onExternalDeepLink: 'navigation:deep-link-pending',
  onLaunchTool: 'window:launch-tool',
  onNodeRuntimeInstallProgress: 'runtime:node-install-progress',
  onPythonRuntimeInstallProgress: 'runtime:python-install-progress',
  onGitRuntimeInstallProgress: 'runtime:git-install-progress',
  onInstallProgress: 'cli:install-progress',
  onCodexDesktopStatus: 'desktop:codex-status-changed',
  onCodexDesktopInstallProgress: 'desktop:codex-install-progress',
  onUpdateState: 'update:state-changed',
  onAccountPaymentWindowTerminal: 'account:payment-window-terminal',
  onAiChatStream: 'chat:stream-event',
} as const satisfies {
  [Method in keyof XingmangEventContract]: XingmangEventContract[Method]['channel']
}

function invoke<Method extends keyof XingmangInvokeContract>(
  method: Method,
  ...args: IpcContractArgs<XingmangInvokeContract[Method]>
): Promise<IpcContractResult<XingmangInvokeContract[Method]>> {
  return ipcRenderer.invoke(ipcInvokeChannels[method], ...args) as Promise<
    IpcContractResult<XingmangInvokeContract[Method]>
  >
}

function subscribe<Method extends keyof XingmangEventContract>(
  method: Method,
  listener: (payload: IpcEventPayload<XingmangEventContract[Method]>) => void,
): () => void {
  const channel = ipcEventChannels[method]
  const handler = (_event: Electron.IpcRendererEvent, payload: unknown) => {
    listener(payload as IpcEventPayload<XingmangEventContract[Method]>)
  }
  ipcRenderer.on(channel, handler)
  return () => ipcRenderer.removeListener(channel, handler)
}

const xingmangApi: XingmangApi = {
  getPlatformCapabilities: () => invoke('getPlatformCapabilities'),
  scanSystem: (forceRefresh, options) => invoke('scanSystem', forceRefresh, options),
  refreshNetworkLocation: () => invoke('refreshNetworkLocation'),
  refreshOfficialChatGptUsage: () => invoke('refreshOfficialChatGptUsage'),
  getCodexReadiness: () => invoke('getCodexReadiness'),
  getConfig: () => invoke('getConfig'),
  revealApiKey: (provider) => invoke('revealApiKey', provider),
  saveConfig: (payload) => invoke('saveConfig', payload),
  openProviderConfigDirectory: (provider) => invoke('openProviderConfigDirectory', provider),
  configureExternalTool: (tool, options) => invoke('configureExternalTool', tool, options),
  scanExternalClients: (force) => invoke('scanExternalClients', force),
  installExternalClient: (tool) => invoke('installExternalClient', tool),
  launchExternalClient: (tool) => invoke('launchExternalClient', tool),
  switchToOfficialAccount: (provider, mode) => mode === undefined
    ? invoke('switchToOfficialAccount', provider)
    : invoke('switchToOfficialAccount', provider, mode),
  switchAccountSource: (provider, target) => invoke('switchAccountSource', provider, target),
  inspectRunningTools: (providers) => invoke('inspectRunningTools', providers),
  checkToolModels: (provider) => invoke('checkToolModels', provider),
  listModels: (apiKey) => invoke('listModels', apiKey),
  listConfiguredModels: (provider) => invoke('listConfiguredModels', provider),
  chooseWorkspace: (options) => options === undefined ? invoke('chooseWorkspace') : invoke('chooseWorkspace', options),
  getRepositoryContext: () => invoke('getRepositoryContext'),
  installNodeRuntime: () => invoke('installNodeRuntime'),
  restartWindows: () => invoke('restartWindows'),
  installPythonRuntime: () => invoke('installPythonRuntime'),
  installGitRuntime: () => invoke('installGitRuntime'),
  installCli: (provider, version) => invoke('installCli', provider, version),
  cancelCliInstall: (provider) => invoke('cancelCliInstall', provider),
  uninstallCli: (provider) => invoke('uninstallCli', provider),
  checkCliUpdate: (provider) => invoke('checkCliUpdate', provider),
  getCodexSetupStatus: () => invoke('getCodexSetupStatus'),
  installCodexDesktop: () => invoke('installCodexDesktop'),
  cancelCodexDesktopInstall: () => invoke('cancelCodexDesktopInstall'),
  uninstallCodexDesktop: () => invoke('uninstallCodexDesktop'),
  checkCodexDesktopUpdate: () => invoke('checkCodexDesktopUpdate'),
  launchCli: (provider, workspace, mode) => invoke('launchCli', provider, workspace, mode),
  getCodexDesktopStatus: () => invoke('getCodexDesktopStatus'),
  inspectCodexDesktopLocale: () => invoke('inspectCodexDesktopLocale'),
  inspectCodexWorkspacePermissions: () => invoke('inspectCodexWorkspacePermissions'),
  trustCodexWorkspace: () => invoke('trustCodexWorkspace'),
  setCodexDesktopLocale: (locale) => invoke('setCodexDesktopLocale', locale),
  launchCodexDesktop: (mode) => invoke('launchCodexDesktop', mode),
  setWindowMode: (mode) => invoke('setWindowMode', mode),
  setWindowTheme: (theme) => invoke('setWindowTheme', theme),
  getWindowCapabilities: () => invoke('getWindowCapabilities'),
  relaunchApp: () => invoke('relaunchApp'),
  takeExternalDeepLink: () => invoke('takeExternalDeepLink'),
  replyWindowClose: (requestId, report) => invoke('replyWindowClose', requestId, report),
  openExternal: (url) => invoke('openExternal', url),
  bypassBrokenProxy: () => invoke('bypassBrokenProxy'),
  openNetworkSettings: (kind) => invoke('openNetworkSettings', kind),
  getUpdateState: () => invoke('getUpdateState'),
  runStartupUpdate: () => invoke('runStartupUpdate'),
  checkForUpdates: () => invoke('checkForUpdates'),
  downloadUpdate: () => invoke('downloadUpdate'),
  installUpdate: () => invoke('installUpdate'),
  listSessions: (query) => invoke('listSessions', query),
  getSessionDetail: (sessionId) => invoke('getSessionDetail', sessionId),
  exportSession: (sessionId) => invoke('exportSession', sessionId),
  archiveSession: (sessionId) => invoke('archiveSession', sessionId),
  restoreSession: (sessionId) => invoke('restoreSession', sessionId),
  listProviderSessions: (query) => invoke('listProviderSessions', query),
  getProviderSessionDetail: (sessionId) => invoke('getProviderSessionDetail', sessionId),
  exportProviderSession: (sessionId) => invoke('exportProviderSession', sessionId),
  openProviderSessionDirectory: (sessionId) => invoke('openProviderSessionDirectory', sessionId),
  getSettings: () => invoke('getSettings'),
  saveSettings: (settings) => invoke('saveSettings', settings),
  runDiagnostics: (options) => invoke('runDiagnostics', options),
  exportDiagnostics: () => invoke('exportDiagnostics'),
  getRuntimeLogs: (limit) => invoke('getRuntimeLogs', limit),
  getFeedbackReport: () => invoke('getFeedbackReport'),
  copyFeedbackReport: (reportId) => invoke('copyFeedbackReport', reportId),
  exportFeedbackReport: (reportId) => invoke('exportFeedbackReport', reportId),
  revealExportedFile: (filePath) => invoke('revealExportedFile', filePath),
  openRuntimeLogDirectory: () => invoke('openRuntimeLogDirectory'),
  clearRuntimeLogs: () => invoke('clearRuntimeLogs'),
  reportRendererError: (payload) => invoke('reportRendererError', payload),
  listBackups: () => invoke('listBackups'),
  createBackup: (provider) => invoke('createBackup', provider),
  inspectBackup: (id) => invoke('inspectBackup', id),
  restoreBackup: (id) => invoke('restoreBackup', id),
  deleteBackup: (id) => invoke('deleteBackup', id),
  listMcpServers: () => invoke('listMcpServers'),
  addMcpServer: (input) => invoke('addMcpServer', input),
  removeMcpServer: (name) => invoke('removeMcpServer', name),
  loginMcpServer: (name) => invoke('loginMcpServer', name),
  logoutMcpServer: (name) => invoke('logoutMcpServer', name),
  listSkills: () => invoke('listSkills'),
  importSkill: (input) => invoke('importSkill', input),
  toggleSkill: (skillPath, enabled) => invoke('toggleSkill', skillPath, enabled),
  uninstallSkill: (skillPath) => invoke('uninstallSkill', skillPath),
  listPlugins: () => invoke('listPlugins'),
  addPlugin: (selector) => invoke('addPlugin', selector),
  removePlugin: (selector) => invoke('removePlugin', selector),
  togglePlugin: (selector, enabled) => invoke('togglePlugin', selector, enabled),
  addMarketplace: (input) => invoke('addMarketplace', input),
  upgradeMarketplace: (name) => invoke('upgradeMarketplace', name),
  removeMarketplace: (name) => invoke('removeMarketplace', name),
  listProviderExtensions: (provider) => invoke('listProviderExtensions', provider),
  listAllProviderExtensions: () => invoke('listAllProviderExtensions'),
  mutateProviderExtension: (input) => invoke('mutateProviderExtension', input),
  ensureProviderMarketplace: (provider) => invoke('ensureProviderMarketplace', provider),
  checkProviderMcpHealth: (provider) => invoke('checkProviderMcpHealth', provider),
  getAccountStatus: (siteId) => siteId === undefined ? invoke('getAccountStatus') : invoke('getAccountStatus', siteId),
  getAccountNotice: (mode) => mode === undefined ? invoke('getAccountNotice') : invoke('getAccountNotice', mode),
  markAccountNoticeRead: (id, entryId) => invoke('markAccountNoticeRead', id, entryId),
  syncLocalNoticeReads: (scope, ids) => invoke('syncLocalNoticeReads', scope, ids),
  getAccelerationState: (scope) => invoke('getAccelerationState', scope),
  listAccelerationLines: (scope) => invoke('listAccelerationLines', scope),
  pingAccelerationLine: (scope, lineId) => invoke('pingAccelerationLine', scope, lineId),
  // 四个参数都要过桥。第四个是用户看过冲突提示后按下的「仍然连接」，少转一个
  // 它就永远是 undefined，主进程那边照样按「没确认过」再拒一次（I5 的校验没错，
  // 错在请求根本没带上那次确认）。末尾的可选参数按实际传入的个数转发，空位不
  // 补 undefined。
  startAcceleration: (scope, mode, lineId, ignoreConflicts) => ignoreConflicts === undefined
    ? lineId === undefined ? invoke('startAcceleration', scope, mode) : invoke('startAcceleration', scope, mode, lineId)
    : invoke('startAcceleration', scope, mode, lineId, ignoreConflicts),
  stopAcceleration: (scope) => invoke('stopAcceleration', scope),
  redeemAccelerationCode: (scope, code) => invoke('redeemAccelerationCode', scope, code),
  getAccelerationPreference: (scope) => invoke('getAccelerationPreference', scope),
  saveAccelerationPreference: (scope, update) => invoke('saveAccelerationPreference', scope, update),
  getLegalDocument: (kind, siteId) => siteId === undefined ? invoke('getLegalDocument', kind) : invoke('getLegalDocument', kind, siteId),
  loginAccount: (input) => invoke('loginAccount', input),
  submitTwoFactorCode: (code) => invoke('submitTwoFactorCode', code),
  logoutAccount: () => invoke('logoutAccount'),
  getAccountSession: () => invoke('getAccountSession'),
  listSavedAccounts: () => invoke('listSavedAccounts'),
  switchSavedAccount: (id) => invoke('switchSavedAccount', id),
  removeSavedAccount: (id) => invoke('removeSavedAccount', id),
  getAccountBalance: () => invoke('getAccountBalance'),
  getAccountTopupInfo: () => invoke('getAccountTopupInfo'),
  quoteAccountTopupAmount: (input) => invoke('quoteAccountTopupAmount', input),
  createAccountTopupPayment: (input) => invoke('createAccountTopupPayment', input),
  closeAccountPaymentWindow: () => invoke('closeAccountPaymentWindow'),
  getAccountTopupOrders: (input) => invoke('getAccountTopupOrders', input),
  redeemAccountTopupCode: (code) => invoke('redeemAccountTopupCode', code),
  transferAccountAffiliateQuota: (input) => invoke('transferAccountAffiliateQuota', input),
  getAccountSubscriptionPlans: () => invoke('getAccountSubscriptionPlans'),
  getAccountSubscriptionSelf: () => invoke('getAccountSubscriptionSelf'),
  updateAccountSubscriptionPreference: (preference) => invoke('updateAccountSubscriptionPreference', preference),
  createAccountSubscriptionPayment: (input) => invoke('createAccountSubscriptionPayment', input),
  purchaseAccountSubscriptionWithBalance: (planId) => invoke('purchaseAccountSubscriptionWithBalance', planId),
  syncManagedCliKeys: () => invoke('syncManagedCliKeys'),
  configureManagedCliKeys: (input) => invoke('configureManagedCliKeys', input),
  registerAccount: (input) => invoke('registerAccount', input),
  sendVerificationCode: (email) => invoke('sendVerificationCode', email),
  sendPasswordResetCode: (email, siteId) => invoke('sendPasswordResetCode', email, siteId),
  resetPassword: (input, siteId) => invoke('resetPassword', input, siteId),
  getAccountProfile: () => invoke('getAccountProfile'),
  updateAccountDisplayName: (input) => invoke('updateAccountDisplayName', input),
  getAccountUsage: (input) => invoke('getAccountUsage', input),
  getAccountDashboard: (input) => invoke('getAccountDashboard', input),
  getAccountTasks: (input) => invoke('getAccountTasks', input),
  getAccountKeys: (input) => invoke('getAccountKeys', input),
  getAccountUsableGroups: () => invoke('getAccountUsableGroups'),
  revokeAccountKey: (id) => invoke('revokeAccountKey', id),
  copyAccountKey: (id) => invoke('copyAccountKey', id),
  revealAccountKey: (id) => invoke('revealAccountKey', id),
  listAccountKeyModels: (id) => invoke('listAccountKeyModels', id),
  saveConfigWithAccountKey: (input) => invoke('saveConfigWithAccountKey', input),
  changeAccountPassword: (input) => invoke('changeAccountPassword', input),
  getAccountLoginSessions: () => invoke('getAccountLoginSessions'),
  revokeAccountLoginSession: (sid) => invoke('revokeAccountLoginSession', sid),
  revokeOtherAccountLoginSessions: () => invoke('revokeOtherAccountLoginSessions'),
  openCanvasWindow: () => invoke('openCanvasWindow'),
  getRememberedAccountLogin: (siteId) => siteId === undefined ? invoke('getRememberedAccountLogin') : invoke('getRememberedAccountLogin', siteId),
  setRememberedAccountLogin: (input, siteId) => siteId === undefined ? invoke('setRememberedAccountLogin', input) : invoke('setRememberedAccountLogin', input, siteId),
  createAccountKey: (input) => invoke('createAccountKey', input),
  updateAccountKey: (input) => invoke('updateAccountKey', input),
  listAiChatGroups: () => invoke('listAiChatGroups'),
  prepareAiChatGroup: (group) => invoke('prepareAiChatGroup', group),
  startAiChat: (input) => invoke('startAiChat', input),
  generateAiImage: (input) => invoke('generateAiImage', input),
  cancelAiChat: (requestId) => invoke('cancelAiChat', requestId),
  copyAiChatAsset: (assetId) => invoke('copyAiChatAsset', assetId),
  saveAiChatAsset: (assetId) => invoke('saveAiChatAsset', assetId),
  showAiChatAssetMenu: (assetId) => invoke('showAiChatAssetMenu', assetId),
  readAiChatHistory: (scope) => invoke('readAiChatHistory', scope),
  writeAiChatHistory: (input) => invoke('writeAiChatHistory', input),
  checkProviderConnection: (provider) => invoke('checkProviderConnection', provider),
  checkExternalClientConnection: (tool) => invoke('checkExternalClientConnection', tool),
  getAccountKeyOptions: (provider) => invoke('getAccountKeyOptions', provider),
  onAccountSessionChanged: (listener) => subscribe('onAccountSessionChanged', listener),
  onExternalClientInstallProgress: (listener) => subscribe('onExternalClientInstallProgress', listener),
  onAccountUsageChanged: (listener) => subscribe('onAccountUsageChanged', listener),
  onAccountVaultRecovered: (listener) => subscribe('onAccountVaultRecovered', listener),
  onNavigate: (listener) => subscribe('onNavigate', listener),
  onWindowCloseRequest: (listener) => subscribe('onWindowCloseRequest', listener),
  onExternalDeepLink: (listener) => subscribe('onExternalDeepLink', listener),
  onLaunchTool: (listener) => subscribe('onLaunchTool', listener),
  onNodeRuntimeInstallProgress: (listener) => subscribe('onNodeRuntimeInstallProgress', listener),
  onPythonRuntimeInstallProgress: (listener) => subscribe('onPythonRuntimeInstallProgress', listener),
  onGitRuntimeInstallProgress: (listener) => subscribe('onGitRuntimeInstallProgress', listener),
  onInstallProgress: (listener) => subscribe('onInstallProgress', listener),
  onCodexDesktopStatus: (listener) => subscribe('onCodexDesktopStatus', listener),
  onCodexDesktopInstallProgress: (listener) => subscribe('onCodexDesktopInstallProgress', listener),
  onUpdateState: (listener) => subscribe('onUpdateState', listener),
  onAccountPaymentWindowTerminal: (listener) => subscribe('onAccountPaymentWindowTerminal', listener),
  onAiChatStream: (listener) => subscribe('onAiChatStream', listener),
}

contextBridge.exposeInMainWorld('xingmang', xingmangApi)
