import type { PageId } from './pages';
import { accelerationExpiryWarningSeconds, accelerationTrialSeconds } from '../../../electron/acceleration-contract';
import { macDesktopTutorialTopic, macRuntimeTutorialTopic } from './business';
import { errors } from './errors';
import { statuses } from './status';
import { firstRunHints } from './tools';
import { runtimeButtonLabel, runtimeHomebrewCommand } from '../features/tools/runtime-install-guide';

export type TutorialIllustrationId = 'desktop-home' | 'desktop-install' | 'desktop-config' | 'desktop-project' | 'desktop-message' | 'home' | 'account' | 'install' | 'config' | 'launch' | 'chat' | 'canvas' | 'acceleration' | 'extensions' | 'skills' | 'plugins' | 'backup' | 'health';

export interface TutorialStep {
  title: string;
  detail: string;
  where?: string;
  bullets?: readonly string[];
  expected?: string;
  tip?: string;
  example?: string;
  illustration?: TutorialIllustrationId;
  extra?: readonly { title: string; detail: string }[];
  action: string;
  page: PageId;
}

export interface TutorialTopic {
  id: string;
  title: string;
  lead: string;
  category: 'start' | 'everyday' | 'advanced';
  minutes: number;
  keywords: readonly string[];
  steps: readonly TutorialStep[];
  reminders?: readonly string[];
}

export const tutorialTopics: readonly TutorialTopic[] = [
  {
    id: 'start',
    title: '第一次用？照着这 4 步做',
    lead: '工具箱帮你装好、配好 Codex 桌面端。跟着做，最后在 Codex 窗口里发出第一条消息。',
    category: 'start',
    minutes: 5,
    keywords: ['新手', '入门', '第一次', '不会用', '安装', '登录', '首页', 'Codex', '桌面端', '图形界面'],
    steps: [
      {
        title: '登录星芒账号',
        where: '工具箱左下角 → 账号',
        detail: '用你自己的星芒账号登录。左下角已经显示账号名字的，直接看第 2 步。',
        bullets: ['点左下角账号区域，输入账号和密码。', '没有账号就按登录窗口里的注册入口操作。'],
        expected: '左下角显示你的账号名字。',
        illustration: 'account',
        action: '打开个人中心',
        page: 'account',
      },
      {
        title: '装好 Codex 桌面端',
        where: '工具箱首页 → Codex 桌面端',
        detail: '找准「Codex 桌面端」这一行。已经显示版本号的，不用重复安装。',
        bullets: ['Windows：点「安装」，等进度结束。', 'Mac：先在应用外装好官方 Codex App，再回首页点「重新检测」。'],
        expected: 'Codex 桌面端显示已安装版本。',
        illustration: 'desktop-install',
        extra: [{ title: '下载完还不算装好？', detail: 'Mac 按安装包说明完成安装；要求拖入「应用程序」时要完成这一步。Windows 安装报错时按提示处理，详细步骤见「Codex 桌面端怎么安装？」。桌面端不用先装 Codex CLI、Node.js 或 Python。' }],
        action: '去首页找 Codex 桌面端',
        page: 'home',
      },
      {
        title: '看到「已配好」就继续',
        where: '工具箱首页 → Codex 桌面端 → 状态',
        detail: '工具箱通常会自动配好。已经显示「已配好」就看第 4 步；显示「连接账号」时，才需要下面的操作。',
        bullets: ['点「连接账号」，选择「使用星芒账号」。', '需要准备密钥时选「自动准备/复用」；密钥就是工具调用 AI 用的通行证。', '点「保存配置」，再选「仅更新账号来源、密钥和模型」。'],
        expected: 'Codex 桌面端这一行显示「已配好」。',
        illustration: 'desktop-config',
        extra: [{ title: '没配成功怎么办？', detail: '看到分组或密钥读取失败时，先点「刷新密钥」，读到后再保存；自动准备会使用该分组默认模型。已有自己的密钥或想换模型，详见「Codex 怎么连接账号、换模型？」。' }],
        action: '去首页看是否已配好',
        page: 'home',
      },
      {
        title: '打开 Codex，发出第一条消息',
        where: '工具箱首页 → Codex 桌面端「打开」→ Codex 对话框',
        detail: '点击「打开」，后面的操作在新出现的 Codex 窗口里完成。先问一个简单问题，不用选择文件夹。',
        bullets: ['在 Codex 里开始新对话（英文界面可能写 New chat）。', '输入下面这句话并发送，等待回复。'],
        example: '你好，请用中文告诉我你能帮我做什么。',
        expected: 'Codex 回了一段完整文字，你就可以开始用了。',
        illustration: 'desktop-message',
        extra: [{ title: '提示 Codex 已在运行？', detail: '点「打开窗口」回到现有窗口。刚改过配置，需要重新读取时，先保存任务再选「重启 Codex」。' }],
        action: '回首页打开 Codex',
        page: 'home',
      },
    ],
    reminders: ['AI 写出来的代码和给出的结论都可能出错，合并或执行之前自己再过一遍。', '粘贴来路不明的网页、文档或日志时留个心眼，里面可能藏着让 AI 去做别的事的指令。'],
  },
  {
    id: 'install',
    title: 'Codex 桌面端怎么安装？',
    lead: 'Windows 和 Mac 走不同的安装步骤，选你正在用的电脑。',
    category: 'start',
    minutes: 4,
    keywords: ['Codex', '桌面端', 'Windows', 'Mac', 'macOS', '苹果', '安装', '下载', '已安装', '未安装', '检测失败', '商店'],
    steps: [
      {
        title: '确认看的是「Codex 桌面端」',
        where: '工具箱首页 → 还可以装 / 你的工具',
        detail: '找到名字完整写着「Codex 桌面端」的工具。它和「Codex CLI」是两个程序。',
        bullets: ['未安装时，在「还可以装」里找。', '已安装时，在「你的工具」里看版本。'],
        expected: '找到 Codex 桌面端自己的安装状态。',
        illustration: 'desktop-install',
        action: '打开安装卸载',
        page: 'maintenance',
      },
      {
        title: 'Windows：点安装，等它装完',
        where: '工具箱首页 → Codex 桌面端 → 安装',
        detail: '安装由工具箱完成，不用先装 Node.js 或 Python。',
        bullets: ['点一次「安装」，等待下载和安装进度结束。', '出现版本号后再看账号连接状态。'],
        expected: 'Codex 桌面端显示版本号。',
        extra: [{ title: '安装报错或要求去微软商店？', detail: '按错误提示完成商店安装后回来「重新检测」。下载失败先看具体原因；「更多」→「安装卸载」可查看安装日志。' }],
        action: '去首页安装桌面端',
        page: 'home',
      },
      {
        title: 'Mac：装好官方应用，再回来检测',
        where: 'Mac 官方安装包 → 工具箱首页 → 重新检测',
        detail: 'Mac 需要在工具箱外安装官方 Codex App。',
        bullets: ['从官方渠道下载 Mac 安装包，按说明完成安装。', '要求拖入「应用程序」时先完成拖入，再打开应用。', '回工具箱首页点「重新检测」。'],
        expected: '工具箱显示 Codex 桌面端已安装。',
        extra: [{ title: 'Mac 需要先装 Homebrew 吗？', detail: '使用桌面端不用装 Homebrew、Node.js 或 Codex CLI。「Mac 上装 Node.js 和 Python」一章只用于命令行工具。' }],
        action: '回首页重新检测',
        page: 'home',
      },
      {
        title: '装好了却没显示，先重新检测',
        where: '工具箱首页 → 重新检测',
        detail: '先确认电脑本身能打开 Codex，再让工具箱重新检测。',
        bullets: ['Windows：使用安装 Codex 的同一个系统用户。', 'Mac：确认完成了安装，不是只打开下载的安装包。'],
        expected: '识别成功后能看到版本；仍失败就记下具体错误。',
        extra: [{ title: '显示检测失败，不是未安装？', detail: '表示工具箱这次没读到可靠结果。到「检查」查看原因，仍无法解决时到「反馈」预览报告交给客服。' }],
        action: '回首页核对桌面端',
        page: 'home',
      },
    ],
  },
  {
    id: 'config',
    title: 'Codex 怎么连接账号、换模型？',
    lead: '已经「已配好」而且能正常回复，就不用改。需要连接账号或换模型时，再跟着这一章做。',
    category: 'start',
    minutes: 4,
    keywords: ['Codex', '桌面端', '配置', '模型', 'Key', 'API Key', '密钥', '分组', '自动配置', '保存', '重置', 'ChatGPT', '官方账号'],
    steps: [
      {
        title: '打开配置，选择星芒账号',
        where: '工具箱首页 → Codex 桌面端 → … → 配置',
        detail: '配置就是告诉 Codex 使用哪个账号。使用星芒额度时，选「使用星芒账号」。',
        bullets: ['点「连接账号」，或「…」里的「配置」。', '确认弹窗写的是「Codex 桌面端 配置」。'],
        expected: '「使用星芒账号」已选中。',
        extra: [{ title: '想用自己的 Key 或 ChatGPT 账号？', detail: '自己的星芒 Key 选「自己填写密钥」，粘贴完整内容；官方账号选「ChatGPT 账号」，保存后到 Codex 完成官方登录。Codex CLI 与桌面端共用配置，修改会影响两者。' }],
        illustration: 'desktop-config',
        action: '去首页打开 Codex 配置',
        page: 'home',
      },
      {
        title: '确认访问密钥',
        where: 'Codex 配置窗口 → 访问密钥（Key）',
        detail: '密钥是调用 AI 的通行证；分组决定能用哪些模型。已有可用密钥可以保留，没有时再选自动准备。',
        bullets: ['保留正在正常使用的「当前密钥」。', '首次配置可选「自动准备/复用」，查看下方显示的分组。', '提示读取失败时点「刷新密钥」，读到后再保存。'],
        expected: '密钥与分组已明确，没有读取失败提示。',
        extra: [{ title: '选已有密钥有什么区别？', detail: '会使用那一把 Key 的分组和模型权限。通过名称、分组和掩码预览核对，不只看相似名称；ChatGPT 官方账号来源不选星芒 Key。' }],
        action: '返回首页配置密钥',
        page: 'home',
      },
      {
        title: '需要换模型时，再检测和选择',
        where: 'Codex 配置窗口 → 检测模型 → 默认模型',
        detail: '模型就是回答问题的 AI。第一次自动配置可用默认模型，不必马上更换。',
        bullets: ['使用当前、已有或手填密钥时，点「检测模型」。', '在「默认模型」里选择想用的一个，通常保持「全部模型」筛选。'],
        expected: '默认模型已选中，没有检测失败提示。',
        extra: [{ title: '自动准备时，检测模型按钮不能点？', detail: '先保存，工具箱才会准备专属密钥。需要换模型时，再打开配置检测；第一次保存使用该分组默认模型。' }, { title: '官方账号或模型兼容问题', detail: 'ChatGPT 账号在 Codex 自己的界面里选模型。星芒模型需要支持 Codex 使用的接口，列表中出现不保证每次调用成功。' }],
        action: '返回首页选择模型',
        page: 'home',
      },
      {
        title: '保存后，让 Codex 重新读取配置',
        where: 'Codex 配置窗口 → 保存配置',
        detail: '日常保存选择保留其他设置的那一项。',
        bullets: ['点「保存配置」，核对账号、密钥、分组和模型。', '选「仅更新账号来源、密钥和模型」。', 'Codex 已运行时先保存任务，再从首页「打开」中选「重启 Codex」。'],
        expected: '窗口关闭并提示保存成功，重开 Codex 后使用新配置。',
        extra: [{ title: '「重置为初始状态」什么时候用？', detail: '仅在要重建配置时使用。它先备份，再重置该来源的权限、MCP 和推理参数等自定义设置；历史会话保留。' }],
        action: '回首页保存并打开 Codex',
        page: 'home',
      },
    ],
  },
  {
    id: 'switch-account',
    title: '官方账号和当前账号怎么切换？',
    lead: '以前用过 Claude 或 ChatGPT 官方账号的，一键就能切到当前账号，也能一键切回去。不用自己备份，也不用重新安装。',
    category: 'start',
    minutes: 2,
    keywords: ['切换', '官方账号', '当前账号', 'ChatGPT', 'Claude 账号', '中转', '切回', '登录', '401', 'Please run /login', '报错', '备份'],
    steps: [
      {
        title: '看工具行写的是哪个账号',
        where: '工具箱首页 → 工具行',
        detail: '每个工具行下面有一句话说明现在用的是谁的账号。',
        bullets: ['「正在用官方账号」：用的是你自己的 Claude 或 ChatGPT 订阅。', '「正在用当前账号」：用的是左下角这个账号的额度。'],
        expected: '知道这个工具现在用的是哪个账号。',
        illustration: 'home',
        action: '回首页看工具行',
        page: 'home',
      },
      {
        title: '在「…」里点切换',
        where: '工具箱首页 → 工具行右侧 … → 切到当前账号 / 切回官方账号',
        detail: '点一下就行，工具箱会替你做完：先备份原来的配置，再把会冲突的旧登录挪到一边，写好新配置，最后自动测一次能不能连上。',
        bullets: ['切到当前账号前要先登录左下角的账号。', '测下来连不上时会自动恢复原样，并说一句原因。'],
        expected: '右下角提示「已切到当前账号」或「已切回官方账号」。',
        extra: [{ title: '原来的配置去哪了？', detail: '切换前的配置自动放进「备份」页，想退回去可以在那里恢复。挪开的官方登录只是换了个位置，切回官方时会放回原处。' }, { title: 'Gemini 为什么没有「切回官方账号」？', detail: '个人 Google 账号已经不能用于 Gemini CLI。企业版用户可以在「…」→「配置」里选择官方账号。' }],
        action: '去首页切换',
        page: 'home',
      },
      {
        title: '把已经开着的工具关掉重开',
        where: 'Claude Code / Codex 窗口',
        detail: '已经打开的工具还记着旧账号，要关掉重开才会换过来。Codex 桌面端也一样。',
        bullets: ['先保存手头的工作，再关掉工具窗口。', '回到首页点「打开」。'],
        expected: '重开后能正常回复。',
        action: '回首页打开工具',
        page: 'home',
      },
      {
        title: '切回官方后提示要登录',
        where: 'Claude Code / Codex 窗口',
        detail: '这台电脑没登录过官方账号时，切回后要在工具里登录一次。',
        bullets: ['Claude Code：打开后输入 /login，按提示登录 Claude 账号。', 'Codex：打开后按提示用 ChatGPT 账号登录。', '提示「refresh token has expired」时，在 Codex 里退出后重新登录。'],
        expected: '工具里显示已登录，能正常回复。',
        extra: [{ title: '切完还是报 401 或「Please run /login」？', detail: '到「检查」页重新检查一次，看「环境变量覆盖」有没有提示：系统里设过的 ANTHROPIC_API_KEY 这类变量会盖过工具箱写的配置。' }],
        action: '去检查页',
        page: 'health',
      },
    ],
  },
  {
    id: 'launch',
    title: '打开 Codex 后，怎么开始用？',
    lead: '先发一个问题，再试着处理文件。一件事一次说清楚就好。',
    category: 'start',
    minutes: 4,
    keywords: ['Codex', '桌面端', '打开', '启动', '聊天', '文件夹', '项目', '第一次对话', 'New chat', '记录', '权限'],
    steps: [
      {
        title: '打开 Codex 窗口',
        where: '工具箱首页 → Codex 桌面端 → 打开',
        detail: '看到「已配好」后点「打开」，接下来在 Codex 窗口里操作。',
        bullets: ['点击 Codex 桌面端这一行的「打开」。', '提示已经运行时，点「打开窗口」。'],
        expected: '屏幕上出现 Codex 的独立窗口。',
        illustration: 'desktop-home',
        action: '去首页打开 Codex',
        page: 'home',
      },
      {
        title: '先发一句简单的话',
        where: 'Codex 窗口 → 新对话 → 输入框',
        detail: '只问问题不用选文件夹。先试一条消息，确认能收到回复。',
        bullets: ['开始一段新对话，英文界面可能显示 New chat。', '输入下面这句话并发送。'],
        example: '请帮我列一份今天的工作计划，先问我有哪些事情要做。',
        expected: 'Codex 返回文字，你可以继续回答它。',
        illustration: 'desktop-message',
        action: '返回首页打开桌面端',
        page: 'home',
      },
      {
        title: '要处理文件，再添加本地项目',
        where: 'Codex 窗口 → 本地项目 / 打开文件夹',
        detail: '本地项目就是这次要处理的电脑文件夹。第一次先用一个练习文件夹。',
        bullets: ['在 Codex 里添加本地项目或打开文件夹。', '选这次任务的文件夹，不选整个桌面或磁盘。', '说明要做什么，先让 AI 列计划再修改文件。'],
        expected: 'Codex 使用的是你选中的项目文件夹。',
        extra: [{ title: '在哪里选文件夹、怎么给权限？', detail: '在 Codex 自己的窗口选择项目，工具箱配置中的工作文件夹不能代替它。文件操作仍受 Codex 权限限制，弹出确认时看清范围再允许。' }],
        illustration: 'desktop-project',
        action: '返回首页打开桌面端',
        page: 'home',
      },
      {
        title: '下次接着原来的对话聊',
        where: 'Codex 窗口 → 已有对话',
        detail: '同一件事继续原对话，换一个目标就开新对话。',
        bullets: ['找到刚才的对话，继续补充要求。', '有文件修改时先查看结果，再交代下一步。'],
        expected: '能回到原来的项目和对话继续工作。',
        extra: [{ title: '工具箱的「聊天」是同一个窗口吗？', detail: '不是。「聊天」是工具箱自带的问答功能；Codex 桌面端的对话要回到 Codex 窗口继续。工具箱「记录」可辅助查看支持的工具会话。' }],
        action: '回首页继续使用 Codex',
        page: 'home',
      },
    ],
  },
  {
    id: 'account',
    title: '账号、充值与额度',
    lead: '查看自己的账号、充值到账情况和使用费用。',
    category: 'everyday',
    minutes: 4,
    keywords: ['个人中心', '登录', '注册', 'QQ邮箱', '密码', '余额', '充值', '订阅', '兑换码', '订单', 'Key', '费用'],
    steps: [
      {
        title: '在个人中心确认当前账号',
        where: '工具箱左下角 → 个人中心 → 我的账号',
        detail: '先确认当前登录的是你自己的账号。',
        bullets: ['点左下角账号，未登录就先登录。', '查看资料与余额，读取失败时点「刷新余额」。'],
        expected: '账号名字正确，余额已读取。',
        illustration: 'account',
        action: '打开个人中心',
        page: 'account',
      },
      {
        title: '分清账号密码、密钥和模型分组',
        where: '个人中心 → 密钥',
        detail: '密码用来登录；Key 是调用 AI 的通行证；分组决定能用的模型和收费规则。普通使用通常不用手动复制 Key。',
        bullets: ['在「密钥」里查看已有 Key。', '工具配置里核对所用 Key 的名称、分组和掩码预览。'],
        expected: '知道当前工具用了哪个分组。',
        extra: [{ title: '官方账号也扣星芒余额吗？', detail: '切换到官方账号来源后，登录和额度按官方服务的规则使用。' }],
        action: '查看账号与密钥',
        page: 'account',
      },
      {
        title: '充值或兑换，并确认到账',
        where: '个人中心 → 充值与订阅',
        detail: '按页面提供的金额和支付方式充值。手里有充值码的，也可以直接兑换。',
        bullets: ['选金额和支付方式，点「充值」，核对报价后支付。', '使用充值码时，填入「兑换充值码」，点「兑换」并确认账号。', '付款后等成功提示，核对余额或权益。'],
        expected: '显示充值或兑换成功，余额或权益已更新。',
        extra: [{ title: '付了钱但没有到账提示？', detail: '先「刷新余额与订阅」，再到「我的订单」点「查询订单」。关闭支付窗口不会取消订单，不要因窗口没关就重复付款；可用支付、订阅入口以页面实际显示为准。' }],
        action: '打开个人中心办理充值',
        page: 'account',
      },
      {
        title: '查看每次调用消耗了多少',
        where: '个人中心 → 调用明细 / 用量看板',
        detail: '「调用明细」看每次用了多少，「用量看板」看整体趋势。',
        bullets: ['按刚才使用的时间找到调用。', '打开详情，核对模型、分组和费用。'],
        expected: '能找到对应请求的用量和计费信息。',
        extra: [{ title: '余额没变，或者想重试？', detail: '可以手动刷新余额；显示更新失败时可能仍是旧金额。聊天、生图和重试都是实际请求，费用以服务端记录为准。' }],
        action: '查看用量与调用明细',
        page: 'account',
      },
    ],
  },
  {
    id: 'chat',
    title: '直接聊天与生成图片',
    lead: '在工具箱里直接问问题或生成图片，不用另装工具。',
    category: 'everyday',
    minutes: 3,
    keywords: ['聊天', '问答', '文案', '图片', '生图', '发送', '停止', '分组', '模型', '新对话', '历史'],
    steps: [
      {
        title: '打开聊天，选好分组和模型',
        where: '左侧聊天 → 新对话 → 输入框上方',
        detail: '先选回答问题的模型。分组决定可用模型与计费规则。',
        bullets: ['点「新对话」，保持「文本对话」。', '选好「分组」和「模型」，列表失败时点刷新。'],
        expected: '分组和模型已选中，输入文字后可以发送。',
        illustration: 'chat',
        action: '打开聊天',
        page: 'chat',
      },
      {
        title: '先发送一个清楚的小问题',
        where: '聊天 → 消息输入框',
        detail: '说清想做什么、给谁看、希望输出什么。',
        bullets: ['输入问题，点向上的发送箭头。', '需要中止时点「停止生成」。'],
        example: '请写一封客户进度说明：本周完成首页，下周做支付。语气专业，200 字以内。',
        expected: '消息区出现 AI 回复。',
        action: '去聊天发送第一个问题',
        page: 'chat',
      },
      {
        title: '生成图片后复制或另存',
        where: '聊天 → 生成图片',
        detail: '描述想要的画面，生成后可保存到电脑。',
        bullets: ['切到「生成图片」，选可用分组、模型和尺寸。', '输入描述后点「生成图片」。', '完成后点预览，选「复制图片」或「另存图片」。'],
        example: '一只橘猫坐在窗边看雨，温暖的室内灯光，水彩插画，方形构图，不要文字。',
        expected: '看到图片预览，另存后能找到图片文件。',
        extra: [{ title: '没有模型或生成很慢？', detail: '分组没有图片模型时换用可用分组。停止等待不一定取消服务端生成，先确认状态再重试。' }],
        action: '打开聊天生成图片',
        page: 'chat',
      },
      {
        title: '找回历史，谨慎重试',
        where: '聊天 → 左侧对话列表',
        detail: '同一件事继续原对话，换主题就开新对话。',
        bullets: ['点左侧已有对话继续。', '回复下方可复制，需重试时选「重新生成」。'],
        expected: '回到原对话能看到已有消息。',
        extra: [{ title: '重新生成或编辑重发会怎样？', detail: '会提交新的请求，并替换对应消息之后的回复，可能产生新费用；费用在个人中心「调用明细」查看。' }],
        action: '打开聊天历史',
        page: 'chat',
      },
    ],
  },
  {
    id: 'sessions',
    title: '记录',
    lead: '找回这台电脑上的工具对话，继续上次的任务，也可以查看、导出和整理。',
    category: 'everyday',
    minutes: 3,
    keywords: ['记录', '会话', '历史', '搜索', '接着聊', '续接', '归档', '恢复', '导出', 'Markdown', '保留期', '一年', '本机'],
    steps: [
      {
        title: '找到要看的那次对话',
        where: '左侧记录 → 工具筛选 / 搜索框',
        detail: '这里显示 Claude Code、Codex CLI、Gemini CLI、Grok CLI 的本机对话，记录只存在这台电脑上。',
        bullets: ['顶部按工具筛选，或搜索标题、文件夹、模型。', '核对这一行的工作文件夹、消息条数和时间。'],
        expected: '找到正确工具和项目的记录。',
        action: '打开记录查找对话',
        page: 'sessions',
      },
      {
        title: '继续这个文件夹最近的对话',
        where: '记录 → 对应行 → 接着聊',
        detail: '「接着聊」会在记录的文件夹打开对应工具，接上这个文件夹里最近的一次对话。',
        bullets: ['核对工作文件夹，点击「接着聊」。', '首页「最近」卡里也可以使用这个按钮。'],
        expected: '对应工具打开，并接上该目录最近的对话。',
        extra: [{ title: '为什么这一条没有「接着聊」？', detail: '命令行工具只能按文件夹找回最近一条。同一工具、同一文件夹里更早的记录、已归档的记录、没记下文件夹的记录，都不显示这个按钮。' }],
        action: '打开记录继续任务',
        page: 'sessions',
      },
      {
        title: '查看、导出或归档记录',
        where: '记录 → 查看记录 → 右侧详情',
        detail: '先查看内容，需要保存一份就导出，不常用的记录可以归档。',
        bullets: ['点「查看记录」，在右侧阅读对话。', '点「导出 Markdown」，按提示找到导出文件。', '不想放在当前列表时点「归档记录」，需要时再「恢复记录」。'],
        expected: '能阅读或导出对话，归档状态也能恢复。',
        extra: [{ title: '归档会影响继续聊天吗？', detail: '归档会把记录移出工具自己的目录，所以已归档记录不能「接着聊」。需要继续时先恢复，再核对它是否为该目录最近一条。' }],
        action: '打开记录查看详情',
        page: 'sessions',
      },
      {
        title: '看懂不可续接和保留期',
        where: '记录 → 状态提示',
        detail: '显示「文件夹已不存在」时，原目录已删除或搬走，不能继续，但仍可查看和导出。',
        bullets: ['按钮按不动时，先看旁边的文件夹状态。', '重要内容及时「导出 Markdown」，不要只依赖工具保留记录。'],
        expected: '知道不能续接的原因，也能保留需要的内容。',
        extra: [{ title: '记录会保留多久？', detail: '记录由各工具管理。由工具箱写配置的 Claude Code 与 Gemini CLI，默认保留期已从一个月延长到一年；你自己设置过的保留期仍按原设置。' }],
        action: '打开记录核对状态',
        page: 'sessions',
      },
    ],
  },
  {
    id: 'canvas',
    title: '画布：从项目到生成结果',
    lead: '节点是一张处理卡片。先跑通一张，再连接成连续的工作步骤。',
    category: 'everyday',
    minutes: 5,
    keywords: ['画布', '节点', '工作流', '项目', '生图', '素材', '模板', '生成', '保存'],
    steps: [
      {
        title: '打开画布，创建一个练习项目',
        where: '左侧画布 → 项目中心',
        detail: '先给这次创作建一个项目，已有项目可直接打开。',
        bullets: ['点「新建项目」，输入名称。', '点「选择文件夹并创建」，选择专用目录。'],
        expected: '进入带项目名称的画布。',
        illustration: 'canvas',
        action: '打开画布',
        page: 'canvas',
      },
      {
        title: '先配置要用的生成类型',
        where: '画布顶部 → 生成配置',
        detail: '为这次要做的文字或图片任务选择模型。',
        bullets: ['打开「生成配置」，选择对应类型。', '选可用分组和模型，不用的类型先不配。'],
        expected: '本次要用的类型有可用模型。',
        action: '去画布确认生成配置',
        page: 'canvas',
      },
      {
        title: '添加节点，填写内容并运行',
        where: '画布创作库 → 节点 → 运行此节点',
        detail: '先添加一张节点卡片，填写想让 AI 做的事。',
        bullets: ['从创作库或「快速创建」添加节点，填提示词和必需输入。', '点「运行此节点」，核对运行前检查里的模型和分组。', '点「确认运行」，等待完成。'],
        expected: '节点显示已完成，出现生成结果。',
        extra: [{ title: '缺少输入或想用现成流程？', detail: '缺少输入先补内容或连接上游，不要反复运行。现成流程可从创作库模板，或「更多操作」→「打开行业模板库」添加。' }],
        action: '打开画布尝试一个节点',
        page: 'canvas',
      },
      {
        title: '确认保存，查看结果与失败原因',
        where: '画布底部 → 保存状态；顶部 → 运行历史',
        detail: '离开前看一眼保存状态，失败时查看运行记录。',
        bullets: ['确认底部显示「已自动保存」。', '点「运行历史」查看结果或错误。', '要转移项目，在「更多操作」里选「导出项目包」。'],
        expected: '重新打开项目仍能看到画布与素材。',
        extra: [{ title: '还有任务时可以关闭吗？', detail: '按关闭窗口的提示处理。停止本地等待后，服务端仍可能继续生成和计费。' }],
        action: '打开画布查看项目',
        page: 'canvas',
      },
    ],
  },
  {
    id: 'acceleration',
    title: '游戏加速',
    lead: '选线路，点开始；用完点停止，剩余时长下次继续。',
    category: 'everyday',
    minutes: 3,
    keywords: ['加速', '网络', '线路', '智能分配', 'Ping', '延迟', 'TUN', '代理', 'VPN', '免费时长', '托盘', '自动连接', '下载', '到期', '提醒', '通知'],
    steps: [
      {
        title: '登录后查看可用时长',
        where: '左侧游戏加速 → 剩余免费时长',
        detail: `每个账号在本机累计 ${accelerationTrialSeconds / 60} 分钟，连接成功才计时，不每日重置。`,
        bullets: ['未登录先点「登录领取免费体验」。', '查看剩余时长、页面下方「本次连接」和「累计使用」。'],
        expected: '读到剩余时长与线路状态。',
        illustration: 'acceleration',
        extra: [{ title: '时长用完和到期提醒', detail: `时长用完会自动停止，按钮变为「免费体验已用完」，可通过「帮助与客服」咨询。启用「设置」→「通知」里的桌面通知和「加速时长提醒」且系统允许通知时，剩余 ${accelerationExpiryWarningSeconds / 60} 分钟及用完断开会各提醒一次。` }],
        action: '打开游戏加速',
        page: 'acceleration',
      },
      {
        title: '连接前选择线路或智能分配',
        where: '游戏加速 → 选择加速线路',
        detail: '不确定选哪条就用「智能分配」，连接时自动测速选可用线路。Ping 用来测线路的响应快慢。',
        bullets: ['展开线路列表，选择「智能分配」或具体线路。', '手选线路可点旁边「Ping」，数字越小通常越快。'],
        expected: '当前线路显示你的选择。',
        action: '去选择加速线路',
        page: 'acceleration',
      },
      {
        title: '开始加速，等状态确认',
        where: '游戏加速 → 开始加速',
        detail: '点「开始加速」，等连接成功再使用；加速通过这台电脑的系统代理生效。',
        bullets: ['TUN 显示「暂未开放」时不用操作。', '点「开始加速」，等待状态变为「加速已开启」。'],
        expected: '显示实际线路，剩余时长开始计时。',
        extra: [
          { title: '提示其他代理或 VPN 冲突？', detail: '先关闭其他代理或 VPN 后重试；也可以按页面选择「仍然连接」。系统代理能否影响某个应用，取决于那个应用是否采用系统代理。' },
          { title: '为什么有时会自动连接？', detail: '安装、更新 CLI 或下载 Node.js 时，工具箱可准备下载专用临时线路：不改电脑网络设置，不计入免费时长，下载后关闭，加速页不显示已连接。打开 Codex 桌面端时，若有可用额度且还没连接，会先尝试正常加速；成功后会计时，不会自动断开，用完请手动停止。已有线路不改动，自动连接失败也会照常打开 Codex。' },
          { title: '「加速服务暂不可用」或连不上？', detail: '先按具体提示处理：完全退出工具箱（含托盘）后重开、检查磁盘空间，或请管理员处理系统限制。「查看日志」会进入反馈页运行日志，「重新检查」会重新读取状态；线路准备中可点「刷新线路状态」。' },
        ],
        action: '打开游戏加速连接',
        page: 'acceleration',
      },
      {
        title: '用完明确点击停止加速',
        where: '游戏加速 → 停止加速',
        detail: '不用时明确点停止，缩到托盘或切换页面不等于停止。',
        bullets: ['点「停止加速」，等连接结束。', '要换线路或 TUN 模式，也先停止。'],
        expected: '显示未计时，剩余时长保留。',
        extra: [{ title: '窗口缩到托盘后怎么操作？', detail: '右键工具箱托盘图标，查看加速状态和剩余时长，使用「连接加速 / 断开加速」。不可操作时按钮变灰，状态行说明原因。' }],
        action: '查看并停止加速',
        page: 'acceleration',
      },
    ],
  },
  {
    id: 'cli',
    title: '进阶：安装与使用命令行工具',
    lead: 'CLI 是在终端里使用 AI 的方式。只用 Codex 桌面端可以跳过这一章。',
    category: 'advanced',
    minutes: 5,
    keywords: ['CLI', '命令行', '终端', 'Claude Code', 'Codex CLI', 'Gemini', 'Grok', 'Node.js', 'npm', 'Python', 'Git', '安装', '首次命令', '接着聊'],
    steps: [
      {
        title: '选一个 CLI，准备它需要的环境',
        where: '工具箱首页 → 运行环境',
        detail: '命令行工具需要 Node.js 与 npm，Gemini CLI 还要 Python。',
        bullets: ['Windows 点运行环境卡里的准备按钮。', 'Mac 按「Mac 上装 Node.js 和 Python」操作。'],
        expected: '所需运行环境显示版本号。',
        extra: [{ title: 'Claude Code 为什么提示 Git？', detail: 'Windows 上部分技能、插件命令和首次添加官方插件市场需要 Git，按「检查」页的指引安装。' }],
        illustration: 'install',
        action: '去首页准备 CLI 环境',
        page: 'home',
      },
      {
        title: '安装 CLI 并确认账号连接',
        where: '工具箱首页 → 目标 CLI → 安装',
        detail: '选一个要用的 CLI，装好后确认账号连接。',
        bullets: ['点「安装」，等进度和账号同步结束。', '仍未配好时点「连接账号」，选来源、密钥和模型后保存。'],
        expected: '工具行出现版本和「已配好」。',
        extra: [{ title: '已有安装或正在使用 Codex 桌面端？', detail: '已有工具先检测；官方安装器或其他来源管理的工具按原方式更新。Codex CLI 与桌面端共用配置，修改会影响两者；保存通常选「仅更新账号来源、密钥和模型」。' }],
        action: '查看 CLI 安装状态',
        page: 'maintenance',
      },
      {
        title: '点击打开，选择这次的工作文件夹',
        where: '工具箱首页 → CLI 打开 → 选择文件夹',
        detail: '文件夹决定 AI 在哪里处理项目。第一次先用练习目录。',
        bullets: ['点「打开」，选择项目文件夹。', '已有最近目录时可用旁边下拉「换一个目录」。', '等终端里工具启动好，再输入中文任务。'],
        expected: 'CLI 已在正确目录启动，不用再敲一次启动命令。',
        illustration: 'launch',
        action: '回首页打开 CLI',
        page: 'home',
      },
      {
        title: '发出第一个任务，再从记录继续',
        where: 'CLI 终端 → 输入任务；工具箱 → 记录',
        detail: '在启动好的 CLI 里输入任务，收到回复后再继续。',
        bullets: ['发送下面的例句。', '下次从「记录」或首页「最近」找项目，支持时可点「接着聊」。'],
        example: firstRunHints.claude.prompt,
        expected: '收到项目相关的回复。',
        extra: [{ title: '自己打开终端怎么启动？', detail: '可复制首页「试试第一条命令」里的启动命令。只有支持续接的最近会话显示「接着聊」。' }],
        action: '打开记录',
        page: 'sessions',
      },
    ],
  },
  {
    id: 'mcp',
    title: '外接工具',
    lead: '外接工具（MCP）让 AI 使用浏览器等服务。先选工具，再添加连接。',
    category: 'advanced',
    minutes: 4,
    keywords: ['MCP', '浏览器', '外接工具', '连接', '本地程序', '网络服务', '授权', 'JSON'],
    steps: [
      {
        title: '先看它能做什么',
        where: '左侧外接工具 → 顶部工具选择',
        detail: '连接浏览器就能使用相应的网页操作；文件服务可提供获准的文件。各 AI 工具的连接分别管理。',
        bullets: ['顶部选择你正在使用的 AI 工具。', '先看连接说明和权限。'],
        expected: '列表对应选中的工具，空列表表示还没添加。',
        extra: [{ title: '读项目文件一定需要 MCP 吗？', detail: '不需要。CLI 本身可以访问获准的项目文件；文件服务连接用于该服务额外提供的文件。' }],
        illustration: 'extensions',
        action: '打开外接工具',
        page: 'mcp',
      },
      {
        title: '添加一条连接',
        where: '外接工具 → 星芒精选 / 添加连接',
        detail: '第一次优先从「星芒精选」安装；有连接说明时再手动添加。',
        bullets: ['精选卡点「安装」，看清权限后确认。', '手动添加点「添加连接」，按提供方说明填名称、地址或本地程序。'],
        expected: '连接列表新增一行。',
        extra: [{ title: '参数和环境变量怎么填？', detail: '参数用 JSON 字符串数组，例如 ["--help"]；环境变量用文字对象，例如 {"MODE":"read-only"}。这里只是格式示例，实际值按服务说明填写；本地程序必须先装好。' }],
        action: '去添加连接',
        page: 'mcp',
      },
      {
        title: '确认真的接上了',
        where: '外接工具 → 连接行 → 更多操作',
        detail: '需要登录的连接，先授权再使用。',
        bullets: ['显示「尚未登录」时点「更多操作」→「登录授权」。', '到对应 AI 工具里试一个必须使用该连接的任务。'],
        example: '请用我刚添加的浏览器工具打开指定页面，并告诉我页面标题。',
        expected: '授权正常，AI 能使用这条连接。',
        action: '查看连接状态',
        page: 'mcp',
      },
      {
        title: '加不上怎么办',
        where: '外接工具 → 错误提示',
        detail: '先按页面指出的字段修正，不用重新安装所有工具。',
        bullets: ['地址空就补地址；格式错误就核对 JSON。', '「当前工具未提供管理能力」时，到「安装卸载」核对安装。'],
        expected: '修正后可以保存或完成授权。',
        action: '打开安装卸载',
        page: 'maintenance',
      },
    ],
  },
  {
    id: 'skills',
    title: '技能',
    lead: '技能是一份做事说明，让 AI 按固定方法完成某类任务。',
    category: 'advanced',
    minutes: 4,
    keywords: ['技能', 'Skill', '导入', '全局', '当前项目', '启用', '来源', '文件夹'],
    steps: [
      {
        title: '先看技能是什么',
        where: '左侧技能 → 顶部工具选择',
        detail: '先选技能要给哪个 AI 工具使用。',
        bullets: ['顶部选择工具，查看已有技能。', '带「系统内置」的只能查看，其余可按工具能力管理。'],
        expected: '列表对应选中的工具。',
        illustration: 'skills',
        action: '打开技能',
        page: 'skills',
      },
      {
        title: '添加自己的技能',
        where: '技能 → 导入技能',
        detail: 'Codex CLI 填本机技能文件夹，Gemini CLI 填技能来源。',
        bullets: ['点「导入技能」，按提示填来源。', '选「我的（全局）」用于多个项目，或「当前项目」只用于此项目。'],
        expected: '列表出现新技能及添加范围。',
        extra: [{ title: 'Claude Code、Grok CLI 没有导入按钮？', detail: '它们不提供这里的导入入口。按工具自己的方式放好技能，再回本页重新加载；选择当前项目时先核对工作文件夹。' }],
        action: '去导入技能',
        page: 'skills',
      },
      {
        title: '确认生效',
        where: '技能 → 新技能状态',
        detail: '看到技能后，再用一个相关任务验证。',
        bullets: ['确认显示「已启用」。', '到对应工具里交代一个技能负责的任务。'],
        expected: 'AI 按技能的方法处理任务。',
        extra: [{ title: '为什么不能开关或没触发？', detail: 'Gemini CLI 可在这里开关，其他工具到自身界面操作。技能只在相关任务中触发，不是所有问题都会使用。' }],
        action: '查看技能状态',
        page: 'skills',
      },
      {
        title: '导入不了怎么办',
        where: '技能 → 错误提示',
        detail: '先看是来源没填，还是当前工具不支持导入。',
        bullets: ['来源为空就补填；不支持导入就用工具自身的方式。', '「部分信息需要确认」时，处理具体原因后重新加载。'],
        expected: '列表能正常读取并找到技能。',
        action: '打开技能检查提示',
        page: 'skills',
      },
    ],
  },
  {
    id: 'plugins',
    title: '插件',
    lead: '插件是一整包扩展能力，可能包含命令、技能和服务连接。',
    category: 'advanced',
    minutes: 4,
    keywords: ['插件', 'plugin', '市场', '官方市场', '安装', '来源', '仓库', '更新'],
    steps: [
      {
        title: '先分清它和外接工具',
        where: '左侧插件 → 顶部工具选择',
        detail: '外接工具连接单个服务，插件可带来一整套能力。',
        bullets: ['顶部选你要用的 AI 工具。', '查看「已安装」，安装新插件前先读用途和来源。'],
        expected: '插件列表对应正确的工具。',
        illustration: 'plugins',
        action: '打开插件',
        page: 'plugins',
      },
      {
        title: '添加插件',
        where: '插件 → 添加插件 / 市场',
        detail: 'Claude Code 的市场首次点「添加官方市场」；Codex CLI 的市场点「添加市场」。',
        bullets: ['有现成来源时点「添加插件」，填名称或仓库地址。', '选择添加范围，再确认安装。'],
        expected: '「已安装」里出现对应插件。',
        extra: [{ title: '市场入口和来源有什么要求？', detail: 'Claude Code 添加官方市场后从清单安装；Codex CLI 填市场地址，市场行可更新或移除。Gemini CLI 和 Grok CLI 只有已安装列表；来源用作者提供的名称或地址，不填普通网页。' }],
        action: '去添加插件',
        page: 'plugins',
      },
      {
        title: '确认装上了',
        where: '插件 → 已安装 → 更多操作',
        detail: '先核对安装状态，再到 AI 工具里试用。',
        bullets: ['确认插件行显示「已启用」。', '从「更多操作」→「查看详情」核对来源与版本。'],
        expected: '名称和状态正确，工具内能使用插件。',
        extra: [{ title: '哪些插件能在这里更新、开关？', detail: 'Claude Code、Gemini CLI、Grok CLI 支持开关和更新；Codex CLI 支持添加和移除。' }],
        action: '查看已安装插件',
        page: 'plugins',
      },
      {
        title: '装完没反应怎么办',
        where: '插件状态 → 对应 AI 工具',
        detail: '工具运行中安装的插件，可能需要重新打开工具才生效。',
        bullets: ['先保存当前工作，再重新打开工具。', '仍失败时，记录插件名称、工具版本和报错。'],
        expected: '重开后能使用插件，或已取得明确错误。',
        extra: [{ title: '没有市场、缺 Git 或来源不确定？', detail: '「当前工具未提供市场管理接口」表示没有市场，现有插件仍在已安装列表。Claude Code 首次加官方市场需要 Git，按检查页指引安装。来源不可信先别装，插件可能拥有与工具相同的操作能力。' }],
        action: '打开插件检查状态',
        page: 'plugins',
      },
    ],
  },
  {
    id: 'safety',
    title: '备份、更新与数据',
    lead: '改配置前留备份，更新前保存工作，项目文件另外保管。',
    category: 'advanced',
    minutes: 3,
    keywords: ['备份', '恢复', '更新', '重置', '数据', '隐私', '卸载', '版本'],
    steps: [
      {
        title: '先备份工具配置',
        where: '侧栏更多 → 备份',
        detail: '配置备份保存工具设置，不包含整个项目或所有聊天记录。',
        bullets: ['选工具，点「创建备份」或「创建第一份备份」。', '恢复时核对工具、时间和文件范围，再确认。'],
        expected: '列表出现对应工具的新备份。',
        illustration: 'backup',
        action: '打开备份',
        page: 'backups',
      },
      {
        title: '区分两种更新入口',
        where: '更多 → 更新；首页 → 工具行更新',
        detail: '「更多」里的更新管工具箱，首页工具行的更新管那个 AI 工具。',
        bullets: ['进入对应的更新入口，按提示下载。', '先保存任务，再确认重启安装。'],
        expected: '重新打开并检测后看到新版本。',
        extra: [{ title: '更新失败怎么办？', detail: '按页面给出的失败步骤处理后重试，不要把工具箱版本和 Codex 等工具的版本混在一起。' }],
        action: '打开工具箱更新',
        page: 'updates',
      },
      {
        title: '知道哪些数据需要另外保存',
        where: '设置 → 隐私与数据；自己的项目文件夹',
        detail: '换电脑或清理文件前，单独保留项目和重要资料。',
        bullets: ['找到自己的项目目录和画布项目目录。', '分别确认配置、对话和登录信息如何保留。'],
        expected: '知道哪些文件要另外备份。',
        action: '查看隐私与数据设置',
        page: 'settings',
      },
    ],
  },
  {
    id: macRuntimeTutorialTopic,
    title: 'Mac 上装 Node.js 和 Python',
    lead: '只用 Codex 桌面端可以跳过。要用 CLI 时，下面两种安装方式选一种。',
    category: 'advanced',
    minutes: 4,
    keywords: ['Mac', 'macOS', '苹果', 'CLI', '命令行', 'Node.js', 'npm', 'Python', 'Homebrew', 'brew', 'pkg', '环境'],
    steps: [
      {
        title: '先看首页缺哪一个',
        where: '工具箱首页 → 运行环境',
        detail: 'CLI 需要 Node.js 与 npm，Gemini CLI 还要 Python。',
        bullets: ['查看哪项没有版本号。', '只安装要用的环境，已装好的不用重复装。'],
        expected: '知道这次缺少 Node.js 还是 Python。',
        illustration: 'install',
        action: '返回首页看环境',
        page: 'home',
      },
      {
        title: '装过 Homebrew 的走这条',
        where: 'Mac 终端 → 安装命令',
        detail: `Node.js 用 ${runtimeHomebrewCommand('node')}，Python 用 ${runtimeHomebrewCommand('python')}。星芒不会替你跑这条命令。`,
        bullets: ['打开 Mac 的「终端」。', '只粘贴缺少的那项命令，回车并等它完成。'],
        example: `${runtimeHomebrewCommand('node')}\n${runtimeHomebrewCommand('python')}`,
        expected: '需要的安装命令完成，没有失败提示。',
        extra: [{ title: '不知道 Homebrew 是什么？', detail: '它是 Mac 的命令行安装工具。没用过可以直接选下一步的官网安装包方式；工具箱不会替你执行命令，也不会在软件内要求管理员密码。' }],
        action: '返回首页查看安装提示',
        page: 'home',
      },
      {
        title: '没装过 Homebrew 的走这条',
        where: '工具箱首页 → 运行环境 → 官网下载',
        detail: `点「${runtimeButtonLabel('node', 'external')}」或 Python 的官网下载按钮，选择 macOS 的 .pkg 安装包。`,
        bullets: ['Node.js 选 LTS 版本，下载对应安装包。', '双击安装包，按安装器提示完成。'],
        expected: '安装器提示完成，Node.js 安装包也会提供 npm。',
        extra: [{ title: '点击官网按钮后没有开始安装？', detail: '按钮只打开官网，下载和运行安装包需要你自己完成。' }],
        action: '返回首页打开官网',
        page: 'home',
      },
      {
        title: '装完回来重新检测',
        where: '工具箱首页 → 重新检测',
        detail: '装完回工具箱，让它再找一次新安装的环境。',
        bullets: ['点「重新检测」，查看对应环境的版本号。', '还没识别就重开终端和工具箱，再检测。'],
        expected: '环境显示版本号，可以继续安装 CLI。',
        extra: [{ title: '重开后仍找不到？', detail: '进入「检查」查看具体环境结果，把错误和已安装版本提供给客服。' }],
        action: '打开检查',
        page: 'health',
      },
    ],
  },
  {
    id: macDesktopTutorialTopic,
    title: 'Mac 上装桌面端',
    lead: 'Mac 用户从官网下载需要的桌面端，装好后回工具箱检测、配置。不用把四个都装一遍。',
    category: 'advanced',
    minutes: 4,
    keywords: ['Mac', 'macOS', '苹果', 'Codex', 'ChatGPT', 'WorkBuddy', 'Claude Desktop', 'OpenCode', '桌面端', '安装指南', 'dmg', 'pkg', '应用程序', 'arm64', '检测不到'],
    steps: [
      {
        title: '先选你要用的桌面端',
        where: '工具箱首页 → 对应桌面端 → 安装指南',
        detail: 'Mac 上的「安装指南」会打开本教程，下载安装要你自己完成。',
        bullets: ['选择 Codex 桌面端、WorkBuddy、Claude Desktop 或 OpenCode。', '已显示版本号的不用重装，直接看第 4 步。'],
        expected: '知道这次要安装哪个应用。',
        extra: [{ title: '为什么这里不能一键安装？', detail: 'Windows 支持工具箱代装这四个桌面端，macOS 目前采用官网下载、手动安装。它们在 Mac 上也能使用，安装桌面端不会改动已经装好的命令行工具。' }],
        action: '回首页选择桌面端',
        page: 'home',
      },
      {
        title: '去对应官网下载 Mac 版',
        where: '浏览器 → 对应应用的官方下载页',
        detail: '展开下方应用名称，找到对应官网来源。',
        bullets: ['下载 macOS 的桌面端安装包，别选成命令行版本。', 'Apple 芯片的 Mac 选择 Apple Silicon（arm64）版本。'],
        expected: '得到所选应用的 Mac 安装包。',
        extra: [
          { title: 'Codex 桌面端', detail: '在 OpenAI 的 ChatGPT 下载页查找 Mac 安装包；安装后可能叫 Codex，也可能叫 ChatGPT，工具箱会识别对应的官方应用。' },
          { title: 'WorkBuddy', detail: '到腾讯 WorkBuddy 官网下载 macOS 版。' },
          { title: 'Claude Desktop', detail: '到 Claude 官网的下载页选择 macOS 版桌面应用。' },
          { title: 'OpenCode', detail: '到 OpenCode 官网下载 macOS 桌面端，注意与同名命令行版本区分。' },
        ],
        action: '回首页核对应用名称',
        page: 'home',
      },
      {
        title: '装进「应用程序」文件夹',
        where: '下载好的安装包 → 应用程序',
        detail: '只下载或直接打开安装包，还不算完成安装。',
        bullets: ['.dmg：双击打开，把应用图标拖入「应用程序」。', '.pkg：双击，按系统安装器提示完成。', '保留官方应用名，不要改名；首次打开按 macOS 的提示操作。'],
        expected: '能在「应用程序」里找到并打开这个应用。',
        extra: [
          { title: '放在下载文件夹为什么找不到？', detail: '这些桌面端的检测使用系统或当前用户的「应用程序」目录。不要只留在「下载」文件夹或安装镜像里运行，也不要改掉官方应用名。' },
          { title: '为什么安装时问密码？', detail: '安装 .pkg 时 macOS 可能要求一次系统登录密码，这是系统安装器的提示；工具箱本身不要求管理员权限。' },
        ],
        action: '回首页准备重新检测',
        page: 'home',
      },
      {
        title: '重新检测，确认已配好',
        where: '工具箱首页 → 重新检测 → 对应桌面端 → 配置',
        detail: '先确认显示版本号。当前账号已配好且能用的，直接打开即可。',
        bullets: ['点「重新检测」，核对对应桌面端的版本和配置状态。', '未配好时点「配置」，选择密钥来源，再点「检测模型」并选择模型、保存。', '打开应用，发一个简单问题确认能回复。'],
        expected: '桌面端使用当前账号配置，并能正常回复。',
        extra: [
          { title: 'Claude Desktop 保存后没生效？', detail: '先保存当前工作，把 Claude Desktop 完全退出，再重新打开，让它读取新配置。' },
          { title: 'Codex 桌面端和 CLI 为什么一起变了？', detail: 'Codex 桌面端与 Codex CLI 共用一份配置。配好其中一个，另一个也会使用这份设置。' },
          { title: '重新检测后还是未安装？', detail: '先确认应用真的放在「应用程序」目录里、仍使用官方名称，并且能从那里打开。仍失败时到「检查」查看具体原因。' },
        ],
        action: '回首页检测并配置',
        page: 'home',
      },
    ],
  },
  {
    id: 'messages',
    title: '看到这句提示怎么办',
    lead: '找到界面上的原话，展开对应说明，再按提示处理。',
    category: 'advanced',
    minutes: 4,
    keywords: ['报错', '提示', '安装失败', '更新失败', '登录过期', '密钥失效', '余额', '证书', '网络', '配置被改过', '检测失败', '文件夹', '日志'],
    steps: [
      {
        title: '装不上、更新不了',
        where: '失败提示 → 查看日志；更多 → 安装卸载',
        detail: '先记录失败提示，再展开下面同名的说明。',
        bullets: ['确认失败的是工具箱更新，还是某个 AI 工具的安装。', '按对应原因处理后再重试，不要连续重复点击安装。'],
        expected: '安装继续进行，或日志里有明确的失败原因。',
        extra: [
          { title: errors.diskFull.title, detail: '清理安装目录所在磁盘的空间。可以复制界面提供的路径，找到需要检查的目录。' },
          { title: errors.permission.title, detail: '检查当前用户是否能写入安装目录，以及安全软件是否拦截。本软件以普通权限运行，不会自动提权。' },
          { title: errors.installBlocked.title, detail: '检查杀毒软件的隔离记录；确认文件可信后恢复，并将可信的安装目录加入信任。' },
          { title: errors.toolRunning.title, detail: '正在使用的工具占用了文件。先保存工作并关闭对应工具窗口，再重试。' },
          { title: errors.downloadTimeout.title, detail: '已经安装的工具不受这次下载失败影响。检查网络，或点「换官方源重试」。' },
        ],
        action: '查看安装与更新结果',
        page: 'maintenance',
      },
      {
        title: '连不上、登录不了',
        where: '左侧检查 → 连接自检',
        detail: '按错误区分网络、登录、密钥和余额问题。',
        bullets: ['点「重新检查」，再测试当前连接。', '找到下方同名提示，处理后回到原来的工具再试。'],
        expected: '连接测试恢复正常，或已取得需要交给客服的错误信息。',
        illustration: 'health',
        extra: [
          { title: errors.tlsIntercepted.title, detail: '企业网络或安全软件可能替换了连接证书。尝试手机热点等其他网络，或请网络管理员处理证书拦截。' },
          { title: errors.certDate.title, detail: '在系统设置中自动同步日期、时间和时区；仍报错时换一个网络重试。' },
          { title: errors.timeout.title, detail: '检查网络，稍后重试。已经安装的工具仍保留，但调用 AI 仍需要可用的网络连接。' },
          { title: errors.tooManyRequests.title, detail: '暂时停止连续点击，稍后再试。已经安装的工具和保存的配置不会因此清除。' },
          { title: errors.sessionExpired.title, detail: '重新登录星芒账号。已写入工具的 Key 不会因工具箱登录过期而清除；重新登录前，余额和用量不能正常更新。' },
          { title: errors.keyInvalid.title, detail: '确认当前登录的是要使用的账号，再按提示点「一键修复」，用当前账号重新写入 Key。' },
          { title: errors.noBalance.title, detail: '到个人中心充值，确认余额到账后再试。' },
        ],
        action: '检查当前连接',
        page: 'health',
      },
      {
        title: '首页和打开文件夹时',
        where: '工具箱首页 → 工具状态或文件夹提示',
        detail: '状态提醒不一定表示需要重装，先确认它说的是配置还是文件夹。',
        bullets: ['找到下面与首页一致的提示。', '自己有意改过配置时，先核对内容，再决定是否重新写入。'],
        expected: '工具使用正确的配置，文件任务在选定的项目内进行。',
        extra: [
          { title: statuses.tool.configChanged[0], detail: '其他程序或手工操作改过配置，当前账号的 Key 可能已不在里面。要用星芒配置就重新写入 Key；如果这是你有意做的修改，在「…」中选择「就用现在这份」。' },
          { title: statuses.tool.detectionFailed[0], detail: '检测失败不等于没安装。先查看具体原因，处理后重新检测。' },
          { title: '这个文件夹范围太大', detail: '用户主目录、磁盘根目录、桌面、下载、文档等范围太大，改选具体项目文件夹。若仍选择这次打开，不会把该目录标为信任，也不会自动生成项目说明。' },
        ],
        action: '回首页查看具体提示',
        page: 'home',
      },
      {
        title: '还是不知道怎么办',
        where: '检查 → 去处理；更多 → 反馈',
        detail: '先让检查页定位问题，再把失败位置和报告提供给客服。',
        bullets: ['在检查页按「去处理」完成建议操作。', '环境问题查看反馈页的运行日志，安装失败查看安装卸载页的安装日志。', '预览反馈报告，核对后复制或下载，连同操作步骤和截图交给客服。'],
        expected: '客服拿到具体错误和排查结果，能够继续定位。',
        extra: [{ title: '反馈报告里有什么？', detail: '报告会带上次连接自检结果并自动脱敏。发送前仍要预览，确认截图和补充文字不含完整 Key、密码或无关项目资料。' }],
        action: '预览反馈报告',
        page: 'feedback',
      },
    ],
  },
  {
    id: 'trouble',
    title: '出问题怎么办',
    lead: '找到和你一样的情况，按对应步骤处理。不要一出错就重装所有工具。',
    category: 'advanced',
    minutes: 4,
    keywords: ['Codex', '桌面端', '安装', '未识别', '没检测到', '已配好', '英文', '中文', '报错', '失败', '打不开', '不回复', '检查', '诊断', '网络', '密钥', '余额', '额度', '反馈', '客服'],
    steps: [
      {
        title: '装了却没识别：先确认应用和系统账号',
        where: '工具箱首页 → Codex 桌面端 → 重新检测',
        detail: '先确认电脑能打开 Codex 桌面端，再重新检测。装了 Codex CLI 不代表装了桌面端。',
        bullets: ['Windows 用安装 Codex 的同一个系统用户。', 'Mac 确认已完成安装，不是只下载了安装包。', '点「重新检测」，记下仍然出现的错误。'],
        expected: '读到桌面端状态，或取得具体检测错误。',
        extra: [{ title: '检测失败或安装失败在哪里看？', detail: '检测失败不等于未安装。安装日志在「更多」→「安装卸载」；记录系统、Codex 版本和错误，不必重装 Node.js 或 Python。' }],
        action: '回首页重新检测 Codex',
        page: 'home',
      },
      {
        title: '已配好却打不开：查看启动结果',
        where: '工具箱首页 → Codex 桌面端 → 打开',
        detail: '「已配好」说明设置保存了，还要点「打开」启动 Codex。',
        bullets: ['提示已运行时选「打开窗口」。', '刚改过配置时先保存任务，再选「重启 Codex」。', '其他错误记下原文，不要连续重复点击。'],
        expected: '看到 Codex 窗口，或取得明确启动错误。',
        extra: [{ title: '能打开，但还是英文？', detail: '在桌面端「配置」→「界面语言与文件夹权限」点「检查中文界面」，按结果决定是否「启用中文界面」。启用可能重开 Codex，先保存工作。' }],
        action: '回首页检查 Codex 打开结果',
        page: 'home',
      },
      {
        title: '能打开但不回复：测试当前连接',
        where: '左侧检查 → 连接自检 → 测试连接',
        detail: '测试当前配置能不能用，再按结果修正。',
        bullets: ['先点「重新检查」，再点「测试连接」。', '按「去处理」修正密钥、模型、额度或网络问题。', '改配置后重开 Codex，再发一个简单问题。'],
        expected: 'Codex 能正常返回回复。',
        extra: [{ title: '官方账号、取消提示或可选环境', detail: 'ChatGPT 账号来源在 Codex 内确认官方登录和额度。主动停止产生的取消提示不等于请求故障；没用到的可选环境不用马上安装。' }],
        illustration: 'health',
        action: '打开检查测试 Codex 连接',
        page: 'health',
      },
      {
        title: '预览报告后联系支持',
        where: '更多 → 反馈 → 预览反馈报告',
        detail: '把「点了哪里、出现什么」和报告一起提供给客服。',
        bullets: ['预览报告，核对后复制或下载。', '通过右上角「帮助与客服」发送报告、报错截图和操作步骤。'],
        expected: '客服能看清问题发生的位置和错误信息。',
        extra: [{ title: '发报告前检查什么？', detail: '报告会自动脱敏，截图和自己补充的文字仍要核对；不要发送完整 Key、账号密码或无关项目资料。' }],
        action: '打开反馈并预览报告',
        page: 'feedback',
      },
    ],
  },
];
