import { useRef, useState } from 'react';
import { Archive, Check, Download, FolderOpen, Info, Plus, Settings, Trash2 } from 'lucide-react';
import { BalanceTierProvider, BrandIcon, Button, Card, Confirm, Dialog, Drawer, Empty, Input, Kbd, ListRow, Logo, Menu, Notice, PageHead, Pill, Popover, Progress, SearchInput, Segment, Select, SessionRow, SettingRow, Skeleton, Switch, Table, Tabs, Textarea, ToastProvider, ToolRow, Toolbar, useReducedMotion, useToast } from './ui';
import './gallery.css';
import { Coachmark, Tooltip } from './ui';

function GalleryContent() {
  const [coach, setCoach] = useState(false); const [coachStep, setCoachStep] = useState(1);
  const [query, setQuery] = useState(''); const [dialog, setDialog] = useState(false); const [drawer, setDrawer] = useState(false); const [confirm, setConfirm] = useState(false);
  const [enabled, setEnabled] = useState(true); const [tab, setTab] = useState('all'); const [segment, setSegment] = useState('a'); const [draft, setDraft] = useState('');
  const [result, setResult] = useState(''); const [notice, setNotice] = useState(true); const [formValue, setFormValue] = useState(''); const initial = useRef<HTMLInputElement>(null);
  const toast = useToast(); useReducedMotion();
  const choose = (label: string) => { setResult(label); toast.show(label, 'ok'); };
  return <main className="xm-gallery">
    <PageHead title="星芒 AI / 组件检阅" lead="UI v3.1.1" actions={<Logo kind="horizontal" height={32} testId="gallery-logo" />} />
    <output className="xm-gallery-result" data-testid="gallery-result" aria-live="polite">{result}</output>
    <Toolbar testId="gallery-toolbar" left={<Segment label="连接来源" options={[{ value: 'a', label: '全部' }, { value: 'off', label: '不可用', disabled: true }, { value: 'b', label: '已启用' }]} value={segment} onChange={setSegment} />} search={<SearchInput label="搜索组件" value={query} onChange={setQuery} />} right={<Button icon={Plus} variant="primary" onClick={() => { setDraft(''); setDialog(true); }}>打开配置</Button>} />
    {notice && <Notice tone="accent" icon={Info} title="任务正在进行" body="已处理 6 项。" progress={60} onDismiss={() => setNotice(false)} />}
    <section className="xm-gallery-section" aria-labelledby="gallery-buttons"><h2 id="gallery-buttons">V3-001 / Button</h2><div className="xm-gallery-button-matrix">{(['primary', 'secondary', 'ghost', 'danger', 'accent', 'balance'] as const).map(variant => <div key={variant}>{(['md', 'sm', 'xs'] as const).map(size => <Button key={size} variant={variant} size={size} icon={Download} onClick={() => choose(variant + '-' + size)}>{variant + ' ' + size}</Button>)}<Button variant={variant} disabled>不可用</Button><Button variant={variant} loading>处理中</Button></div>)}</div><BalanceTierProvider value="bad"><Button variant="balance">充值</Button></BalanceTierProvider><Button icon={Settings} aria-label="配置工具" title="配置工具" /><Kbd keys="⌘ K" /></section>
    <section className="xm-gallery-section"><h2>V3-003 / Pill · V3-004 / Card · V3-005 / ToolRow</h2><div className="xm-gallery-inline">{(['ok', 'warn', 'bad', 'accent', 'neutral'] as const).map(tone => <Pill key={tone} tone={tone} dot>{tone}</Pill>)}</div><Card title="你的工具" meta="1 个已安装" padding="none" collapsible><ToolRow tool="claude" status="ready" version="2.1.0" model="claude-model" testId="gallery-tool-row" primaryAction={<Button icon={FolderOpen} variant="primary" size="sm" onClick={() => choose('工具已打开')}>打开</Button>} extraAction={<Button icon={Settings} variant="ghost" size="sm" aria-label="配置 Claude Code" />} menu={[{ label: '卸载', danger: true, onSelect: () => setConfirm(true) }]} /><ToolRow tool="codexDesktop" status="unconfigured" primaryAction={<Button variant="secondary" size="sm">配 Key</Button>} /></Card></section>
    <section className="xm-gallery-section"><h2>V3-006 / ListRow · SessionRow</h2><Card padding="none"><ListRow icon={Archive} title="项目连接" desc="C:\Projects\demo" descMono meta="今天 12:30" actions={<Button size="xs" onClick={() => choose('详情已打开')}>查看</Button>} /><SessionRow tool="codex" title="整理工具配置" path="C:\Projects\demo" model="gpt-model" count={8} when="今天" archived onOpen={() => choose('会话已打开')} /></Card></section>
    <section className="xm-gallery-section"><h2>V3-009 / Switch · V3-012 / Input · V3-008 / Segment</h2><Switch checked={enabled} onChange={setEnabled} label="完成后通知" description="任务完成后提醒。" testId="gallery-switch" /><form onSubmit={event => { event.preventDefault(); choose('表单已提交：' + formValue); }} className="xm-gallery-form"><Input label="配置名称" value={formValue} onChange={event => setFormValue(event.target.value)} testId="gallery-name" /><Input label="访问密码" password defaultValue="draft-secret" error="请检查密码" testId="gallery-password" /><Select label="平台" options={[{ value: 'win', label: 'Windows' }, { value: 'mac', label: 'macOS' }]} /><Textarea label="备注" hint="只保存在此设备" /><Button type="submit" variant="primary">提交表单</Button></form></section>
    <section className="xm-gallery-section"><h2>V3-021 / Dialog · V3-023 / Drawer · V3-024 / Toast · V3-020 / Menu</h2><div className="xm-gallery-inline"><Button onClick={() => setDrawer(true)}>打开详情</Button><Button onClick={() => setConfirm(true)}>确认删除</Button><Button onClick={() => { toast.show('第一条'); toast.show('第二条'); toast.show('第三条'); toast.show('第四条'); }}>连续通知</Button><Menu label="文本操作" anchor={<Button>文本操作</Button>} items={[{ label: '复制', onSelect: () => choose('已复制') }, { label: '不可执行', disabled: true, onSelect: () => choose('错误') }, 'divider', { label: 'Save', onSelect: () => choose('已保存') }, { label: '删除', danger: true, onSelect: () => choose('已删除') }]} /><Popover title="配置提示" anchor={<Button>配置提示</Button>}><p>写入配置前会保存备份。</p><Button onClick={() => choose('查看备份')}>查看备份</Button></Popover></div></section>
    <section className="xm-gallery-section"><h2>V3-029 / Empty · V3-027 / Progress · V3-028 / Skeleton</h2><Progress value={62} label="下载 62%" /><Skeleton rows={2} /><Empty icon={Check} title="没有待处理项目" description="任务会显示在这里。" /></section>
    <section className="xm-gallery-section"><h2>V3-007 / Tabs · V3-031 / Table · SettingRow</h2><Tabs label="任务筛选" items={[{ value: 'all', label: '全部任务' }, { value: 'disabled', label: '暂停', disabled: true }, { value: 'active', label: '启用中' }]} value={tab} onChange={setTab} /><Table label="配置记录" columns={[{ key: 'name', label: '名称' }, { key: 'status', label: '状态' }, { key: 'actions', label: '操作' }]} rows={[{ id: '1', name: 'Claude', status: <Pill tone="ok">有效</Pill>, actions: <Button size="xs" onClick={() => choose('内部动作')}>独立动作</Button> }]} rowKey={row => String(row.id)} onRowClick={() => choose('表格行已打开')} empty="暂无数据" /><SettingRow title="通知" description="任务完成时提醒" control={<Switch checked={enabled} onChange={setEnabled} aria-label="任务通知" />} /></section>
    <section className="xm-gallery-section"><h2>BrandIcon / Logo / Kbd</h2><div className="xm-gallery-inline">{['claude', 'codex', 'gemini', 'grok', 'node', 'npm', 'python'].map(tool => <BrandIcon key={tool} tool={tool} size={40} variant="tile" />)}<Logo kind="micro" /><Logo kind="symbol" /><Logo kind="wordmark" /></div></section>
    <section className="xm-gallery-section"><h2>V3-018 / Tooltip · V3-036 / Coachmark</h2><div className="xm-gallery-inline"><Tooltip text="可以用键盘聚焦查看提示"><Button testId="gallery-tooltip-trigger">查看提示</Button></Tooltip><Button testId="gallery-coach-open" onClick={() => { setCoachStep(1); setCoach(true); }}>查看新手提示</Button></div></section>
    <Coachmark open={coach} target="[data-testid='gallery-coach-open']" title={coachStep === 1 ? '先查看当前步骤' : '随时返回这里'} body="提示只指向可见的控件，可以跳过，也可以按 Esc 结束。" step={coachStep} count={2} onNext={() => coachStep === 2 ? setCoach(false) : setCoachStep(2)} onClose={() => setCoach(false)} testId="gallery-coach" />
    <Dialog open={dialog} title="工具配置" subtitle="保存配置后生效" dirty={draft.length > 0} initialFocus={initial} onClose={() => setDialog(false)} testId="gallery-dialog" footer={<><Button onClick={() => setDraft('')}>重置草稿</Button><Button variant="primary" onClick={() => { choose('配置已保存'); setDialog(false); }}>保存配置</Button></>}><label htmlFor="gallery-draft">配置草稿</label><input ref={initial} id="gallery-draft" className="xm-gallery-draft" value={draft} onChange={event => setDraft(event.target.value)} /><Menu label="配置动作" anchor={<Button>配置动作</Button>} items={[{ label: '查看路径', onSelect: () => choose('已查看路径') }, { label: '复制路径', onSelect: () => choose('已复制路径') }]} /></Dialog>
    <Drawer open={drawer} title="详细配置" onClose={() => setDrawer(false)} footer={<Button onClick={() => setDrawer(false)}>完成</Button>} testId="gallery-drawer"><Menu label="详情操作" anchor={<Button>详情操作</Button>} items={[{ label: '复制详情', onSelect: () => choose('已复制详情') }, { label: '重新检查', onSelect: () => choose('已检查') }]} /><Popover title="附加选项" anchor={<Button>附加选项</Button>}><Button onClick={() => choose('已选附加动作')}>附加动作</Button></Popover></Drawer>
    <Confirm open={confirm} title="删除配置" body="这份配置会从设备移除。" requireAck danger onClose={() => setConfirm(false)} onOk={() => { setConfirm(false); choose('确认删除完成'); }} okLabel="删除配置" />
  </main>;
}
export function ComponentGallery() { return <ToastProvider testId="gallery-toasts"><GalleryContent /></ToastProvider>; }
