/* Account prototype module. All data and payments are local demonstrations. */
(() => {
  'use strict';
  const XM = window.XM = window.XM || {};
  const clone = (x) => JSON.parse(JSON.stringify(x));
  const usd = (n, fine = false) => n == null || !Number.isFinite(Number(n)) ? '—' : '$' + Number(n).toFixed(fine ? (Math.abs(Number(n))>0&&Math.abs(Number(n))<.0001?6:4) : 2);
  const fmt = (n) => n == null ? '—' : Number(n).toLocaleString('en-US');
  const localDate = date => [date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(date.getDate()).padStart(2,'0')].join('-');
  const localStamp = date => localDate(date)+' '+[date.getHours(),date.getMinutes()].map(n=>String(n).padStart(2,'0')).join(':');
  const stamp = () => localStamp(new Date());
  const datePlus = (days) => localDate(new Date(Date.now() + days * 86400000));
  const roundUSD = n => Math.round((n+Number.EPSILON)*1e6)/1e6;
  const uid = (prefix) => prefix + '-' + Date.now().toString(36) + '-' + (++sequence);
  let sequence = 0;
  const closeBtn = '<span class="spacer"></span><button class="btn btn-secondary" onclick="A.closeDialog()">返回</button>';
  const note = (text, kind = 'info') => `<div class="callout ${kind}">${ic('info')}<span>${text}</span></div>`;
  const error = (f) => f.err ? `<div class="xm-form-error" role="alert">${esc(f.err)}</div>` : '';
  const keyLabels = {active:'启用',disabled:'已停用',expired:'已过期',exhausted:'额度用尽'};
  const orderLabels = {pending:'等待付款',querying:'正在查询',paid:'已到账',failed:'付款失败',unknown:'待核实',timeout:'超时待核实'};
  const tabs = [['overview','我的账号'],['dashboard','用量看板'],['keys','密钥'],['usage','调用明细'],['tasks','异步任务'],['recharge','充值与订阅'],['orders','我的订单'],['invite','邀请返利'],['devices','登录设备']];
  const plans = [{id:'lite',name:'轻量包',price:9,quota:15,limit:2,days:30,description:'适合偶尔使用 AI 的个人用户'}, {id:'pro',name:'专业包',price:29,quota:55,limit:2,days:30,description:'适合持续使用 AI 的工作流'}];
  const channels = [{id:'stripe',name:'Stripe',currency:'USD',enabled:true,subscription:true,description:'银行卡结账',minimum:5},{id:'creem',name:'Creem',currency:'USD',enabled:true,subscription:true,description:'在线结账',minimum:10},{id:'epay',name:'Epay',currency:'USD',enabled:false,subscription:true,description:'在线结账',minimum:5},{id:'waffo',name:'Waffo Pancake',currency:'USD',enabled:false,subscription:true,description:'在线结账',minimum:5}];
  const field = (label, input, hint = '') => `<div class="field"><label>${label}</label>${input}${hint ? `<div class="hint">${hint}</div>` : ''}</div>`;
  function makeUsage(rows, team = false) {
    const source = rows.length ? rows : [{model:'gpt-5.3-codex',key:team?'团队工作 Key':'个人 Key',group:'默认分组',inTok:4600,outTok:890,cost:.045,ms:2340,stream:true}];
    return Array.from({length:team?5:14},(_,i) => ({...clone(source[i%source.length]), id:(team?'TU':'U')+(i+1), t:localStamp(new Date(Date.now()-i*7*3600000)), daysAgo:i*7/24,status:i===5?'failed':'success', requestId:'req-demo-'+(team?'team-':'personal-')+(i+1), cacheTokens:i%3===0?null:1200,firstTokenMs:i%3===0?null:840, billing:i%4===0?'subscription':'balance', cost:i===5?0:source[i%source.length].cost}));
  }
  function makeData(user, seed, isNew = false) {
    const team = user.name === 'xm-team';
    const keys = isNew ? [] : seed ? clone(S.keys) : [{id:'team-k1',name:'团队工作 Key',group:'默认分组',masked:'sk-demo-****-TEAM',full:'sk-demo-placeholder-team-key',status:'active',created:'2026-09-01',used:'昨天'}];
    keys.forEach((k,i)=>Object.assign(k,{quotaMode:i===0?'unlimited':'limited',quota:i===0?null:20,usedUSD:i===0?.21:.12,expiresAt:null,show:false,status:k.status==='revoked'?'disabled':k.status}));
    if(seed) keys.push({id:'k-demo-disabled',name:'暂停中的测试 Key',group:'默认分组',masked:'sk-demo-****-PAUS',full:'sk-demo-placeholder-paused',status:'disabled',quotaMode:'unlimited',quota:null,usedUSD:0,expiresAt:null,created:'2026-09-01',used:'从未'},{id:'k-demo-expired',name:'临时任务 Key',group:'默认分组',masked:'sk-demo-****-EXPD',full:'sk-demo-placeholder-expired',status:'expired',quotaMode:'limited',quota:5,usedUSD:1.1,expiresAt:'2026-09-01',created:'2026-08-01',used:'8 月 31 日'},{id:'k-demo-exhausted',name:'限额 Key',group:'默认分组',masked:'sk-demo-****-USED',full:'sk-demo-placeholder-exhausted',status:'exhausted',quotaMode:'limited',quota:5,usedUSD:5,expiresAt:null,created:'2026-08-20',used:'昨天'});
    const u = {...user, balance:isNew?0:(user.balance??0), reward:isNew?0:(user.reward??0)};
    const orders = isNew || !seed ? [] : clone(S.orders).map(o=>({...o,owner:u.name,status:'paid',kind:'recharge',amountUSD:o.amount,currency:'USD',checkoutAmount:o.amount,credited:true,quote:{currency:'USD',checkoutAmount:o.amount,amountUSD:o.amount,way:o.way,discount:0},queryCount:1}));
    return {user:u, keys, orders, usage:isNew?[]:makeUsage(seed?S.usage:[],team), tasks:isNew?[]:(seed?clone(S.tasks):[]), devices:isNew?[{id:1,name:'星芒客户端',ip:'—',when:'当前设备',current:true}]:clone(seed?S.devices:[{id:1,name:'星芒客户端',ip:'—',when:'当前设备',current:true}]), chat:seed?S.chat:{convs:[],active:null,mode:'text',group:'默认分组',model:'claude-sonnet-5',draft:'',params:{temp:.7,maxTokens:'模型默认',freq:0,presence:0,seed:'随机'}}, subscriptions:isNew?[]:[{id:team?'sub-team':'sub-personal',plan:'lite',name:'轻量包',quota:15,used:3.2,expiresAt:datePlus(16),status:'active',startsAt:datePlus(-14)},{id:team?'sub-team-old':'sub-personal-old',plan:'pro',name:'专业包',quota:55,used:55,expiresAt:datePlus(-2),status:'expired',startsAt:datePlus(-32)}], preference:'subscription_first', drafts:{}, filters:{usage:{range:'7d',model:'',key:'',group:'',status:'',page:1},tasks:{query:'',status:'',page:1},orders:{status:'',page:1}}, scenes:{},dashboardRange:'7d',usedCodes:[],purchases:isNew?{lite:0,pro:0}:{lite:1,pro:1},expired:false};
  }
  function st() {
    if(!S._xmAccount){
      const store = S._xmAccount = {records:{},active:S.user?.name||null,channels:clone(channels),paymentOutcome:'paid',switchOutcome:'ready',switching:null};
      if(S.user){const seeded=Boolean(S.launched&&S.keys.length&&S.accounts.some(a=>a.name===S.user.name));store.records[S.user.name]=makeData(S.user,seeded,!seeded); S.accounts.forEach(u=>{if(!store.records[u.name])store.records[u.name]=makeData(u,false);}); bind(store.records[S.user.name]);}
    }
    return S._xmAccount;
  }
  function bind(record) { S.user=record.user; for(const key of ['keys','orders','usage','tasks','devices','chat']) S[key]=record[key]; }
  function data() {const store=st(); return store.records[S.user?.name] || null;}
  function saveCurrent() {
    const store=st(), record=store.records[store.active]; if(!record)return;
    if(S.user?.name===store.active){record.user=S.user; for(const key of ['keys','orders','usage','tasks','devices','chat'])record[key]=S[key]; if(S.view==='account') record.drafts[S.accountTab]=S.pageForm||S.form||{};}
    S.accounts=S.accounts.map(u=>u.name===record.user.name?{...record.user}:u);
  }
  function pageDraft(tab) {const d=data(); return d.drafts[tab] ||= tab==='recharge'?{amount:30,pay:'stripe',code:''}:{};}
  function statusBox(page,rows,emptyText,action='') {
    const status=data()?.scenes[page]||(typeof XM.pageStatus==='function'?XM.pageStatus('account-'+page):'ready');
    if(status==='loading')return `<div class="xm-state" role="status" data-testid="account-${page}-loading">${ic('refresh','spin')}<h3>正在读取，请稍等</h3><p>读取完成后会在这里显示。</p></div>`;
    if(status==='error')return `<div class="xm-state" data-testid="account-${page}-error"><h3>暂时没能读取</h3><p>已有记录仍然保留，可以稍后再试。</p><button class="btn btn-secondary" onclick="A.accountReload('${page}')">重新读取</button></div>`;
    if(status==='empty'||(!rows.length&&status!=='filterEmpty'))return `<div class="xm-state" data-testid="account-${page}-empty"><h3>${emptyText}</h3>${action}</div>`;
    if(status==='filterEmpty')return `<div class="xm-state" data-testid="account-${page}-filter-empty"><h3>没有符合条件的记录</h3><p>试着放宽时间范围或清除筛选。</p><button class="btn btn-secondary" onclick="A.accountResetFilter('${page}')">清除筛选</button></div>`;
    return '';
  }
  function pager(page, count, size=5) {const f=data().filters[page],total=Math.max(1,Math.ceil(count/size));f.page=Math.max(1,Math.min(f.page||1,total));return `<div class="xm-pagination"><span>共 ${count} 条 · 第 ${f.page} / ${total} 页</span><span><button class="btn btn-ghost sm" ${f.page===1?'disabled':''} onclick="A.accountPage('${page}',-1)">上一页</button><button class="btn btn-ghost sm" ${f.page===total?'disabled':''} onclick="A.accountPage('${page}',1)">下一页</button></span></div>`;}
  function table(headers, rows) {return `<div class="table-wrap"><table class="table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`;}
  function metrics(entries) {return `<div class="grid3 xm-metrics">${entries.map(([title,value,help])=>`<div class="card card-body stat"><b>${value}</b><span>${title}</span>${help?`<small>${help}</small>`:''}</div>`).join('')}</div>`;}
  function rangeControl(range, action) {return `<span class="segment" aria-label="统计时间">${[['24h','24 小时'],['7d','7 天'],['30d','30 天']].map(([v,l])=>`<button class="${range===v?'on':''}" aria-pressed="${range===v}" onclick="${action}('${v}')">${l}</button>`).join('')}</span>`;}
  function overview() {
    const d=data(),u=S.user,f=pageDraft('overview');
    return `<div class="grid2 xm-profile"><div class="card"><div class="card-head"><h2>基本资料</h2></div><div class="card-body"><div class="xm-profile-avatar">${avatarHtml(u,'avatar-big')}<div><strong>${esc(u.display)}</strong><p class="muted">你的账户资料与余额</p><button class="btn btn-secondary sm" onclick="A.dialog('avatar')">更换头像</button></div></div>${field('显示名称',`<input id="account-display" data-testid="account-display" class="input" maxlength="40" value="${esc(f.display??u.display)}" oninput="A.accountDraft('display',this.value)">`)}${field('用户名',`<input class="input" value="${esc(u.name)}" readonly>`,'登录时使用，暂不支持修改。')}${field('邮箱',`<input class="input" value="${esc(u.email)}" readonly>`,'用于找回密码和接收通知。')}<div class="xm-actions"><button class="btn btn-primary" onclick="A.saveProfile()">保存资料</button><button class="btn btn-secondary" onclick="A.dialog('changePw')">修改密码</button></div>${error(f)}</div></div><div class="col"><div class="card"><div class="card-head"><h2>账户余额（美元）</h2></div><div class="acct"><div class="bal"><b data-testid="account-balance">${usd(u.balance)}</b></div><p class="hint">用于星芒账号的按量消费。每次调用的费用可在明细里查看。</p><div class="acts"><button class="btn btn-primary sm" onclick="A.openAccount('recharge')">充值</button><button class="btn btn-secondary sm" onclick="A.openAccount('dashboard')">看用量</button></div></div></div><div class="card"><div class="card-head"><h2>已保存的账号</h2><span class="right">新增设计</span></div>${Object.values(st().records).map(r=>`<div class="lrow"><div class="main-col"><div class="title">${esc(r.user.display)} ${r.user.name===u.name?pill('ok','当前账号'):''}</div><div class="desc">${esc(r.user.email)}</div></div><button class="btn btn-ghost sm" ${r.user.name===u.name||st().switching?'disabled':''} onclick="A.switchAccount(${esc(JSON.stringify(r.user.name))})">${st().switching===r.user.name?'切换中…':'切换'}</button></div>`).join('')}<div class="card-body"><button class="btn btn-secondary sm" data-testid="account-add" onclick="A.accountAdd()">添加另一个账号</button><p class="hint">各账号的余额、订单、Key 和聊天记录分别保存。登录状态失效时需要重新登录。</p></div></div><div class="card"><div class="card-head"><h2>登录与设备</h2></div><div class="card-body"><p>${d.devices.length} 台已登录设备</p><div class="xm-actions"><button class="btn btn-secondary sm" onclick="A.openAccount('devices')">管理设备</button><button class="btn btn-ghost sm" onclick="A.logout()">退出当前账号</button></div></div></div></div></div>`;
  }
  function dashboard() {
    const d=data(),range=d.dashboardRange,days={ '24h':1,'7d':7,'30d':30}[range],rows=d.usage.filter(r=>r.daysAgo<days);
    const head=`<div class="toolbar"><h2>这段时间用了多少</h2><span class="right">${rangeControl(range,'A.accountRange')}</span><button class="btn btn-ghost sm" onclick="A.accountReload('dashboard')">刷新</button></div><p class="hint">统计范围：最近 ${days===1?'24 小时':days+' 天'} · 消费以美元计价，Token 是模型处理文字的计量单位。</p>`;
    const state=statusBox('dashboard',rows,'这段时间还没有用量',`<button class="btn btn-secondary" onclick="A.go('home')">去打开工具</button>`);if(state)return head+`<div class="card">${state}</div>`;
    const sum=rows.reduce((a,r)=>a+r.cost,0),tokens=rows.reduce((a,r)=>a+r.inTok+r.outTok,0),models={};rows.forEach(r=>models[r.model]=(models[r.model]||0)+r.cost);
    const groups=Object.entries(models).sort((a,b)=>b[1]-a[1]);const bucketCount=days===1?6:7,values=Array(bucketCount).fill(0);rows.forEach(r=>values[Math.min(bucketCount-1,Math.floor(r.daysAgo/days*bucketCount))]+=r.cost);values.reverse();const max=Math.max(.01,...values),plot=values.map((v,i)=>`${44+i*65},${164-v/max*126}`).join(' ');
    return head+metrics([['总消费',usd(sum,true),'所选时间内已记录的调用费用'],['请求次数',fmt(rows.length)+' 次',rows.filter(r=>r.status==='failed').length+' 次失败'],['处理 Token',fmt(tokens),'输入 '+fmt(rows.reduce((a,r)=>a+r.inTok,0))+' / 输出 '+fmt(rows.reduce((a,r)=>a+r.outTok,0))]])+`<div class="grid2"><div class="card"><div class="card-head"><h2>消费趋势</h2><span class="right">美元 USD</span></div><div class="card-body"><svg class="xm-trend" viewBox="0 0 480 200" role="img" aria-label="最近${days}天消费趋势；各时间段合计${usd(sum,true)}"><line x1="42" y1="164" x2="446" y2="164" class="xm-axis"/><line x1="42" y1="38" x2="446" y2="38" class="xm-gridline"/><text x="0" y="42">${max.toFixed(2)}</text><text x="24" y="168">0</text><polyline points="${plot}" fill="none" stroke="var(--accent)" stroke-width="3"/>${values.map((v,i)=>`<circle cx="${44+i*65}" cy="${164-v/max*126}" r="4" fill="var(--accent)"><title>第 ${i+1} 段：${usd(v,true)}</title></circle>`).join('')}<text x="42" y="193">${days===1?'24 小时前':days+' 天前'}</text><text x="417" y="193">现在</text></svg><details><summary>查看趋势数据</summary><div class="xm-chart-values">${values.map((v,i)=>`<span>第 ${i+1} 段 <b>${usd(v,true)}</b></span>`).join('')}</div></details></div></div><div class="card"><div class="card-head"><h2>模型消费占比</h2></div><div class="card-body">${groups.map(([model,cost])=>`<div class="xm-model-row"><div><span>${esc(model)}</span><b>${usd(cost,true)}</b></div><div class="xm-bar"><i style="width:${sum?cost/sum*100:0}%"></i></div><small>${sum?(cost/sum*100).toFixed(1):0}% 的消费</small></div>`).join('')}</div></div></div><div class="card xm-gap"><div class="card-head"><h2>速度与排行</h2><button class="btn btn-ghost sm right" onclick="A.openAccount('usage')">查看每次调用</button></div><div class="card-body xm-inline-stats"><span>平均每分钟请求（RPM）<b>${(rows.length/(days*1440)).toFixed(3)}</b></span><span>平均每分钟 Token（TPM）<b>${(tokens/(days*1440)).toFixed(1)}</b></span><span>消费最多的模型<b>${esc(groups[0]?.[0]||'—')}</b></span></div></div>${d.scenes.dashboard==='truncated'?note('当前统计结果达到读取上限，图表只包括已读取的记录。请缩短时间范围以查看完整结果。','warn'):''}`;
  }
  function keysPanel(){const rows=data().keys;return `<div class="card"><div class="card-head"><h2>API Key</h2><span>${rows.length} 把</span><button class="btn btn-primary sm right" data-testid="key-create" onclick="A.dialog('keyEditor')">添加 Key</button></div>${statusBox('keys',rows,'还没有 Key',`<p>Key 是连接星芒服务的凭据。创建后可以选择给哪个工具使用。</p><button class="btn btn-secondary" onclick="A.dialog('keyEditor')">创建第一把 Key</button>`)||table(['名称 / 分组','Key','状态','美元额度 / 已用','到期日期','操作'],rows.map(k=>`<tr data-testid="key-row-${k.id}"><td><strong>${esc(k.name)}</strong><small class="xm-subline">${esc(k.group)}</small></td><td class="mono xm-key-cell">${esc(k.show?k.full:k.masked)}<small class="xm-subline">${k.show?'30 秒后自动隐藏':'默认隐藏完整内容'}</small></td><td>${pill(k.status==='active'?'ok':k.status==='disabled'?'':'warn',keyLabels[k.status]||'状态未知')}</td><td>${k.quotaMode==='unlimited'?'不限额度':usd(k.quota)}<small class="xm-subline">已用 ${usd(k.usedUSD,true)}</small></td><td>${esc(k.expiresAt||'永不过期')}</td><td class="xm-row-actions">${k.status==='active'?`<button class="btn btn-ghost xs" onclick="A.keyShow('${k.id}')">${k.show?'隐藏':'显示'}</button><button class="btn btn-ghost xs" onclick="A.keyRevoke('${k.id}')">停用</button>`:k.status==='disabled'?`<button class="btn btn-secondary xs" onclick="A.keyEnable('${k.id}')">启用</button>`:''}<button class="btn btn-ghost xs" onclick="A.dialog('keyEditor',{id:'${k.id}'})">${k.status==='expired'?'延长有效期':k.status==='exhausted'?'调整额度':'编辑'}</button></td></tr>`).join(''))}</div><p class="hint">停用后，使用这把 Key 的工具无法继续调用。可以重新启用，也可以在工具设置里换一把 Key。</p>`;}
  function usagePanel(){const d=data(),f=d.filters.usage,days={'24h':1,'7d':7,'30d':30}[f.range]||30,all=d.usage,rows=all.filter(r=>r.daysAgo<days&&r.model.toLowerCase().includes(f.model.toLowerCase())&&r.key.toLowerCase().includes(f.key.toLowerCase())&&(!f.group||r.group===f.group)&&(!f.status||r.status===f.status));const pg=pager('usage',rows.length);return `<div class="toolbar xm-filter"><label>时间<select class="input" onchange="A.accountFilter('usage','range',this.value)">${[['24h','24 小时'],['7d','7 天'],['30d','30 天']].map(([v,l])=>`<option value="${v}" ${f.range===v?'selected':''}>最近 ${l}</option>`).join('')}</select></label><label>模型<input class="input" value="${esc(f.model)}" placeholder="例如 gpt" oninput="A.accountFilter('usage','model',this.value,false)"></label><label>Key 名称<input class="input" value="${esc(f.key)}" placeholder="例如 本机" oninput="A.accountFilter('usage','key',this.value,false)"></label><label>分组<select class="input" onchange="A.accountFilter('usage','group',this.value)"><option value="">全部分组</option>${GROUPS.map(g=>`<option ${f.group===g?'selected':''}>${g}</option>`).join('')}</select></label><button class="btn btn-secondary sm" onclick="render()">搜索</button><button class="btn btn-ghost sm" onclick="A.accountResetFilter('usage')">重置</button></div>${metrics([['筛选后消费',usd(rows.reduce((s,r)=>s+r.cost,0),true)],['符合条件的调用',fmt(rows.length)+' 次'],['筛选后 Token',fmt(rows.reduce((s,r)=>s+r.inTok+r.outTok,0))]])}<div class="card">${statusBox('usage',all,'还没有调用记录',`<p>使用工具发起一次请求后，可在这里查看费用。</p>`)||(!rows.length?`<div class="xm-state"><h3>没有符合条件的记录</h3><button class="btn btn-secondary" onclick="A.accountResetFilter('usage')">清除筛选</button></div>`:table(['时间','模型 / Key','输入 / 输出 Token','费用（美元）','耗时 / 状态',''],rows.slice((f.page-1)*5,f.page*5).map(r=>`<tr><td class="mono">${r.t}</td><td><strong>${esc(r.model)}</strong><small class="xm-subline">${esc(r.key)} · ${esc(r.group)}</small></td><td class="mono">${fmt(r.inTok)} / ${fmt(r.outTok)}</td><td class="mono">${usd(r.cost,true)}</td><td>${(r.ms/1000).toFixed(2)} s<small class="xm-subline">${r.status==='success'?'已完成':'调用失败'}</small></td><td><button class="btn btn-ghost xs" data-testid="usage-detail-${r.id}" onclick="A.dialog('usageDetail',{id:'${r.id}'})">详情</button></td></tr>`).join(''))+pg)}</div>`;}
  function tasksPanel(){const d=data(),f=d.filters.tasks,rows=d.tasks.filter(t=>(!f.status||t.status===f.status)&&(t.id+' '+t.model+' '+t.platform).toLowerCase().includes(f.query.toLowerCase()));const pg=pager('tasks',rows.length);return `<div class="toolbar xm-filter"><label>搜索任务<input class="input" value="${esc(f.query)}" placeholder="任务 ID、模型或平台" oninput="A.accountFilter('tasks','query',this.value,false)"></label><label>状态<select class="input" onchange="A.accountFilter('tasks','status',this.value)">${[['','全部状态'],['queued','排队中'],['running','处理中'],['done','已完成'],['failed','失败']].map(([v,l])=>`<option value="${v}" ${f.status===v?'selected':''}>${l}</option>`).join('')}</select></label><button class="btn btn-secondary sm" onclick="render()">搜索</button><button class="btn btn-ghost sm" onclick="A.accountResetFilter('tasks')">重置</button></div><p class="hint">视频、音乐等生成任务需要等待。提交后可离开本页，稍后回来查看进度。</p><div class="card">${statusBox('tasks',d.tasks,'还没有异步任务')||(!rows.length?`<div class="xm-state"><h3>没有符合条件的任务</h3><button class="btn btn-secondary" onclick="A.accountResetFilter('tasks')">清除筛选</button></div>`:table(['任务 / 模型','平台','状态','提交时间','费用（美元）','操作'],rows.slice((f.page-1)*5,f.page*5).map(t=>`<tr><td class="mono">${esc(t.id)}<small class="xm-subline">${esc(t.model)}</small></td><td>${esc(t.platform)}</td><td>${pill(t.status==='done'?'ok':t.status==='failed'?'bad':'warn',{done:'已完成',running:'处理中',queued:'排队中',failed:'失败'}[t.status]||'待核实')}</td><td>${esc(t.t)}</td><td>${usd(t.cost,true)}</td><td><button class="btn btn-ghost xs" onclick="A.dialog('taskDetail',{id:'${t.id}'})">${t.status==='done'?'查看结果':'详情'}</button></td></tr>`).join(''))+pg)}</div>`;}
  function availableChannels(kind='recharge'){return st().channels.filter(c=>c.enabled&&(kind!=='subscription'||c.subscription));}
  function purchaseSlots(record,planId){return (record.purchases[planId]||0)+record.orders.filter(o=>o.kind==='subscription'&&o.planId===planId&&!o.credited&&o.status!=='failed').length;}
  function channelOptions(current,kind='recharge',dialog=false){return availableChannels(kind).map(c=>`<button class="pay-opt ${current===c.id?'on':''}" data-testid="payment-channel-${c.id}" onclick="${dialog?`F.set('channel','${c.id}');render()`:`A.accountDraft('pay','${c.id}',true)`}"><span class="ico">${ic('receipt')}</span><span><strong>${c.name}</strong><small>${c.description} · ${c.currency}</small></span><span class="radio"></span></button>`).join('');}
  function subscriptionList(){const d=data(),active=d.subscriptions.some(x=>x.status==='active'&&x.quota>x.used);return `<div class="card"><div class="card-head"><h2>我的订阅</h2><span>${d.subscriptions.length} 条</span></div>${d.subscriptions.length?d.subscriptions.map(x=>`<div class="lrow"><div class="main-col"><div class="title">${esc(x.name)} ${pill(x.status==='active'?(x.used>=x.quota?'warn':'ok'):'',x.status==='active'?(x.used>=x.quota?'额度已用完':'生效中'):'已到期')}</div><div class="desc">额度 ${usd(x.quota)} · 已用 ${usd(x.used)}<br>到期日期 ${esc(x.expiresAt||'—')}</div></div></div>`).join(''):`<div class="card-body"><p class="muted">当前没有订阅。可以先使用账户余额。</p></div>`}<div class="card-body">${field('消费时先用哪一项',`<select data-testid="billing-preference" class="input" onchange="A.accountPreference(this.value)">${[['subscription_first','订阅优先'],['balance_first','余额优先'],['balance_only','仅使用余额'],['subscription_only','仅使用订阅']].map(([v,l])=>`<option value="${v}" ${d.preference===v?'selected':''} ${v==='subscription_only'&&!active?'disabled':''}>${l}${v==='subscription_only'&&!active?'（暂无可用额度）':''}</option>`).join('')}</select>`,'“优先”会在首选额度不足时尝试另一项；“仅使用”额度不足时会停止调用。')}${!active?note('没有可用的订阅额度。可以购买订阅，或选择使用账户余额。','warn'):''}<button class="btn btn-ghost sm" onclick="A.accountExplainBilling()">看看一次调用如何扣费</button></div></div>`;}
  function rechargePanel(){const d=data(),f=pageDraft('recharge'),opts=availableChannels(),current=opts.find(c=>c.id===f.pay),state=statusBox('recharge',[1],'暂时没有可用的充值渠道',`<p>稍后刷新，或使用有效充值码。</p><button class="btn btn-secondary" onclick="A.accountReload('recharge')">刷新</button>`);if(state)return `<div class="card">${state}</div>`;return `<div class="grid2 xm-commerce"><div class="col"><div class="card"><div class="card-head"><h2>充值到账金额</h2><span class="right">账户余额 ${usd(S.user.balance)}</span></div><div class="card-body"><p class="hint">金额以美元计入账户余额。实际支付金额与币种会在下一步确认。</p><div class="xm-amounts">${[10,30,50,100].map(n=>`<button class="chipbtn ${Number(f.amount)===n?'on':''}" onclick="A.accountDraft('amount',${n},true)">$${n}</button>`).join('')}</div>${field('到账金额（美元 USD）',`<input data-testid="recharge-amount" class="input" type="number" min="1" step="0.01" value="${esc(f.amount??30)}" oninput="A.accountDraft('amount',this.value)">`,current?`当前渠道最低到账金额 ${usd(current.minimum)}。`:'请先选择可用的支付渠道。')}${field('支付渠道',opts.length?`<div class="xm-pay-options">${channelOptions(f.pay)}</div>`:note('暂时没有可用的支付渠道。请稍后刷新，或使用充值码。','warn'),'这里只显示当前可用的渠道。')}${error(f)}<button class="btn btn-primary block" data-testid="recharge-quote" ${!opts.length?'disabled':''} onclick="A.accountQuote()">${f.quoting?'正在获取报价…':'查看支付金额'}</button>${!opts.length?'<button class="btn btn-ghost block" onclick="A.accountReload(\'recharge\')">刷新渠道</button>':''}</div></div><div class="card"><div class="card-head"><h2>兑换充值码</h2></div><div class="card-body">${field('充值码',`<div class="field-row"><input class="input" data-testid="redeem-code" value="${esc(f.code||'')}" placeholder="输入你收到的充值码" oninput="A.accountDraft('code',this.value)"><button class="btn btn-secondary" onclick="A.redeem()">检查充值码</button></div>`)}${f.codeMessage?note(esc(f.codeMessage),f.codeError?'warn':'info'):''}</div></div></div><div class="col"><div class="card"><div class="card-head"><h2>订阅计划</h2></div>${plans.map(p=>{const count=d.purchases[p.id]||0,limited=purchaseSlots(d,p.id)>=p.limit;return `<div class="setting"><div class="l"><strong>${p.name} <span class="mono">${usd(p.price)} / ${p.days} 天</span></strong><span>${p.description}<br>有效期内总额度 ${usd(p.quota)}，不循环重置<br>每个账号最多购买 ${p.limit} 次，已购买 ${count} 次</span></div><div class="r"><button class="btn btn-secondary sm" ${limited?'disabled':''} onclick="A.dialog('subscribe',{plan:'${p.id}'})">${limited?'已达购买上限':'购买'}</button>${limited?'<small class="xm-subline">可选择其他计划</small>':''}</div></div>`;}).join('')}</div>${subscriptionList()}</div></div>`;}
  function ordersPanel(){const d=data(),f=d.filters.orders,rows=d.orders.filter(o=>!f.status||o.status===f.status),pg=pager('orders',rows.length);return `<div class="toolbar xm-filter"><label>订单状态<select class="input" onchange="A.accountFilter('orders','status',this.value)"><option value="">全部状态</option>${Object.entries(orderLabels).filter(([k])=>k!=='querying').map(([v,l])=>`<option value="${v}" ${f.status===v?'selected':''}>${l}</option>`).join('')}</select></label><button class="btn btn-ghost sm" onclick="A.accountResetFilter('orders')">重置</button><span class="right hint">关闭付款页不会取消订单，可在这里继续查询。</span></div><div class="card">${statusBox('orders',d.orders,'还没有订单',`<button class="btn btn-secondary" onclick="A.openAccount('recharge')">去充值</button>`)||(!rows.length?`<div class="xm-state"><h3>没有符合条件的订单</h3><button class="btn btn-secondary" onclick="A.accountResetFilter('orders')">清除筛选</button></div>`:table(['订单号 / 时间','类型','实付金额','到账 / 订阅','状态','操作'],rows.slice((f.page-1)*5,f.page*5).map(o=>`<tr data-testid="order-row-${o.id}"><td class="mono">${esc(o.id)}<small class="xm-subline">${esc(o.when)}</small></td><td>${o.kind==='subscription'?'订阅':o.kind==='reward'?'奖励转入':o.kind==='redeem'?'充值码':'充值'}<small class="xm-subline">${esc(o.way)}</small></td><td>${o.checkoutAmount==null?'—':`${o.currency} ${Number(o.checkoutAmount).toFixed(2)}`}</td><td>${o.kind==='subscription'?esc(o.planName):usd(o.amountUSD)}</td><td>${pill(o.status==='paid'?'ok':o.status==='failed'?'bad':'warn',orderLabels[o.status]||'待核实')}</td><td><button class="btn btn-ghost xs" onclick="A.accountOrder('${o.id}')">${o.status==='paid'?'详情':'查看 / 查询'}</button></td></tr>`).join(''))+pg)}</div>`;}
  function invitePanel(){return `<div class="grid2 xm-profile"><div class="card"><div class="card-head"><h2>邀请好友</h2></div><div class="card-body"><p class="hint">好友使用你的邀请码注册后，符合活动规则的奖励会记到本账号。实际奖励以到账记录为准。</p>${field('我的邀请码',`<div class="field-row"><input class="input mono" value="${esc(S.user.invite||'—')}" readonly><button class="btn btn-secondary" onclick="A.accountCopyInvite()">复制</button></div>`)}<p class="hint">没有邀请码时，请稍后刷新账号资料。</p></div></div><div class="card"><div class="card-head"><h2>可转入奖励（美元）</h2></div><div class="acct"><div class="bal"><b>${usd(S.user.reward)}</b></div><p class="hint">转入后可用于本账号的 AI 消费。</p><button class="btn btn-primary sm" ${!(S.user.reward>0)?'disabled':''} onclick="A.dialog('transferReward')">转入账户余额</button>${!(S.user.reward>0)?'<p class="hint">有可转入奖励后，这里就可以操作。</p>':''}</div></div></div>`;}
  function devicesPanel(){const devices=data().devices;return `<div class="card"><div class="card-head"><h2>登录设备</h2><button class="btn btn-secondary sm right" ${devices.filter(d=>!d.current).length?'':'disabled'} onclick="A.accountRevokeOthers()">退出其他设备</button></div>${statusBox('devices',devices,'暂时没有设备记录')||devices.map(d=>`<div class="lrow"><span class="ico">${ic('monitor')}</span><div class="main-col"><div class="title">${esc(d.current?'星芒客户端 · '+({win:'Windows',mac:'macOS',linux:'Linux'}[S.os]||S.os):d.name)} ${d.current?pill('accent','当前设备'):''}</div><div class="desc">IP ${esc(d.ip)} · ${esc(d.when)}</div></div>${d.current?'<span class="hint">退出请使用“退出当前账号”</span>':`<button class="btn btn-ghost sm" onclick="A.deviceRevoke('${d.id}')">撤销登录</button>`}</div>`).join('')}</div>`;}
  accountHtml = function(){if(!S.user)return welcomeHtml();st();const tab=tabs.some(([k])=>k===S.accountTab)?S.accountTab:'overview',u=S.user;const pages={overview,dashboard,keys:keysPanel,usage:usagePanel,tasks:tasksPanel,recharge:rechargePanel,orders:ordersPanel,invite:invitePanel,devices:devicesPanel};return `<section class="page xm-account" data-testid="account-page"><div class="page-head"><div class="xm-heading"><button class="btn btn-ghost icon" title="返回" onclick="A.accountBack()">${ic('left')}</button><div><h1>个人中心</h1><p>余额、Key、用量与订单都在这里。</p></div></div><div class="actions">${avatarHtml(u,'avatar')}<div><strong>${esc(u.display)}</strong><small class="xm-subline">${esc(u.email)}</small></div></div></div><div class="tabs">${tabs.map(([k,l])=>`<a class="${tab===k?'on':''}" data-testid="account-tab-${k}" onclick="A.openAccount('${k}')">${l}</a>`).join('')}</div>${data().switchMessage?note(esc(data().switchMessage),'warn'):''}${pages[tab]()}</section>`;};
  accountCard = function(){if(!S.user)return `<div class="card"><div class="card-head"><h2>星芒账号</h2></div><div class="acct"><p class="hint">登录后查看余额，并为工具选择星芒服务。</p><div class="acts"><button class="btn btn-primary sm" onclick="A.dialog('login')">登录</button><button class="btn btn-ghost sm" onclick="A.dialog('register')">注册</button></div></div></div>`;st();return `<div class="card"><div class="card-head"><h2>账户余额（美元）</h2><span class="right">${esc(S.user.display)}</span></div><div class="acct"><div class="bal"><b>${usd(S.user.balance)}</b></div><p class="hint">按量费用以实际调用记录为准。</p><div class="acts"><button class="btn btn-primary sm" onclick="A.openAccount('recharge')">充值</button><button class="btn btn-ghost sm" onclick="A.openAccount('dashboard')">用量看板</button></div></div></div>`;};
  Object.assign(A,{
    openAccount(tab='overview'){if(!S.user){A.dialog('login');return;} saveCurrent();S.accPop=null;S.view='account';S.accountTab=tab;S.drawer=null;const f=pageDraft(tab);S.pageForm=f;if(!topDialog())S.form=f;render();},
    accountBack(){saveCurrent();A.go(S.page||'home');},
    accountDraft(key,value,refresh=false){const f=pageDraft(S.accountTab);f[key]=value;f.err='';S.pageForm=f;if(!topDialog())S.form=f;if(refresh)render();},
    accountRange(value){data().dashboardRange=value;render();},
    accountFilter(page,key,value,refresh=true){const d=data();d.filters[page][key]=value;d.filters[page].page=1;if(d.scenes[page]==='filterEmpty')d.scenes[page]='ready';if(refresh)render();},
    accountResetFilter(page){const d=data();if(page==='usage')d.filters.usage={range:'30d',model:'',key:'',group:'',status:'',page:1};if(page==='tasks')d.filters.tasks={query:'',status:'',page:1};if(page==='orders')d.filters.orders={status:'',page:1};d.scenes[page]='ready';render();},
    accountPage(page,offset){data().filters[page].page+=offset;render();},
    accountReload(page){const d=data(),session=S;d.scenes[page]='loading';render();later(()=>{if(S!==session)return;d.scenes[page]='ready';if(data()===d)render();},450);},
    saveProfile(){const d=data(),f=pageDraft('overview'),name=String(f.display??S.user.display).trim();if(!name||name.length>40){f.err='显示名称需要 1–40 个字符。';render();return;}d.user.display=name;f.display=name;f.err='';saveCurrent();render();A.toast('资料已保存');},
    accountAdd(){A.dialog('login');S.form.addAccount=true;topDialog().initial=formFingerprint(S.form);render();},
    accountScenario(page,state){const d=data();if(page==='payment'){st().paymentOutcome=state;for(const r of Object.values(st().records))for(const o of r.orders)if(!o.credited)o.expected=state;}else if(page==='channels'){st().channels.forEach(c=>{c.enabled=state==='all'||(state==='normal'&&['stripe','creem'].includes(c.id))||state===c.id;});}else if(page==='switch'){st().switchOutcome=state;}else if(page==='quote'){d.scenes.quote=state;}else if(page==='subscriptions'){if(state==='insufficient'){d.subscriptions.forEach(x=>x.used=x.quota);d.user.balance=0;}else if(state==='limit'){d.purchases={lite:2,pro:2};}else if(state==='empty'){d.subscriptions=[];d.preference='balance_only';}}else{d.scenes[page]=state;}render();},
    accountPreference(value){if(value==='subscription_only'&&!data().subscriptions.some(s=>s.status==='active'&&s.quota>s.used)){A.toast('没有可用的订阅额度，请先购买订阅。','warn');return;}data().preference=value;render();A.toast('扣费偏好已保存');},
    accountExplainBilling(){const d=data(),active=d.subscriptions.filter(s=>s.status==='active').reduce((n,s)=>n+Math.max(0,s.quota-s.used),0);A.dialog('accountInfo',{title:'每次调用如何扣费',body:`${note('本次示例调用费用为 $0.10，下面只说明扣费规则，不实际扣款。')}<dl class="kv"><dt>账户余额（美元）</dt><dd>${usd(d.user.balance)}</dd><dt>可用订阅额度</dt><dd>${usd(active)}</dd><dt>当前偏好</dt><dd>${{subscription_first:'订阅优先，额度不足时使用余额',balance_first:'余额优先，余额不足时使用订阅',balance_only:'仅使用余额',subscription_only:'仅使用订阅'}[d.preference]}</dd><dt>能否使用</dt><dd>${((d.preference==='balance_only'?d.user.balance:d.preference==='subscription_only'?active:d.user.balance+active)>=.1)?'有足够额度':'额度不足，请充值或购买订阅后再试'}</dd></dl>`});}
  });
  function keyForm(p){const key=p.id?data().keys.find(k=>k.id===p.id):null,f=S.form;return {key,f,values:{kname:f.kname??key?.name??'',kgroup:f.kgroup??key?.group??'默认分组',kquotaMode:f.kquotaMode??key?.quotaMode??'unlimited',kquota:f.kquota??key?.quota??10,kexpiryMode:f.kexpiryMode??(key?.expiresAt?'date':'never'),kexpiry:f.kexpiry??key?.expiresAt??datePlus(30)}};}
  DIALOGS.keyEditor = p=>{const {key,f,values:v}=keyForm(p);return dialogShell({title:key?'编辑 Key':'添加 Key',sub:key?'修改名称、额度和到期日期，Key 内容保持不变。':'创建一把连接星芒服务的 Key。',body:`<div data-testid="key-editor">${field('名称',`<input class="input" data-autofocus maxlength="60" value="${esc(v.kname)}" placeholder="例如：Claude Code · 本机" oninput="F.set('kname',this.value)">`)}${field('分组',`<select class="input" onchange="F.set('kgroup',this.value)">${GROUPS.map(g=>`<option ${g===v.kgroup?'selected':''}>${g}</option>`).join('')}</select>`,'不确定时选择默认分组。')}${field('最多可消费多少（美元）',`<select class="input" data-testid="key-quota-mode" onchange="F.set('kquotaMode',this.value);render()"><option value="unlimited" ${v.kquotaMode==='unlimited'?'selected':''}>不限额度</option><option value="limited" ${v.kquotaMode==='limited'?'selected':''}>设置固定额度</option></select>`,'Key 额度是使用上限，不是额外余额。')}${v.kquotaMode==='limited'?field('额度上限（美元 USD）',`<input class="input" data-testid="key-quota" type="number" min="0.01" step="0.01" value="${esc(v.kquota)}" oninput="F.set('kquota',this.value)">`,key?`这把 Key 已用 ${usd(key.usedUSD,true)}。上限小于或等于已用金额时，会显示“额度用尽”。`:'达到上限后会停止使用，可随时回来调整。'):''}${field('到期设置',`<select class="input" data-testid="key-expiry-mode" onchange="F.set('kexpiryMode',this.value);render()"><option value="never" ${v.kexpiryMode==='never'?'selected':''}>永不过期</option><option value="date" ${v.kexpiryMode==='date'?'selected':''}>指定日期</option></select>`)}${v.kexpiryMode==='date'?field('到期日期',`<input class="input" data-testid="key-expiry" type="date" value="${esc(v.kexpiry)}" oninput="F.set('kexpiry',this.value)">`,'到期后不能继续使用，可延长日期恢复。'):''}${error(f)}</div>`,footer:`<span class="spacer"></span><button class="btn btn-ghost" onclick="A.requestDialogClose('dismiss')">取消</button><button class="btn btn-primary" data-testid="key-save" onclick="A.keySave('${p.id||''}')">${key?'保存修改':'创建 Key'}</button>`});};
  DIALOGS.usageDetail=p=>{const r=data().usage.find(x=>x.id===p.id)||data().usage[p.i];if(!r)return dialogShell({title:'调用详情',body:note('这条记录暂时不可用。请返回明细重新读取。','warn'),footer:closeBtn});return dialogShell({title:'调用详情',sub:r.t+' · '+r.model,wide:true,body:`<dl class="kv"><dt>请求编号</dt><dd class="mono">${esc(r.requestId||'—')}</dd><dt>状态</dt><dd>${r.status==='failed'?'调用失败':'已完成'}</dd><dt>API Key / 分组</dt><dd>${esc(r.key)} / ${esc(r.group)}</dd><dt>输入 / 输出 Token</dt><dd>${fmt(r.inTok)} / ${fmt(r.outTok)}</dd><dt>缓存读取 Token</dt><dd>${fmt(r.cacheTokens)}</dd><dt>费用（美元）</dt><dd>${usd(r.cost,true)}</dd><dt>扣费来源</dt><dd>${r.billing==='subscription'?'订阅额度':'账户余额'}</dd><dt>首字等待</dt><dd>${r.firstTokenMs==null?'—':(r.firstTokenMs/1000).toFixed(2)+' 秒'}</dd><dt>总耗时</dt><dd>${(r.ms/1000).toFixed(2)} 秒</dd><dt>输出方式</dt><dd>${r.stream?'逐字输出（流式）':'完成后一次显示'}</dd></dl>${r.status==='failed'?note('本次调用未成功，记录费用为 $0.0000。可返回工具检查提示后重新发起。','warn'):note('“—”表示该项没有可用数据。')}`,footer:closeBtn});};
  DIALOGS.taskDetail=p=>{const t=data().tasks.find(x=>x.id===p.id);if(!t)return dialogShell({title:'任务详情',body:note('这条任务暂时不可用。','warn'),footer:closeBtn});return dialogShell({title:'任务详情',sub:t.id,body:`<dl class="kv"><dt>平台 / 模型</dt><dd>${esc(t.platform)} / ${esc(t.model)}</dd><dt>状态</dt><dd data-testid="task-status">${{done:'已完成',running:'处理中',queued:'排队中',failed:'失败'}[t.status]||'待核实'}</dd><dt>提交时间</dt><dd>${esc(t.t)}</dd><dt>耗时</dt><dd>${esc(t.dur||'—')}</dd><dt>费用（美元）</dt><dd>${usd(t.cost,true)}</dd></dl>${t.status==='done'?`<div class="xm-task-result"><span>${ic('check')}</span><strong>结果已准备好</strong><p>视频预览 · ${esc(t.model)} · ${esc(t.dur||'—')}</p><div class="xm-video-placeholder" role="img" aria-label="任务结果示例预览">${ic('play')}<span>生成结果预览</span></div></div>`:t.status==='failed'?note('任务处理失败，结果没有生成。先查看工具中的失败原因，再决定是否重新发起。重复生成可能产生新的费用。','warn'):note(t.status==='queued'?'任务正在排队，可以离开本页，稍后回来查询。':'任务仍在处理，可以关闭详情页，稍后继续查询。')}`,footer:`${closeBtn}${['running','queued'].includes(t.status)?`<button class="btn btn-primary" ${t.querying?'disabled':''} onclick="A.accountTaskQuery('${t.id}')">${t.querying?'查询中…':'刷新进度'}</button>`:''}`});};
  DIALOGS.accountInfo=p=>dialogShell({title:p.title,body:p.body,footer:closeBtn});
  function quoteBody(q){return `<dl class="kv"><dt>充值到账</dt><dd>${q.kind==='subscription'?esc(q.planName):usd(q.amountUSD)+' USD'}</dd><dt>支付渠道</dt><dd>${esc(q.way)}</dd><dt>订单原价</dt><dd>${q.currency} ${Number(q.originalAmount).toFixed(2)}</dd><dt>优惠</dt><dd>${q.discount?'- '+q.currency+' '+Number(q.discount).toFixed(2):'无'}</dd><dt>本次实付</dt><dd><strong class="mono xm-price">${q.currency} ${Number(q.checkoutAmount).toFixed(2)}</strong></dd><dt>所属账号</dt><dd>${esc(q.owner)}</dd><dt>报价有效至</dt><dd>${new Date(q.expiresAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</dd></dl>`;}
  DIALOGS.rechargeConfirm = p=>{const d=renderingDialog,f=S.form,q=d.props.quote;if(!q)return dialogShell({title:'确认充值',body:note('请先在充值页获取支付报价。','warn'),footer:`${closeBtn}<button class="btn btn-primary" onclick="A.closeDialog();A.accountQuote()">获取报价</button>`});const expired=q.expiresAt<=Date.now();return dialogShell({title:q.kind==='subscription'?'确认购买订阅':'确认充值',sub:'核对账号、到账金额和实付金额后再继续。',body:`<div data-testid="payment-quote">${quoteBody(q)}${expired?note('这份报价已失效，请重新获取报价。','warn'):''}${error(f)}</div>`,footer:`<span class="spacer"></span><button class="btn btn-ghost" onclick="A.closeDialog()">返回修改</button><button class="btn btn-primary" data-testid="payment-submit" ${f.busy?'disabled':''} onclick="${expired?'A.accountRefreshQuote()':'A.pay()'}">${f.busy?'正在创建订单…':expired?'重新获取报价':'确认并打开付款页'}</button>`});};
  function findOrder(id){for(const record of Object.values(st().records)){const order=record.orders.find(o=>o.id===id);if(order)return {record,order};}return null;}
  DIALOGS.accountOrder = p=>{const found=findOrder(p.id);if(!found)return dialogShell({title:'订单不存在',body:note('没有找到这笔订单。请回到我的订单重新选择。','warn'),footer:closeBtn});const o=found.order;return dialogShell({title:o.kind==='subscription'?'订阅订单':'充值订单',sub:o.id,body:`<div data-testid="payment-order"><div class="xm-order-status" role="status">${pill(o.status==='paid'?'ok':o.status==='failed'?'bad':'warn',orderLabels[o.status])}</div><dl class="kv"><dt>所属账号</dt><dd>${esc(o.owner)}${S.user?.name!==o.owner?'（当前查看的是另一账号的订单）':''}</dd><dt>支付渠道</dt><dd>${esc(o.way)}</dd><dt>实付金额</dt><dd>${o.checkoutAmount==null?'—':o.currency+' '+Number(o.checkoutAmount).toFixed(2)}</dd><dt>${o.kind==='subscription'?'订阅计划':'到账金额（美元）'}</dt><dd>${o.kind==='subscription'?esc(o.planName):usd(o.amountUSD)}</dd><dt>创建时间</dt><dd>${esc(o.when)}</dd><dt>最后查询</dt><dd>${esc(o.queriedAt||'还未查询')}</dd></dl>${o.status==='paid'?note(o.kind==='subscription'?'订阅已生效，可回到“充值与订阅”查看额度。':'金额已记入这笔订单所属账号的余额。'):o.status==='failed'?note('本次付款没有完成，未增加余额。可以保留订单后返回充值页重新下单。','warn'):o.status==='timeout'?note('等待已超过 10 分钟，暂时无法确认是否到账。请先继续查询，避免重复付款。','warn'):o.status==='unknown'?note(o.queryError||'付款页已经关闭，订单仍保留。你可以继续查询确认到账状态。','warn'):note('付款完成后点击“查询到账状态”。结果以订单查询为准。可关闭此页，稍后从“我的订单”继续查询。')}${o.queryCount>0?`<p class="hint">已查询 ${o.queryCount} 次。${o.credited?'这笔订单已完成结算，重复查询不会重复到账。':''}</p>`:''}</div>`,footer:`<span class="spacer"></span><button class="btn btn-ghost" onclick="A.payClose()">${o.status==='paid'?'关闭':'关闭付款页'}</button><button class="btn btn-primary" data-testid="order-query" ${o.status==='querying'?'disabled':''} onclick="A.accountOrderQuery('${o.id}')">${o.status==='querying'?'查询中…':'查询到账状态'}</button>`});};
  DIALOGS.subscribe=p=>{const plan=plans.find(x=>x.id===p.plan)||plans[0],d=data(),f=S.form,count=d.purchases[plan.id]||0,limited=purchaseSlots(d,plan.id)>=plan.limit,mode=f.subpay||'balance',opts=availableChannels('subscription');return dialogShell({title:'购买「'+plan.name+'」',sub:`${usd(plan.price)} / ${plan.days} 天 · 总额度 ${usd(plan.quota)}`,body:`<p class="hint">从购买成功时开始计算有效期；到期或额度用完后，这条订阅停止提供额度。</p>${note(`每账号最多购买 ${plan.limit} 次，已购买 ${count} 次。`,limited?'warn':'info')}${field('付款方式',`<select class="input" onchange="F.set('subpay',this.value);render()"><option value="balance" ${mode==='balance'?'selected':''}>账户余额（美元）</option><option value="online" ${mode==='online'?'selected':''} ${opts.length?'':'disabled'}>在线支付${opts.length?'':'（暂无渠道）'}</option></select>`)}${mode==='balance'?`<p>账户余额（美元）：<strong>${usd(S.user.balance)}</strong></p>${S.user.balance<plan.price?note('余额不足，可改用在线支付，或先充值后继续。','warn'):''}`:field('支付渠道',`<div class="xm-pay-options">${channelOptions(f.channel||opts[0]?.id,'subscription',true)}</div>`)}${error(f)}`,footer:`<span class="spacer"></span><button class="btn btn-ghost" onclick="A.requestDialogClose('dismiss')">取消</button>${mode==='balance'&&S.user.balance<plan.price?`<button class="btn btn-secondary" onclick="A.closeDialog();A.openAccount('recharge')">去充值</button>`:''}<button class="btn btn-primary" data-testid="subscription-buy" ${limited||f.busy||(mode==='balance'&&S.user.balance<plan.price)?'disabled':''} onclick="A.subscribe('${plan.id}')">${limited?'已达购买上限':f.busy?'处理中…':mode==='balance'?'确认扣款并生效':'查看支付报价'}</button>`});};
  DIALOGS.transferReward=()=>dialogShell({title:'奖励转入账户余额',sub:'核对金额后转入当前账号。',body:`${field('转入金额（美元 USD）',`<input class="input" data-autofocus type="number" min="0.01" step="0.01" value="${esc(S.form.tr??S.user.reward)}" oninput="F.set('tr',this.value)">`,'当前可转入 '+usd(S.user.reward)+'。')}${error(S.form)}`,footer:`<span class="spacer"></span><button class="btn btn-ghost" onclick="A.requestDialogClose('dismiss')">取消</button><button class="btn btn-primary" onclick="A.transfer()">确认转入</button>`});
  function settle(record,o){if(o.credited)return; if(o.kind==='subscription'){record.subscriptions.push({id:uid('sub'),plan:o.planId,name:o.planName,quota:o.planQuota,used:0,startsAt:datePlus(0),expiresAt:datePlus(o.planDays),status:'active'});record.purchases[o.planId]=(record.purchases[o.planId]||0)+1;}else record.user.balance=roundUSD(record.user.balance+o.amountUSD);o.credited=true;o.settledAt=stamp();S.accounts=S.accounts.map(u=>u.name===record.user.name?{...record.user}:u);}
  function prepareQuote(owner,kind,amount,channel,plan){return {id:uid('quote'),owner,kind,amountUSD:kind==='subscription'?0:amount,channel:channel.id,way:channel.name,currency:channel.currency,originalAmount:amount,discount:0,checkoutAmount:amount,expiresAt:Date.now()+120000,planId:plan?.id,planName:plan?.name,planQuota:plan?.quota,planDays:plan?.days};}
  Object.assign(A,{
    keySave(id){const dialog=topDialog(),{key,f,values:v}=keyForm({id});if(!String(v.kname).trim()){f.err='给这把 Key 起个名字，方便以后找到。';render();return;}if(v.kquotaMode==='limited'&&(!Number.isFinite(Number(v.kquota))||Number(v.kquota)<=0)){f.err='请输入大于 0 的美元额度。';render();return;}if(v.kexpiryMode==='date'&&!/^\d{4}-\d{2}-\d{2}$/.test(v.kexpiry)){f.err='请选择完整的到期日期。';render();return;}const k=key||{id:uid('key'),full:'sk-demo-placeholder-'+uid('local'),masked:'sk-demo-****-'+sequence,usedUSD:0,show:false,created:datePlus(0),used:'从未',status:'active'};Object.assign(k,{name:v.kname.trim(),group:v.kgroup,quotaMode:v.kquotaMode,quota:v.kquotaMode==='limited'?Number(v.kquota):null,expiresAt:v.kexpiryMode==='date'?v.kexpiry:null,show:false});if(k.status!=='disabled')k.status=k.expiresAt&&k.expiresAt<datePlus(0)?'expired':k.quotaMode==='limited'&&k.usedUSD>=k.quota?'exhausted':'active';if(!key)data().keys.push(k);const parent=S.dialogs.find(x=>x.id===dialog.props.parentId);if(parent?.type==='config'&&!key){parent.form.key=k.id;parent.dirty=true;}saveCurrent();A.closeDialog();A.toast(key?'Key 已更新':'Key 已创建');},
    keyShow(id){const record=data(),k=record.keys.find(x=>x.id===id);if(!k||k.status!=='active')return;k.show=!k.show;const token=k.reveal=uid('reveal'),session=S;render();if(k.show)later(()=>{if(S!==session||k.reveal!==token)return;k.show=false;if(data()===record)render();},30000);},
    keyRevoke(id){const record=data(),k=record.keys.find(x=>x.id===id);if(!k)return;A.confirm({title:'停用「'+esc(k.name)+'」？',body:'使用这把 Key 的工具将无法继续调用。以后可以在这里重新启用。',ok:'确认停用',danger:true,run:()=>{k.status='disabled';k.show=false;if(data()===record)TOOL_ORDER.forEach(t=>{if(S.tools[t]?.key===id)S.tools[t].configured=false;});A.toast('Key 已停用，可在密钥页重新启用。');}});},
    keyEnable(id){const k=data().keys.find(x=>x.id===id);if(!k)return;k.status=k.expiresAt&&k.expiresAt<datePlus(0)?'expired':k.quotaMode==='limited'&&k.quota<=k.usedUSD?'exhausted':'active';render();A.toast(k.status==='active'?'Key 已启用，可在工具设置里重新选择。':k.status==='expired'?'有效期已过，请先延长到期日期。':'额度已用完，请先调整额度。',k.status==='active'?undefined:'warn');},
    accountTaskQuery(id){const record=data(),t=record.tasks.find(x=>x.id===id),session=S;if(!t||t.querying)return;t.querying=true;render();later(()=>{if(S!==session)return;t.querying=false;if(t.status==='queued')t.status='running';else if(t.status==='running'){t.status='done';t.dur='52 s';}if(data()===record)render();},600);},
    accountQuote(){const d=data(),f=pageDraft('recharge'),channel=availableChannels().find(x=>x.id===f.pay),amount=Number(f.amount),session=S;if(f.quoting)return;if(!channel){f.err='请选择当前可用的支付渠道。';render();return;}if(!Number.isFinite(amount)||amount<channel.minimum||amount>10000||Math.abs(Math.round(amount*100)-amount*100)>.000001){f.err=`到账金额应为 ${usd(channel.minimum)} 至 $10,000.00，最多两位小数。`;render();return;}f.quoting=true;f.err='';const selected={amount,channel:clone(channel),owner:d.user.name};render();later(()=>{if(S!==session)return;f.quoting=false;if(data()!==d)return;if(d.scenes.quote==='error'){f.err='暂时没有拿到报价，请重试。';render();return;}const quote=prepareQuote(selected.owner,'recharge',selected.amount,selected.channel);if(d.scenes.quote==='expired')quote.expiresAt=Date.now()-1;if(d.scenes.quote==='discount'){quote.discount=Number((quote.originalAmount*.1).toFixed(2));quote.checkoutAmount=Number((quote.originalAmount-quote.discount).toFixed(2));}A.dialog('rechargeConfirm',{quote});},550);},
    accountRefreshQuote(){const d=topDialog(),old=d?.props.quote;if(!old)return;const c=availableChannels(old.kind).find(x=>x.id===old.channel);if(!c){S.form.err='原渠道暂不可用，请返回重新选择。';render();return;}d.props.quote={...old,id:uid('quote'),expiresAt:Date.now()+120000};d.form.err='';d.initial=formFingerprint(d.form);render();},
    pay(){const dialog=topDialog(),q=dialog?.props.quote,f=S.form,session=S;if(!q||f.busy)return;if(S.user?.name!==q.owner){f.err='账号已变化，请返回并为当前账号重新获取报价。';render();return;}if(q.expiresAt<=Date.now()){f.err='报价已经失效，请重新获取。';render();return;}if(!availableChannels(q.kind).some(c=>c.id===q.channel)){f.err='该支付渠道暂不可用，请返回重新选择。';render();return;}const record=st().records[q.owner];if(q.kind==='subscription'&&purchaseSlots(record,q.planId)>=plans.find(p=>p.id===q.planId).limit){f.err='这个计划已达到购买次数上限。';render();return;}f.busy=true;render();later(()=>{if(S!==session)return;if(!S.dialogs.includes(dialog)){f.busy=false;return;}if(q.kind==='subscription'&&purchaseSlots(record,q.planId)>=plans.find(p=>p.id===q.planId).limit){f.busy=false;f.err='已有待付款订单或已达购买上限，请先到我的订单核实。';render();return;}const order={id:uid('XM'),owner:q.owner,when:stamp(),kind:q.kind,amountUSD:q.amountUSD,amount:q.amountUSD,currency:q.currency,checkoutAmount:q.checkoutAmount,way:q.way,channel:q.channel,quote:clone(q),status:'pending',queryCount:0,credited:false,createdAt:Date.now(),expected:st().paymentOutcome,planId:q.planId,planName:q.planName,planQuota:q.planQuota,planDays:q.planDays};record.orders.unshift(order);dialog.type='accountOrder';dialog.props={id:order.id};dialog.form={};dialog.initial=formFingerprint({});dialog.dirty=false;if(topDialog()===dialog)S.form=dialog.form;render();},450);},
    accountOrder(id){A.dialog('accountOrder',{id});},
    accountOrderQuery(id){const found=findOrder(id),session=S;if(!found)return;const {record,order:o}=found;if(o.status==='querying')return;const prior=o.status;o.status='querying';render();later(()=>{if(S!==session)return;o.queryCount++;o.queriedAt=stamp();if(o.credited)o.status='paid';else if(o.expected==='error'){o.status='unknown';o.queryError='暂时无法查询订单。余额尚未改变，请稍后继续查询。';}else if(o.expected==='timeout'||Date.now()-o.createdAt>600000&&o.expected!=='paid'){o.status='timeout';}else if(o.expected==='failed'){o.status='failed';}else if(o.expected==='pending'||o.queryCount===1&&prior==='pending'){o.status='pending';}else{o.status='paid';settle(record,o);}render();},650);},
    payClose(){const dialog=topDialog();if(dialog?.type==='accountOrder'){const found=findOrder(dialog.props.id);if(found&&!['paid','failed','timeout','querying'].includes(found.order.status))found.order.status='unknown';dialog.dirty=false;dialog.initial=formFingerprint(dialog.form);}A.closeDialog();},
    subscribe(planId){const plan=plans.find(p=>p.id===planId),record=data(),f=S.form;if(!plan||f.busy)return;if(purchaseSlots(record,plan.id)>=plan.limit){f.err='已达到这个计划的购买次数上限。';render();return;}if((f.subpay||'balance')==='online'){const c=availableChannels('subscription').find(c=>c.id===(f.channel||availableChannels('subscription')[0]?.id));if(!c){f.err='暂时没有可用的支付渠道。';render();return;}A.dialog('rechargeConfirm',{quote:prepareQuote(record.user.name,'subscription',plan.price,c,plan)});return;}if(record.user.balance<plan.price){f.err='账户余额不足，请先充值或选择在线支付。';render();return;}f.busy=true;const session=S,dialog=topDialog();render();later(()=>{if(S!==session||!S.dialogs.includes(dialog))return;if(record.user.balance<plan.price||purchaseSlots(record,plan.id)>=plan.limit){f.busy=false;f.err='余额或可购买次数发生变化，请检查后重试。';render();return;}record.user.balance=roundUSD(record.user.balance-plan.price);const o={id:uid('SUB'),owner:record.user.name,when:stamp(),kind:'subscription',way:'账户余额',currency:'USD',checkoutAmount:plan.price,amountUSD:0,status:'paid',queryCount:1,credited:false,planId:plan.id,planName:plan.name,planQuota:plan.quota,planDays:plan.days};record.orders.unshift(o);settle(record,o);A.closeDialog();render();A.toast('订阅已生效，可在我的订阅查看。');},500);},
    redeem(){const record=data(),f=pageDraft('recharge'),code=String(f.code||'').trim().toUpperCase();f.codeError=true;if(!code){f.codeMessage='请输入充值码。';render();return;}if(record.usedCodes.includes(code)){f.codeMessage='这个充值码已经使用过，请检查我的订单。';render();return;}if(code!=='XM-DEMO-20'){f.codeMessage='充值码无效或已过期，请检查后重试。';render();return;}f.codeError=false;f.codeMessage='充值码可为本账号增加 $20.00 余额。请在确认窗核对。';A.confirm({title:'兑换 $20.00 到账户余额？',body:`所属账号：${esc(record.user.name)}。兑换成功后可在我的订单查看记录。`,ok:'确认兑换',run:()=>{if(record.usedCodes.includes(code))return;record.usedCodes.push(code);const o={id:uid('CODE'),owner:record.user.name,when:stamp(),kind:'redeem',amountUSD:20,way:'充值码',currency:'USD',checkoutAmount:null,status:'paid',credited:false,queryCount:1};record.orders.unshift(o);settle(record,o);f.code='';f.codeMessage='兑换成功，$20.00 已到账。';render();}});},
    transfer(){const record=data(),amount=Number(S.form.tr??record.user.reward);if(!Number.isFinite(amount)||amount<=0||amount>record.user.reward||Math.abs(Math.round(amount*100)-amount*100)>.000001){S.form.err='转入金额须大于 0，不超过可转入奖励，且最多保留两位小数。';render();return;}record.user.reward=(Math.round(record.user.reward*100)-Math.round(amount*100))/100;const o={id:uid('REWARD'),owner:record.user.name,when:stamp(),kind:'reward',amountUSD:Number(amount.toFixed(2)),way:'邀请奖励',currency:'USD',checkoutAmount:null,status:'paid',credited:false,queryCount:1};record.orders.unshift(o);settle(record,o);A.closeDialog();A.toast('奖励已转入账户余额。');},
    deviceRevoke(id){const record=data(),device=record.devices.find(d=>String(d.id)===String(id));if(!device||device.current)return;A.confirm({title:'撤销这台设备的登录？',body:esc(device.name)+' 将退出登录，需要重新验证才能继续使用。',ok:'撤销登录',danger:true,run:()=>{record.devices=record.devices.filter(d=>String(d.id)!==String(id));if(data()===record)S.devices=record.devices;A.toast('这台设备的登录已撤销。');}});},
    accountRevokeOthers(){const record=data();A.confirm({title:'退出所有其他设备？',body:'其他浏览器和客户端需要重新登录，当前设备继续使用。',ok:'退出其他设备',run:()=>{record.devices=record.devices.filter(d=>d.current);if(data()===record)S.devices=record.devices;A.toast('其他设备已退出。');}});},
    accountCopyInvite(){const code=S.user?.invite;if(!code){A.toast('暂时没有可用邀请码。','warn');return;}if(typeof XM.copy==='function'){XM.copy(code);return;}A.dialog('accountInfo',{title:'复制邀请码',body:field('邀请码',`<input class="input mono" value="${esc(code)}" readonly onfocus="this.select()">`,'选中后按 '+(S.os==='mac'?'⌘C':'Ctrl+C')+' 复制。')});}
  });
  function pauseChat(record){if(!record?.chat)return;record.chat.convs.forEach(conv=>{if(conv.request){cancelConversationRequest(conv);conv.accountPaused=true;}});}
  function switchHook(previous,next){let result={ok:true,failed:[]};if(typeof XM.onAccountSwitched==='function'){try{result=XM.onAccountSwitched(previous,next)||result;}catch(_){result={ok:false,failed:['工具状态'],message:'账号已切换，部分工具状态未同步。请到首页检查后再打开。'};}}return result;}
  XM.authComplete = function(user,options={}){const store=st(),previous=options.previousUser||S.user,old=store.records[store.active];if(old){saveCurrent();pauseChat(old);}let record=store.records[user.name];if(!record){record=store.records[user.name]=makeData({...user,balance:0,reward:0,usedMonth:0},false,true);}record.expired=false;record.user={...record.user,name:user.name,display:user.display||record.user.display,email:user.email||record.user.email};bind(record);store.active=user.name;store.switching=null;if(!S.accounts.some(a=>a.name===user.name))S.accounts.push({...record.user});S.accounts=S.accounts.map(a=>a.name===user.name?{...record.user}:a);if(previous?.name!==user.name){const result=switchHook(previous,record.user);record.switchMessage=result.ok===false||result.failed?.length?(result.message||'部分工具尚未完成账号同步。请到首页检查后再打开。'):'';}return record.user;};
  Object.assign(A,{
    switchAccount(index){const store=st(),target=typeof index==='number'?S.accounts[index]?.name:index,record=store.records[target];S.accPop=null;if(!record||target===S.user?.name){render();return;}if(store.switching)return;const previous=S.user,session=S;saveCurrent();store.switching=target;render();later(()=>{if(S!==session)return;store.switching=null;if(record.expired||store.switchOutcome==='expired'){record.expired=true;A.dialog('accountSwitchExpired',{target});return;}pauseChat(store.records[store.active]);store.active=target;bind(record);S.dialogs=[];S.pageForm=pageDraft(S.accountTab||'overview');S.form=S.pageForm;S.drawer=null;S.view='account';let result=switchHook(previous,record.user);if(store.switchOutcome==='partial')result={ok:false,failed:['Claude Code'],message:'账号已经切换，Claude Code 的账号尚未同步。请在首页检查配置后再打开。'};record.switchMessage=result.ok===false||result.failed?.length?(result.message||'部分工具尚未完成账号同步。请到首页检查后再打开。'):'';render();A.toast('已切换到 '+record.user.display+(record.switchMessage?'，请检查工具同步结果。':''),record.switchMessage?'warn':undefined);},650);},
    accountRelogin(target){A.closeDialog();A.dialog('login');S.form.acc=target;S.form.addAccount=true;S.form.accountTarget=target;topDialog().initial=formFingerprint(S.form);render();},
    logout(){const store=st(),record=data();A.confirm({title:'退出当前账号？',body:'当前设备需要重新登录。账户资料和订单会保留，进行中的订单仍可在登录后查询。',ok:'退出登录',danger:true,run:()=>{saveCurrent();pauseChat(record);if(record)record.expired=true;S.user=null;store.active=null;for(const key of ['keys','orders','usage','tasks','devices'])S[key]=[];S.chat={...S.chat,convs:[],active:null,draft:''};S.dialogs=[];S.pageForm={};S.form={};S.view='welcome';switchHook(record?.user,null);render();A.toast('已退出当前账号。');}});}
  });
  DIALOGS.accountSwitchExpired=p=>dialogShell({title:'这个账号需要重新登录',body:`${note('暂时无法切换到 '+esc(p.target)+'。当前账号仍然保持登录，资料和输入没有变化。','warn')}<p class="hint">重新登录成功后再切换，或者先返回继续使用当前账号。</p>`,footer:`${closeBtn}<button class="btn btn-primary" onclick="A.accountRelogin(${esc(JSON.stringify(p.target))})">重新登录</button>`});
  const previousDeepLink=A.deepLink;
  A.deepLink=function(url){if(!String(url).startsWith('xingmang://pay'))return previousDeepLink(url);let id='';try{id=new URL(url).searchParams.get('order')||'';}catch(_){}const found=findOrder(id);if(!found){A.toast('没有找到对应订单，请到“我的订单”选择需要查询的订单。','warn');return;}A.accountOrder(id);A.accountOrderQuery(id);};
  XM.accountVersion='3.0.0';XM.accountStore=st;XM.accountData=data;XM.keyUsable=k=>!!k&&k.status==='active'&&(!k.expiresAt||k.expiresAt>=datePlus(0))&&(k.quotaMode!=='limited'||k.quota>k.usedUSD);
  XM.accountCharge=function(amountUSD,ownerName=S.user?.name,options={}){const record=st().records[ownerName],amount=Number(amountUSD);if(!record||!Number.isFinite(amount)||amount<=0)return {ok:false,error:'暂时无法读取账户额度，请重新登录后再试。'};const active=record.subscriptions.filter(s=>s.status==='active'&&(!s.expiresAt||s.expiresAt>=datePlus(0))&&s.quota>s.used);const subscriptionLeft=active.reduce((n,s)=>n+s.quota-s.used,0),pref=record.preference||'subscription_first',balance=record.user.balance??0;const available=pref==='balance_only'?balance:pref==='subscription_only'?subscriptionLeft:balance+subscriptionLeft;if(available+1e-8<amount)return {ok:false,error:pref==='subscription_only'?'订阅额度不足。请购买订阅或更改扣费偏好。':pref==='balance_only'?'账户余额不足。请充值或更改扣费偏好。':'可用额度不足。请充值或购买订阅后再试。'};let remaining=amount,fromBalance=0,fromSubscription=0;const spendBalance=()=>{const take=Math.min(remaining,balance);fromBalance=take;remaining=roundUSD(remaining-take);};const spendSubscription=()=>{const take=Math.min(remaining,subscriptionLeft);fromSubscription=take;remaining=roundUSD(remaining-take);};if(pref==='balance_first'||pref==='balance_only'){spendBalance();if(pref!=='balance_only')spendSubscription();}else{spendSubscription();if(pref!=='subscription_only')spendBalance();}const result={ok:true,amountUSD:amount,balanceUSD:roundUSD(fromBalance),subscriptionUSD:roundUSD(fromSubscription),billing:fromSubscription>0?(fromBalance>0?'mixed':'subscription'):'balance'};if(options.preview)return result;record.user.balance=roundUSD(balance-fromBalance);let subSpend=fromSubscription;for(const sub of active){const take=Math.min(subSpend,sub.quota-sub.used);sub.used=roundUSD(sub.used+take);subSpend=roundUSD(subSpend-take);if(subSpend<=0)break;}S.accounts=S.accounts.map(u=>u.name===ownerName?{...record.user}:u);return result;};
  const chargeAccount = XM.accountCharge;
  XM.accountCharge = function(amountUSD,ownerName=S.user?.name,options={}){const result=chargeAccount(amountUSD,ownerName,options);result.source=result.billing||null;result.message=result.ok?(result.source==='subscription'?'已使用订阅额度':result.source==='mixed'?'已使用订阅额度与账户余额':'已使用账户余额'):result.error;if(result.ok&&!options.preview){const record=st().records[ownerName];record.charges ||= [];record.charges.push({id:uid('charge'),owner:ownerName,when:stamp(),amountUSD:result.amountUSD,balanceUSD:result.balanceUSD,subscriptionUSD:result.subscriptionUSD,source:result.source});}return result;};
  XM.accountCanCharge = (amountUSD,ownerName=S.user?.name) => XM.accountCharge(amountUSD,ownerName,{preview:true});
  st();
})();
