/* Offline browser checks for the canvas UI prototype, not native-window compatibility. */
const assert=require('node:assert/strict');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const {chromium}=require(process.env.XINGMANG_PLAYWRIGHT_MODULE||'playwright');
let browser;
(async()=>{
  const html=process.argv.find(a=>a.endsWith('.html'))||path.resolve(__dirname,'../integration-preview.html');
  browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1640,height:1100},acceptDownloads:true});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route(/^https?:/,r=>r.abort());
  await page.goto(pathToFileURL(html).href);
  if(!await page.evaluate(()=>typeof A.canvasScenario==='function')){
    await page.addStyleTag({path:path.join(__dirname,'45-canvas.css')});
    await page.addScriptTag({path:path.join(__dirname,'45-canvas.js')});
  }
  const get=()=>page.evaluate(()=>JSON.parse(JSON.stringify(S.canvas45)));
  const phase=(kind,value)=>page.waitForFunction(([k,v])=>S.canvas45[k].phase===v,[kind,value]);
  await page.evaluate(()=>{S.coach=null;S.update.dismissed=true;A.openCanvas();});
  assert(await page.getByRole('heading',{name:'把想法连成作品'}).isVisible());
  await page.getByTestId('canvas-demo').click();
  assert.equal((await get()).project.nodes.length,4);
  await page.locator('#cx-text').fill('我修改的画面：蓝色山野和温暖落日');
  assert.equal((await get()).dirty,true);
  assert.equal(await page.locator('#cx-text').inputValue(),'我修改的画面：蓝色山野和温暖落日');
  await page.getByTestId('canvas-save').click();
  assert.equal((await get()).save.phase,'saving');
  assert(await page.getByTestId('canvas-add-text').isDisabled());
  await phase('save','saved');
  assert.equal((await get()).dirty,false);
  await page.getByTestId('canvas-run').click();
  assert.equal((await get()).run.phase,'running');
  assert(await page.getByTestId('canvas-stop').isVisible());
  await phase('run','done');
  await page.getByTestId('canvas-view-result').click();
  assert(await page.getByRole('dialog',{name:'运行结果 · 本地演示'}).isVisible());
  assert(await page.locator('.cx-art.large').isVisible());
  assert.match(await page.locator('.cx-result-description').textContent(),/我修改的画面/);
  await page.keyboard.press('Escape');
  assert.equal((await get()).modal,null);
  assert(await page.locator('.cx-window').isVisible());
  await page.locator('#cx-text').fill('');
  assert.equal((await get()).run.phase,'idle');
  assert.equal(await page.getByTestId('canvas-view-result').count(),0);
  await page.getByTestId('canvas-run').click();
  assert.equal((await get()).run.phase,'invalid');
  assert.match(await page.locator('.cx-run-panel').textContent(),/还没有文字/);
  await page.locator('#cx-text').fill('星空山野');
  await page.evaluate(()=>A.canvasScenario('save','failure'));
  await page.getByTestId('canvas-save').click();await phase('save','failed');
  await page.getByRole('button',{name:'关闭画布窗口',exact:true}).click();
  assert.equal((await get()).modal.type,'unsaved');
  assert(await page.getByRole('dialog',{name:'还有修改没有保存'}).isVisible());
  assert.equal(await page.locator('.cx-content').evaluate(e=>e.inert),true);
  await page.getByRole('button',{name:'保存并继续',exact:true}).click();
  await page.waitForFunction(()=>!S.canvasOpen);
  assert(await page.locator('#win').isVisible());
  assert(await page.locator('#main').isVisible());
  await page.evaluate(()=>A.openCanvas());
  assert.equal((await get()).project.nodes[0].text,'星空山野');
  await page.getByTestId('canvas-add-image').click();
  let c=await get(),added=c.selected;assert.equal(c.project.nodes.length,5);
  await page.locator('#cx-name').fill('待删除图片');
  await page.getByTestId('canvas-delete').click();
  assert.equal((await get()).modal.type,'delete');
  await page.getByRole('dialog').getByRole('button',{name:'删除节点',exact:true}).click();
  assert.equal((await get()).project.nodes.length,4);
  await page.getByRole('button',{name:'撤销',exact:true}).click();
  assert.equal((await get()).project.nodes.length,5);
  assert((await get()).project.nodes.some(n=>n.id===added));
  await page.evaluate(()=>{A.canvasDelete();A.canvasDeleteConfirm();A.canvasSelect('n1');});
  const x=(await get()).project.nodes[0].x;
  await page.locator('#cx-node-n1').focus();await page.keyboard.press('ArrowRight');
  assert.equal((await get()).project.nodes[0].x,x+20);
  const h=await page.locator('#cx-node-n1 .cx-node-head').boundingBox();
  await page.mouse.move(h.x+h.width/2,h.y+h.height/2);await page.mouse.down();await page.mouse.move(h.x+h.width/2+35,h.y+h.height/2+24,{steps:5});await page.mouse.up();
  assert((await get()).project.nodes[0].x>x+20);
  await page.evaluate(()=>{A.canvasRemoveEdge(0);A.canvasBeginLink('n1');});
  await page.locator('#cx-link-target').selectOption('n2');
  await page.getByRole('button',{name:'连接',exact:true}).click();
  assert((await get()).project.edges.some(e=>e[0]==='n1'&&e[1]==='n2'));
  await page.evaluate(()=>{A.canvasBeginLink('n1');S.canvas45.target='n2';A.canvasConnect();});
  assert.match((await get()).notice,/已经连接/);
  await page.evaluate(()=>{A.canvasBeginLink('n3');S.canvas45.target='n2';A.canvasConnect();});
  assert.match((await get()).notice,/循环/);
  await page.evaluate(()=>A.canvasToggleLink());
  const zoom=(await get()).zoom;await page.getByRole('button',{name:'放大画布',exact:true}).click();assert((await get()).zoom>zoom);
  await page.getByRole('button',{name:'适应',exact:true}).click();
  const downloadEvent=page.waitForEvent('download');
  await page.getByRole('button',{name:'导出演示',exact:true}).click();
  const download=await downloadEvent;assert.equal(download.suggestedFilename(),'xingmang-canvas-demo.json');
  assert.match((await get()).notice,/已下载演示 JSON/);
  await page.getByRole('button',{name:'导入演示',exact:true}).click();
  await page.locator('#cx-import').fill('{bad json');
  await page.getByRole('button',{name:'导入为新项目',exact:true}).click();
  assert(await page.locator('.cx-error').isVisible());
  await page.getByRole('button',{name:'填入内置示例',exact:true}).click();
  await page.getByRole('button',{name:'导入为新项目',exact:true}).click();
  assert.equal((await get()).modal.type,'unsaved');
  await page.getByRole('button',{name:'放弃修改',exact:true}).click();
  assert.match((await get()).project.name,/导入/);
  assert.equal((await get()).project.nodes.length,4);
  await page.getByRole('button',{name:'所有项目',exact:true}).click();
  await page.getByTestId('canvas-new').click();
  await page.getByRole('button',{name:'创建项目',exact:true}).click();
  assert.match(await page.locator('.cx-error').textContent(),/名称/);
  await page.locator('#cx-new-name').fill('新手的第一张画面');
  await page.getByRole('button',{name:'创建项目',exact:true}).click();
  assert.equal((await get()).project.nodes.length,0);
  await page.getByTestId('canvas-run').click();assert.equal((await get()).run.phase,'invalid');
  await page.getByTestId('canvas-add-text').click();await page.locator('#cx-text').fill('一个简单的想法');
  await page.getByRole('button',{name:'关闭画布窗口',exact:true}).click();
  await page.getByRole('button',{name:'取消',exact:true}).click();assert(await page.locator('.cx-window').isVisible());
  await page.getByRole('button',{name:'关闭画布窗口',exact:true}).click();
  await page.getByRole('button',{name:'放弃修改',exact:true}).click();
  await page.evaluate(()=>A.canvasScenario('demo'));
  await page.evaluate(()=>A.canvasScenario('run','failure'));
  await page.getByTestId('canvas-run').click();await phase('run','failed');
  await page.getByRole('button',{name:'重新运行',exact:true}).click();
  await page.getByTestId('canvas-stop').click();
  assert.equal((await get()).run.phase,'stopped');
  await page.waitForTimeout(2600);assert.equal((await get()).run.phase,'stopped');
  await page.getByRole('button',{name:'重新运行',exact:true}).click();
  await page.getByRole('button',{name:'关闭画布窗口',exact:true}).click();
  assert.equal((await get()).modal.type,'running');
  await page.getByRole('button',{name:'停止并继续',exact:true}).click();
  assert.equal(await page.evaluate(()=>S.canvasOpen),false);
  await page.evaluate(()=>A.openCanvas());
  await page.waitForTimeout(2600);assert.equal((await get()).run.phase,'stopped');
  for(const os of ['win','mac','linux']){
    await page.evaluate(os=>{S.os=os;S.canvas45.selected='n1';render();},os);
    assert.equal(await page.locator('.cx-window').getAttribute('data-canvas-os'),os);
    assert.equal(await page.locator('.cx-mac-close').count(),os==='mac'?1:0);
    await page.locator('#cx-text').fill('平台快捷键 '+os);
    await page.keyboard.press(os==='mac'?'Meta+s':'Control+s');await phase('save','saved');
    await page.keyboard.press(os==='mac'?'Meta+k':'Control+k');assert.equal(await page.evaluate(()=>S.palette),null);
    await page.keyboard.press(os==='mac'?'Control+k':'Meta+k');assert.equal(await page.evaluate(()=>S.palette),null);
    await page.locator('.cx-window button').first().focus();await page.keyboard.press('Shift+Tab');
    assert.equal(await page.evaluate(()=>Boolean(document.activeElement.closest('.cx-window'))),true);
    await page.locator('#cx-node-n1').focus();await page.keyboard.press('ArrowRight');
    await page.keyboard.press(os==='mac'?'Meta+z':'Control+z');
    await page.keyboard.press(os==='mac'?'Meta+w':'Control+w');
    assert.equal((await get()).modal.type,'unsaved');
    await page.keyboard.press('Escape');assert.equal((await get()).modal,null);
  }
  await page.evaluate(()=>{S.canvasCloseCallbackCount=0;A.canvasCloseThen(()=>S.canvasCloseCallbackCount++);});
  assert.equal((await get()).modal.type,'unsaved');
  await page.getByRole('button',{name:'取消',exact:true}).click();
  await page.evaluate(()=>A.closeCanvas());
  await page.getByRole('button',{name:'放弃修改',exact:true}).click();
  assert.equal(await page.evaluate(()=>S.canvasCloseCallbackCount),0);
  await page.evaluate(()=>{A.openCanvas();A.canvasSelect('n1');});
  await page.locator('#cx-text').fill('主窗口关闭保护');
  await page.evaluate(()=>A.canvasCloseThen(()=>S.canvasCloseCallbackCount++));
  await page.getByRole('button',{name:'保存并继续',exact:true}).click();
  await page.waitForFunction(()=>!S.canvasOpen);
  assert.equal(await page.evaluate(()=>S.canvasCloseCallbackCount),1);
  await page.evaluate(()=>{A.openCanvas();A.canvasSelect('n1');});
  await page.locator('#cx-text').fill('取消保存并继续');
  await page.evaluate(()=>A.canvasCloseThen(()=>S.canvasCloseCallbackCount++));
  await page.getByRole('button',{name:'保存并继续',exact:true}).click();
  await page.getByRole('button',{name:'取消',exact:true}).click();
  await page.waitForTimeout(850);
  assert.equal(await page.evaluate(()=>S.canvasCloseCallbackCount),1);
  assert.equal(await page.evaluate(()=>S.canvasOpen),true);
  assert.equal((await get()).save.phase,'dirty');
  await page.evaluate(()=>{A.canvasSave();S=freshState(true);S.coach=null;render();});
  await page.waitForTimeout(900);assert.equal(await page.evaluate(()=>Boolean(S.canvas45)),false);
  await page.evaluate(()=>A.canvasScenario('demo'));
  await page.getByTestId('canvas-run').click();
  await page.evaluate(()=>{S=freshState(true);S.coach=null;render();});
  await page.waitForTimeout(2600);assert.equal(await page.evaluate(()=>Boolean(S.canvas45)),false);
  await page.evaluate(()=>{S.os='win';S.theme='dark';A.canvasScenario('demo');});
  await page.getByTestId('canvas-run').click();await phase('run','done');
  const windowBox=await page.locator('.cx-window').boundingBox(),closeBox=await page.getByRole('button',{name:'关闭画布窗口',exact:true}).boundingBox();
  assert(closeBox.x>windowBox.x+windowBox.width*.85,'Windows close control stays on the right');
  if(process.argv.includes('--screenshot-base64'))console.log('SCREENSHOT:'+Buffer.from(await page.locator('.cx-window').screenshot()).toString('base64'));
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({ok:true,checks:'overview/create, edit, save/retry/close, validation/run/stop/results, graph links/delete/undo/drag, zoom/fit, JSON import/download, 3 OS shortcuts, reset stale callbacks',browserErrors:errors.length}));
  await browser.close();
})().catch(async error=>{console.error(error);if(browser)await browser.close();process.exitCode=1;});
