/* Bounded browser checks for offline maintenance interactions. No live service calls. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.XINGMANG_PLAYWRIGHT_MODULE||'playwright');
let browser;
(async()=>{
  const root=path.resolve(__dirname,'../..'),checks=[],errors=[],requests=[];
  const template=fs.readFileSync(path.join(root,'work/integration-preview.html'),'utf8');
  const base=fs.readFileSync(path.join(root,'work/prototype.js'),'utf8').replace(/initProto\(\);\s*$/,'');
  const modules=['00-runtime','40-tools','50-platform','80-maintenance'];
  const js=base+'\n'+modules.map(n=>fs.readFileSync(path.join(__dirname,n+'.js'),'utf8')).join('\n')+'\ninitProto();render();';
  const css=fs.readFileSync(path.join(root,'work/prototype.css'),'utf8')+'\n'+modules.map(n=>fs.readFileSync(path.join(__dirname,n+'.css'),'utf8')).join('\n');
  const html=template.replace(/<style>[\s\S]*?<\/style>/,()=>'<style>'+css+'</style>').replace(/<script>[\s\S]*?<\/script>/,()=>'<script>'+js+'</script>');
  browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1640,height:1100}});
  page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});await page.route(/^https?:/,r=>r.abort());
  await page.setContent(html,{waitUntil:'domcontentloaded'});
  const check=(name,v)=>{assert.ok(v,name);checks.push(name);};
  const wait=ms=>page.waitForTimeout(ms);
  const reset=()=>page.evaluate(()=>{S=freshState(true);S.update.dismissed=true;S.update.dismissedOk=true;S.update.dismissedDl=true;S.os='win';A.go('home');});
  await reset();
  await page.evaluate(()=>{for(const id of TOOL_ORDER)S.tools[id].installed=id==='codexDesktop';S.env.node=null;S.env.npm=null;A.go('health');A.healthRun();});await page.waitForFunction(()=>S.health.status==='done');
  check('desktop only does not report optional Node as failure',await page.evaluate(()=>S.health.status==='done'&&S.health.items.find(x=>x.k==='node').st==='optional'&&!S.health.items.some(x=>x.k==='gemini')));
  await page.evaluate(()=>{S.tools.codex.installed=true;A.healthRun();});await page.waitForFunction(()=>S.health.status==='done');
  check('desktop remains usable while installed CLI gets runtime action',await page.evaluate(()=>S.health.items.find(x=>x.k==='node').st==='optional'&&S.health.items.find(x=>x.k==='codex').st==='warn'&&S.health.items.find(x=>x.k==='codex').target==='maintenance'));
  await page.evaluate(()=>A.healthRun());await wait(120);await page.evaluate(()=>A.healthCancel());await wait(1500);
  check('cancelled diagnostic never finishes later',await page.evaluate(()=>S.health.status==='cancelled'));
  await page.evaluate(()=>{A.maintenanceScenario('health','failed');A.healthRun();});await page.waitForFunction(()=>S.health.status==='done');await page.evaluate(()=>A.healthFix('service'));
  check('diagnostic repair deep-links to network group',await page.evaluate(()=>S.page==='settings'&&S.settingsTab==='网络'));
  check('repair destination has return action',await page.locator('.xm-health-return').count()===1);await page.locator('.xm-health-return button').click();
  check('return action preserves diagnostic result',await page.evaluate(()=>S.page==='health'&&S.health.status==='done'));
  await page.evaluate(()=>{S.logs.unshift({t:'刚刚',lv:'error',msg:'Demo secret sk-demoSensitive123456',d:'C:\\Users\\person\\project api_key=otherSecret123 person@example.com 127.0.0.1'});A.reportPreview();});
  const report=await page.locator('#xm-report-text').inputValue();check('report masks tokens user paths emails and addresses',!['sk-demoSensitive123456','person','otherSecret123','127.0.0.1'].some(x=>report.includes(x)));
  await page.evaluate(()=>A.maintenanceScenario('clipboard','failed'));await page.evaluate(()=>A.reportCopy());
  check('clipboard failure provides selectable report',await page.evaluate(()=>XM.state('maintenance').copy==='failed'&&document.getElementById('xm-report-text').selectionEnd>0));
  await page.evaluate(()=>{A.closeDialog();A.go('feedback');S.logFilter='error';render();});
  check('feedback level filter only displays errors',await page.locator('.log .lv:not(.error)').count()===0);await page.evaluate(()=>A.search('feedback','no-matching-event-xyz'));
  check('feedback selected filter has visual state',await page.locator('.toolbar .segment .on').count()===1);
  check('feedback empty search offers reset',await page.locator('#content').innerText().then(t=>t.includes('没有匹配的日志')));
  await page.evaluate(()=>{A.search('feedback','');A.logsClear();});check('clear logs requires confirmation',await page.evaluate(()=>S.logs.length>0&&topDialog().type==='confirm'));await page.evaluate(()=>A.confirmRun());
  check('confirmed clear has empty state',await page.evaluate(()=>S.logs.length===0));
  await reset();await page.evaluate(()=>{A.go('updates');A.updateCheck();A.updateCancel();});await wait(850);check('checking cancellation stays cancelled',await page.evaluate(()=>S.update.phase==='cancelled'));
  await page.evaluate(()=>{A.maintenanceScenario('update','checkFailed');A.updateCheck();});await page.waitForFunction(()=>S.update.phase==='failed');
  check('failed-check notice retries check instead of downloading',await page.locator('[data-maintenance-update] .nacts button').first().getAttribute('onclick').then(v=>v==='A.updateRetry()'));
  await page.evaluate(()=>{A.maintenanceScenario('update','downloadFailed');A.updateDownload();});await wait(750);check('download failure has retry path',await page.evaluate(()=>S.update.phase==='failed'&&S.update.failedAt==='download'));await page.evaluate(()=>A.updateRetry());await wait(750);
  check('repeated update failure offers manual install',await page.locator('#content').innerText().then(t=>t.includes('已连续失败')&&t.includes('手动安装说明')));
  await page.evaluate(()=>{A.maintenanceScenario('update','ready');A.updateDownload();});await page.waitForFunction(()=>S.update.phase==='downloaded');
  check('download completes without auto-install',await page.evaluate(()=>S.update.phase==='downloaded'&&S.update.current==='0.1.31'));
  check('ready notice asks user to save tasks without signed guarantee',await page.locator('.notice').allTextContents().then(a=>!a.join(' ').includes('任务不会丢')&&!a.join(' ').includes('签名')&&a.join(' ').includes('保存')));
  await page.evaluate(()=>A.updateInstall());check('install requires saved-tasks confirmation',await page.locator('.dialog button').filter({hasText:'确认重启并安装'}).isDisabled());
  await page.evaluate(()=>{F.set('savedTasks',true);render();A.updateConfirmInstall();});check('explicit installation confirmation changes version',await page.evaluate(()=>S.update.phase==='latest'&&S.update.current==='0.1.32'));
  for(const phase of ['idle','checking','latest','available','downloading','downloaded','failed','cancelled']){await page.evaluate(p=>{A.maintenanceScenario('update',p);A.go('updates');},phase);const text=await page.locator('[data-testid="maintenance-update-status"]').innerText();check('footer projects update phase '+phase,phase==='latest'?text.includes('最新'):!text.includes('最新'));}
  await reset();await page.evaluate(()=>A.go('settings'));
  for(const group of ['外观','启动与关闭','工具','网络','通知','账号','隐私与数据','关于']){await page.evaluate(g=>A.settingSection(g),group);check('one panel for settings '+group,await page.locator('#settings-panel').count()===1&&await page.locator('#settings-panel > h2').innerText()===group);}
  await page.evaluate(()=>A.settingSection('外观'));await page.locator('#settings-tab-0').focus();await page.keyboard.press('ArrowDown');check('settings keyboard navigation stays intact',await page.evaluate(()=>S.settingsTab==='启动与关闭'));
  await page.evaluate(()=>{A.maintenanceScenario('settings','failed');A.setting('autostart',true);});check('setting value previews during save',await page.evaluate(()=>S.settings.autostart===true&&XM.state('maintenance').save.autostart.phase==='saving'));await wait(550);
  check('failed setting reverts old value',await page.evaluate(()=>S.settings.autostart===false&&XM.state('maintenance').save.autostart.phase==='failed'));
  await page.evaluate(()=>{A.maintenanceScenario('settings','ready');A.settingRetry('autostart');});await wait(550);check('setting retry commits attempted value',await page.evaluate(()=>S.settings.autostart===true&&XM.state('maintenance').save.autostart.phase==='saved'));
  await page.evaluate(()=>{A.settingSection('外观');A.setting('reduceMotion',true);});await wait(550);check('reduce motion changes computed CSS',await page.locator('#settings-tab-0').evaluate(e=>getComputedStyle(e).transitionDuration==='0s'));
  check('English is not presented as unsupported selectable option',await page.locator('#settings-panel option').allTextContents().then(a=>!a.includes('English')));
  await page.evaluate(()=>{A.settingSection('网络');S.settings.proxy='manual';S.settings.proxyUrl='http://127.0.0.1:7890';XM.state('maintenance').proxyDraft='invalid';A.setting('proxyUrl','invalid');A.settingsProxyTest();});await wait(650);
  check('proxy test uses visible restored address after invalid input',await page.evaluate(()=>XM.state('maintenance').network==='done'));
  await page.evaluate(()=>{XM.setPlatformVersion('ubuntu2404');A.settingSection('启动与关闭');});check('Linux no-tray keeps tray control disabled',await page.locator('#settings-panel button').filter({hasText:'缩到托盘'}).isDisabled());
  await reset();await page.evaluate(()=>{A.go('settings');A.settingSection('隐私与数据');});check('migration starts unexecuted',await page.evaluate(()=>XM.state('maintenance').migration.phase==='idle'));
  await page.evaluate(()=>{A.dialog('xmMigration');A.settingsMigrate();A.settingsDataCancel('migration');A.dialog('xmMigration');});await wait(850);
  check('cancelled migration cannot close later dialog',await page.evaluate(()=>XM.state('maintenance').migration.phase==='cancelled'&&topDialog()?.type==='xmMigration'));await page.evaluate(()=>A.closeDialog());
  await page.evaluate(()=>{A.dialog('xmMigration');A.settingsMigrate();});await wait(850);check('migration keeps before snapshot',await page.evaluate(()=>XM.state('maintenance').migration.phase==='done'&&!!XM.state('maintenance').migration.snapshot));
  await page.evaluate(()=>{S.settings.workdir='new-version-projects';A.maintenanceScenario('rollback','failed');A.dialog('xmRollback');A.settingsRollback();});await wait(850);
  check('failed rollback preserves current value and both snapshots',await page.evaluate(()=>{const m=XM.state('maintenance').migration;return m.phase==='rollbackFailed'&&S.settings.workdir==='new-version-projects'&&m.newSnapshot.settings.workdir==='new-version-projects'&&!!m.snapshot;}));
  await page.evaluate(()=>{A.maintenanceScenario('rollback','ready');A.dialog('xmRollback');A.settingsRollback();});await wait(850);check('successful rollback retains newer snapshot',await page.evaluate(()=>{const m=XM.state('maintenance').migration;return m.phase==='rolledBack'&&S.settings.workdir===m.snapshot.settings.workdir&&m.newSnapshot.settings.workdir==='new-version-projects';}));
  await page.evaluate(()=>{A.dialog('xmRollback');A.settingsRollback();});await wait(850);check('repeated completed rollback cannot replace newer snapshot',await page.evaluate(()=>XM.state('maintenance').migration.newSnapshot.settings.workdir==='new-version-projects'));await page.evaluate(()=>A.closeDialog());
  await reset();await page.evaluate(()=>{A.dialog('xmMigration');A.settingsMigrate();});await wait(850);
  await page.evaluate(()=>{S.settings.workdir='new1';A.dialog('xmRollback');A.settingsRollback();A.settingsDataCancel('rollback');S.settings.workdir='new2';A.dialog('xmRollback');A.settingsRollback();A.setting('workdir','late-save');});await wait(1000);
  check('cancel-retry retains every newer snapshot and blocks concurrent settings',await page.evaluate(()=>{const m=XM.state('maintenance').migration;return m.phase==='rolledBack'&&S.settings.workdir===m.snapshot.settings.workdir&&m.newSnapshots.some(s=>s.settings.workdir==='new1')&&m.newSnapshots.some(s=>s.settings.workdir==='new2');}));
  for(const id of ['win11','mac15','ubuntu2404']){await page.evaluate(id=>{XM.setPlatformVersion(id);S.q.tutorial='';A.go('tutorial','first');},id);const text=await page.locator('#content').innerText();check('tutorial follows platform '+id,id==='ubuntu2404'?text.includes('先准备命令行工具'):text.includes('先准备 Codex 桌面端'));}
  check('no script errors',errors.length===0);check('no outgoing HTTP requests',requests.length===0);
  console.log(JSON.stringify({passed:checks.length,checks,errors,requests},null,2));await browser.close();
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1;});
