const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const path = require('node:path')
const { test } = require('node:test')
const YAML = require('yaml')
const { buildOfficialPackageMatrix } = require('./cos-chatgpt-platform-matrix.cjs')

test('all platforms become four Windows and macOS sequential independent jobs and group recovery stays within those identities', () => {
  const all = buildOfficialPackageMatrix()
  assert.deepEqual(all.include.map(item => item.platform), ['windows-x64', 'windows-arm64', 'macos-arm64', 'macos-x64'])
  for (const group of ['windows', 'macos']) assert.ok(buildOfficialPackageMatrix(group).include.every(item => all.include.some(entry => entry.platform === item.platform) && item.platform.startsWith(group)))
  for (const { platform } of all.include) assert.deepEqual(buildOfficialPackageMatrix(platform), { include: [{ platform }] })
  for (const value of ['linux', 'linux-deb-x64', 'linux-deb-arm64', 'linux-rpm-x64', 'linux-rpm-arm64', 'https://evil.invalid', 'windows-x64,linux-rpm-x64', '../escape', 'constructor', null, {}]) assert.throws(() => buildOfficialPackageMatrix(value))
})

test('protected workflow serializes jobs under its existing group and requires every selected job to succeed', async () => {
  const text = await fs.readFile(path.join(__dirname, '../.github/workflows/sync-chatgpt-official-cos.yml'), 'utf8')
  const workflow = YAML.parse(text)
  assert.equal(workflow.concurrency.group, 'cos-chatgpt-official-publish')
  assert.equal(workflow.concurrency['cancel-in-progress'], false)
  assert.equal(workflow.jobs.select.outputs.matrix, '${{ steps.platforms.outputs.matrix }}')
  assert.equal(workflow.jobs.sync.needs, 'select')
  assert.equal(workflow.jobs.sync.strategy['max-parallel'], 1)
  assert.equal(workflow.jobs.sync.strategy['fail-fast'], false)
  assert.equal(workflow.jobs.sync.strategy.matrix, '${{ fromJSON(needs.select.outputs.matrix) }}')
  assert.equal(workflow.jobs.sync['runs-on'], 'windows-latest')
  assert.equal(workflow.jobs.sync['timeout-minutes'], 90)
  assert.equal(workflow.jobs.sync.environment, 'cos-sync')
  assert.equal(workflow.jobs.sync['continue-on-error'], undefined)
  for (const job of [workflow.jobs.select, workflow.jobs.sync]) assert.equal(job.if, "${{ github.repository == 'xufei5620/xingmang-ai-manager' && github.ref == 'refs/heads/main' && vars.XINGMANG_COS_SYNC_ENABLED == 'true' }}")
  const step = workflow.jobs.sync.steps.find(item => item.env?.CHATGPT_SYNC_PLATFORMS)
  assert.equal(step.env.CHATGPT_SYNC_PLATFORMS, '${{ matrix.platform }}')
  assert.equal(step.run, 'node scripts/sync-chatgpt-official-cos.cjs')
})
