const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { spawn, spawnSync } = require('node:child_process')
const binary = path.resolve('dist-native/macos-system-proxy-test')
const supported = process.platform === 'darwin'
if (supported) { const built = spawnSync(process.execPath, ['scripts/build-macos-system-proxy.cjs', '--test'], { encoding: 'utf8' }); assert.equal(built.status, 0, built.stderr) }
function launch(dir) {
  const child = spawn(binary, ['--journal', path.join(dir, 'journal'), '--fixture', path.join(dir, 'store')])
  let buffer = ''; let sequence = 0; const waiting = new Map()
  child.stdout.on('data', data => { buffer += data; let end; while ((end = buffer.indexOf('\n')) >= 0) { const msg = JSON.parse(buffer.slice(0, end)); buffer = buffer.slice(end + 1); waiting.get(msg.id)?.(msg); waiting.delete(msg.id) } })
  child.on('error', () => {})
  return { child, rpc(op, port) { return new Promise((resolve, reject) => { const id = ++sequence; const timer = setTimeout(() => reject(Error('reply timeout')), 10000); waiting.set(id, value => { clearTimeout(timer); resolve(value) }); child.stdin.write(JSON.stringify({ id, op, ...(port ? { port } : {}) }) + '\n') }) } }
}
function fixture() { const dir = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'xm-proxy-'))); fs.writeFileSync(path.join(dir, 'store'), JSON.stringify({ services: { wifi: { HTTPEnable: 0, ProxyAutoConfigEnable: 1, ProxyAutoConfigURLString: 'https://example.invalid/pac', ExceptionsList: ['local'], Custom: 'keep' } } })); return dir }
function read(dir) { return JSON.parse(fs.readFileSync(path.join(dir, 'store'))) }
function write(dir, data) { fs.writeFileSync(path.join(dir, 'store'), JSON.stringify(data)) }
test('waits for asynchronously published proxy state before deciding enable failed', { skip: !supported }, async t => {
  const dir = fixture()
  const data = read(dir)
  data.applied = JSON.parse(JSON.stringify(data.services))
  data.delayAppliedReads = 3
  write(dir, data)
  const h = launch(dir)
  t.after(() => { h.child.kill('SIGKILL'); fs.rmSync(dir, { recursive: true, force: true }) })
  assert.equal((await h.rpc('enable', 17890)).ok, true)
  assert.equal(read(dir).applied.wifi.HTTPPort, 17890)
  assert.equal((await h.rpc('restore')).ok, true)
  assert.equal(read(dir).applied.wifi.ProxyAutoConfigEnable, 1)
  await h.rpc('stop')
})
test('native helper exists', { skip: !supported }, () => assert.ok(fs.existsSync(binary), 'native fixture helper must be compiled'))
test('snapshots PAC and preserves unrelated external fields and changed endpoints', { skip: !supported }, async t => { const dir = fixture(); const h = launch(dir); t.after(() => { h.child.kill('SIGKILL'); fs.rmSync(dir, { recursive: true, force: true }) }); assert.equal((await h.rpc('enable', 17890)).ok, true); let data = read(dir); assert.equal(data.services.wifi.ProxyAutoConfigEnable, 0); data.services.wifi.Custom = 'external'; write(dir, data); assert.equal((await h.rpc('restore')).ok, true); data = read(dir); assert.equal(data.services.wifi.ProxyAutoConfigEnable, 1); assert.equal(data.services.wifi.Custom, 'external'); assert.equal(data.services.wifi.HTTPProxy, undefined); await h.rpc('enable', 17890); data = read(dir); data.services.wifi.HTTPProxy = 'other'; write(dir, data); assert.equal((await h.rpc('restore')).ok, false); assert.equal(fs.existsSync(path.join(dir, 'journal')), true); assert.equal(read(dir).services.wifi.HTTPProxy, 'other'); data = read(dir); data.services.wifi.HTTPSProxy = 'other'; data.services.wifi.SOCKSProxy = 'other'; data.services.wifi.HTTPPort = 18888; data.services.wifi.HTTPSPort = 18888; data.services.wifi.SOCKSPort = 18888; write(dir, data); assert.equal((await h.rpc('stop')).ok, true) })
test('competing owner refused and SIGKILL journal recovered', { skip: !supported }, async t => { const dir = fixture(); const h = launch(dir); let other; t.after(() => { h.child.kill('SIGKILL'); other?.child.kill('SIGKILL'); fs.rmSync(dir, { recursive: true, force: true }) }); await h.rpc('enable', 17890); other = launch(dir); assert.equal((await other.rpc('enable', 17891)).ok, false); other.child.kill('SIGKILL'); await new Promise(resolve => { h.child.once('exit', resolve); h.child.kill('SIGKILL') }); other = launch(dir); assert.equal((await other.rpc('recover')).ok, true); assert.equal(read(dir).services.wifi.ProxyAutoConfigEnable, 1); assert.equal(fs.existsSync(path.join(dir, 'journal')), false); await other.rpc('stop') })
test('failed restoration retains journal and EOF restores', { skip: !supported }, async t => { const dir = fixture(); const h = launch(dir); t.after(() => { h.child.kill('SIGKILL'); fs.rmSync(dir, { recursive: true, force: true }) }); await h.rpc('enable', 17890); let data = read(dir); data.failWrite = true; write(dir, data); assert.equal((await h.rpc('restore')).ok, false); assert.equal(fs.existsSync(path.join(dir, 'journal')), true); data.failWrite = false; write(dir, data); const exited = new Promise(resolve => h.child.once('exit', resolve)); h.child.stdin.end(); await exited; assert.equal(read(dir).services.wifi.ProxyAutoConfigEnable, 1) })

test('authorization denial leaves configuration untouched and reads never authorize', { skip: !supported }, async t => { const dir = fixture(); let data = read(dir); data.denyAuthorization = true; write(dir, data); const before = fs.readFileSync(path.join(dir, 'store'), 'utf8'); const h = launch(dir); t.after(() => { h.child.kill('SIGKILL'); fs.rmSync(dir, { recursive: true, force: true }) }); assert.equal((await h.rpc('inspect')).ok, true); assert.equal((await h.rpc('recover')).ok, true); const reply = await h.rpc('enable', 17890); assert.equal(reply.ok, false); assert.equal(reply.error, 'authorization'); assert.equal(fs.readFileSync(path.join(dir, 'store'), 'utf8'), before); assert.equal(fs.existsSync(path.join(dir, 'journal')), false); await h.rpc('stop') })
test('partial enable failure retains recoverable snapshot and PID reuse identity does not block', { skip: !supported }, async t => { const dir = fixture(); const h = launch(dir); let next; t.after(() => { h.child.kill('SIGKILL'); next?.child.kill('SIGKILL'); fs.rmSync(dir, { recursive: true, force: true }) }); let data = read(dir); data.partialWrite = true; data.services.ethernet = { HTTPEnable: 0 }; write(dir, data); assert.equal((await h.rpc('enable', 17890)).ok, false); assert.equal(fs.existsSync(path.join(dir, 'journal')), true); await new Promise(resolve => { h.child.once('exit', resolve); h.child.kill('SIGKILL') }); let journal = JSON.parse(fs.readFileSync(path.join(dir, 'journal'))); journal.pid = process.pid; journal.identity = '1:1'; fs.writeFileSync(path.join(dir, 'journal'), JSON.stringify(journal)); data = read(dir); data.partialWrite = false; write(dir, data); next = launch(dir); assert.equal((await next.rpc('recover')).ok, true); assert.equal(read(dir).services.wifi.HTTPEnable, 0); assert.equal(read(dir).services.ethernet.HTTPEnable, 0); await next.rpc('stop') })

test('controlled flag conflict retains owned endpoints and recovery journal', { skip: !supported }, async t => { const dir = fixture(); const h = launch(dir); t.after(() => { h.child.kill('SIGKILL'); fs.rmSync(dir, { recursive: true, force: true }) }); await h.rpc('enable', 17890); let data = read(dir); data.services.wifi.ProxyAutoConfigEnable = 1; write(dir, data); assert.equal((await h.rpc('restore')).ok, false); assert.equal(fs.existsSync(path.join(dir, 'journal')), true); assert.equal(read(dir).services.wifi.HTTPProxy, '127.0.0.1') })
test('corrupted owner metadata fails closed', { skip: !supported }, async t => { const dir = fixture(); const h = launch(dir); let next; t.after(() => { h.child.kill('SIGKILL'); next?.child.kill('SIGKILL'); fs.rmSync(dir, { recursive: true, force: true }) }); await h.rpc('enable', 17890); await new Promise(resolve => { h.child.once('exit', resolve); h.child.kill('SIGKILL') }); const journal = JSON.parse(fs.readFileSync(path.join(dir, 'journal'))); journal.pid = -1; fs.writeFileSync(path.join(dir, 'journal'), JSON.stringify(journal)); const before = fs.readFileSync(path.join(dir, 'store'), 'utf8'); next = launch(dir); assert.equal((await next.rpc('recover')).ok, false); assert.equal(fs.readFileSync(path.join(dir, 'store'), 'utf8'), before); assert.equal(fs.existsSync(path.join(dir, 'journal')), true) })

test('corrupted expected endpoint dictionary fails closed', { skip: !supported }, async t => { const dir = fixture(); const h = launch(dir); let next; t.after(() => { h.child.kill('SIGKILL'); next?.child.kill('SIGKILL'); fs.rmSync(dir, { recursive: true, force: true }) }); await h.rpc('enable', 17890); await new Promise(resolve => { h.child.once('exit', resolve); h.child.kill('SIGKILL') }); const journal = JSON.parse(fs.readFileSync(path.join(dir, 'journal'))); journal.entries.wifi.expected = Buffer.from('<?xml version="1.0"?><plist version="1.0"><dict><key>HTTPProxy</key><string>external.invalid</string></dict></plist>').toString('base64'); fs.writeFileSync(path.join(dir, 'journal'), JSON.stringify(journal)); const before = fs.readFileSync(path.join(dir, 'store'), 'utf8'); next = launch(dir); assert.equal((await next.rpc('recover')).ok, false); assert.equal(fs.readFileSync(path.join(dir, 'store'), 'utf8'), before); assert.equal(fs.existsSync(path.join(dir, 'journal')), true) })
test('production inspect succeeds without authorization or a recovery journal', { skip: !supported || !fs.existsSync(path.resolve(`dist-native/macos-system-proxy-${process.arch}`)) }, () => {
  const dir = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'xm-proxy-readonly-')))
  try {
    const result = spawnSync(path.resolve(`dist-native/macos-system-proxy-${process.arch}`), ['--journal', path.join(dir, 'journal')], {
      input: '{"id":1,"op":"inspect"}\n{"id":2,"op":"stop"}\n', encoding: 'utf8', timeout: 10000,
    })
    assert.equal(result.status, 0)
    const replies = result.stdout.trim().split('\n').map(JSON.parse)
    assert.equal(replies[0].id, 1)
    assert.equal(replies[0].ok, true)
    assert.equal(replies[1].ok, true)
    assert.equal(fs.existsSync(path.join(dir, 'journal')), false)
  } finally { fs.rmSync(dir, { recursive: true, force: true }) }
})
test('restore retries application after persistence succeeded but apply failed', { skip: !supported }, async t => {
  const dir = fixture(); const h = launch(dir)
  t.after(() => { h.child.kill('SIGKILL'); fs.rmSync(dir, { recursive: true, force: true }) })
  assert.equal((await h.rpc('enable', 17890)).ok, true)
  let data = read(dir); data.failApplyOnce = true; write(dir, data)
  assert.equal((await h.rpc('restore')).ok, false)
  data = read(dir)
  assert.equal(data.services.wifi.HTTPEnable, 0)
  assert.equal(data.applied.wifi.HTTPEnable, 1)
  assert.equal(fs.existsSync(path.join(dir, 'journal')), true)
  assert.equal((await h.rpc('restore')).ok, true)
  assert.equal(read(dir).applied.wifi.HTTPEnable, 0)
  assert.equal(fs.existsSync(path.join(dir, 'journal')), false)
  await h.rpc('stop')
})
test('oversized encoded journal is rejected before proxy persistence', { skip: !supported }, async t => {
  const dir = fixture(); const h = launch(dir)
  t.after(() => { h.child.kill('SIGKILL'); fs.rmSync(dir, { recursive: true, force: true }) })
  const data = read(dir); data.services.wifi.Custom = 'x'.repeat(410000); write(dir, data)
  const before = fs.readFileSync(path.join(dir, 'store'), 'utf8')
  assert.equal((await h.rpc('enable', 17890)).ok, false)
  assert.equal(fs.readFileSync(path.join(dir, 'store'), 'utf8'), before)
  assert.equal(fs.existsSync(path.join(dir, 'journal')), false)
  await h.rpc('stop')
})
test('denied authorization releases an idle owner lock for another instance', { skip: !supported }, async t => {
  const dir = fixture(); const first = launch(dir); const second = launch(dir)
  t.after(() => { first.child.kill('SIGKILL'); second.child.kill('SIGKILL'); fs.rmSync(dir, { recursive: true, force: true }) })
  let data = read(dir); data.denyAuthorization = true; write(dir, data)
  assert.equal((await first.rpc('enable', 17890)).error, 'authorization')
  await first.rpc('restore')
  data = read(dir); data.denyAuthorization = false; write(dir, data)
  assert.equal((await second.rpc('enable', 17891)).ok, true)
  await second.rpc('stop'); await first.rpc('stop')
})
test('inactive saved service restores persisted settings without an applied entry', { skip: !supported }, async t => {
  const dir = fixture(); const h = launch(dir)
  t.after(() => { h.child.kill('SIGKILL'); fs.rmSync(dir, { recursive: true, force: true }) })
  assert.equal((await h.rpc('enable', 17890)).ok, true)
  const data = read(dir); data.inactiveServices = ['wifi']; write(dir, data)
  assert.equal((await h.rpc('restore')).ok, true)
  assert.equal(read(dir).services.wifi.HTTPEnable, 0)
  assert.equal(read(dir).applied.wifi, undefined)
  assert.equal(fs.existsSync(path.join(dir, 'journal')), false)
  await h.rpc('stop')
})
test('active saved service missing its applied dictionary retains recovery', { skip: !supported }, async t => {
  const dir = fixture(); const h = launch(dir)
  t.after(() => { h.child.kill('SIGKILL'); fs.rmSync(dir, { recursive: true, force: true }) })
  assert.equal((await h.rpc('enable', 17890)).ok, true)
  const data = read(dir); data.missingAppliedServices = ['wifi']; write(dir, data)
  assert.equal((await h.rpc('restore')).ok, false)
  assert.equal(read(dir).services.wifi.HTTPEnable, 0)
  assert.equal(fs.existsSync(path.join(dir, 'journal')), true)
})
test('inactive service with still-owned applied endpoints retains recovery', { skip: !supported }, async t => {
  const dir = fixture(); const h = launch(dir)
  t.after(() => { h.child.kill('SIGKILL'); fs.rmSync(dir, { recursive: true, force: true }) })
  assert.equal((await h.rpc('enable', 17890)).ok, true)
  const data = read(dir); data.inactiveServices = ['wifi']; data.staleAppliedServices = ['wifi']; write(dir, data)
  assert.equal((await h.rpc('restore')).ok, false)
  assert.equal(read(dir).applied.wifi.HTTPEnable, 1)
  assert.equal(fs.existsSync(path.join(dir, 'journal')), true)
})
test('EOF during slow authorization cancels enable before any journal or proxy write', { skip: !supported }, async t => {
  const dir = fixture(); const h = launch(dir)
  t.after(() => { h.child.kill('SIGKILL'); fs.rmSync(dir, { recursive: true, force: true }) })
  const data = read(dir); data.authorizationDelayMs = 150; write(dir, data)
  const before = fs.readFileSync(path.join(dir, 'store'), 'utf8')
  const reply = h.rpc('enable', 17890)
  await new Promise(resolve => setTimeout(resolve, 30))
  const exited = new Promise(resolve => h.child.once('exit', resolve))
  h.child.stdin.end()
  assert.equal((await reply).ok, false)
  await exited
  assert.equal(fs.readFileSync(path.join(dir, 'store'), 'utf8'), before)
  assert.equal(fs.existsSync(path.join(dir, 'journal')), false)
})
test('queued request flood cancels bounded native work without proxy mutation', { skip: !supported }, async t => {
  const dir = fixture(); const h = launch(dir)
  t.after(() => { h.child.kill('SIGKILL'); fs.rmSync(dir, { recursive: true, force: true }) })
  const data = read(dir); data.authorizationDelayMs = 150; write(dir, data)
  const before = fs.readFileSync(path.join(dir, 'store'), 'utf8')
  const exited = new Promise(resolve => h.child.once('exit', resolve))
  h.child.stdin.write(Array.from({ length: 100 }, (_, i) => JSON.stringify({ id: i + 1, op: 'enable', port: 17890 })).join('\n') + '\n')
  h.child.stdin.end()
  await exited
  assert.equal(fs.readFileSync(path.join(dir, 'store'), 'utf8'), before)
  assert.equal(fs.existsSync(path.join(dir, 'journal')), false)
})
